/* Run with PLAYWRIGHT_MODULE pointing to an existing Playwright install, if needed.
   Serves only game assets and the shared theme; never starts app.js or a database. */
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
const fs = require('node:fs');
const express = require('express');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const Cube = require('../vendor/cube');
const root = path.resolve(__dirname, '../../..');
const output = process.env.CUBE_SCREENSHOTS || path.join(os.tmpdir(), 'rubiks-cube-browser');
const app = express();
app.use('/rubiks-cube', express.static(path.join(root, 'games/rubiks-cube')));
app.use('/css', express.static(path.join(root, 'public/css')));
const server = app.listen(0, '127.0.0.1', async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
  const checks = [], errors = [], requests = [];
  const check = (name, condition) => { assert.ok(condition, name); checks.push(name); };
  const url = `http://127.0.0.1:${server.address().port}/rubiks-cube/`;
  const state = page => page.locator('#net .sticker').evaluateAll(elements => {
    const result = [];
    for (const element of elements) result[Number(element.dataset.index)] = element.dataset.color;
    return result.join('');
  });
  const settle = page => page.locator('#gameMode:enabled').waitFor();
  try {
    fs.mkdirSync(output, { recursive: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => requests.push(request.url()));
    await page.goto(url);
    await page.locator('[data-move="R"]:enabled').waitFor();
    const solved = new Cube().asString();
    check('initial cube is solved', await state(page) === solved);
    await page.screenshot({ path: path.join(output, 'desktop.png'), fullPage: true });
    await page.locator('[data-move="R"]').click();
    await settle(page);
    check('face buttons update real cube state', await state(page) === new Cube().move('R').asString());
    await page.locator('#undo').click();
    await settle(page);
    check('undo restores previous cube', await state(page) === solved);
    await page.keyboard.press('f');
    await settle(page);
    await page.keyboard.press('Shift+F');
    await settle(page);
    check('keyboard and inverse keyboard turns match', await state(page) === solved);
    const canvas = await page.locator('#cube').boundingBox();
    await page.mouse.move(canvas.x + canvas.width / 2, canvas.y + canvas.height / 2);
    await page.mouse.down();
    await page.mouse.move(canvas.x + 70, canvas.y + 70, { steps: 5 });
    await page.mouse.up();
    check('orbit does not mutate cube', await state(page) === solved);
    await page.locator('#resetView').click();
    await page.locator('#scramble').click();
    await settle(page);
    const scrambled = await state(page);
    check('scramble creates an unsolved legal state', scrambled !== solved && Cube.fromString(scrambled).asString() === scrambled);
    await page.locator('#solveMode').click();
    check('solver starts with the current game', await state(page) === scrambled);
    await page.locator('#clearEntry').click();
    await page.locator('#palette [data-color="R"]').click();
    await page.locator('.sticker[data-index="0"]').click();
    await page.locator('#findSolution').click();
    check('bad color counts show actionable validation', /nine stickers/.test(await page.locator('#status').innerText()));
    await page.locator('#clearEntry').click();
    const entered = new Cube().move("R U F2 L' D B2").asString();
    // Input through the actual color palette and sticker buttons, not a test-only model API.
    for (const color of ['U', 'R', 'F', 'D', 'L', 'B']) {
      await page.locator(`#palette [data-color="${color}"]`).click();
      for (let i = 0; i < 54; i++) if (i % 9 !== 4 && entered[i] === color && entered[i] !== solved[i]) await page.locator(`.sticker[data-index="${i}"]`).click();
    }
    check('manual entry preserves face orientation', await state(page) === entered);
    await page.locator('#findSolution').click();
    await page.locator('#player:not([hidden])').waitFor({ timeout: 45000 });
    check('real worker computes entered cube solution', /Found a \d+-turn/.test(await page.locator('#status').innerText()));
    await page.screenshot({ path: path.join(output, 'solution.png'), fullPage: true });
    await page.locator('#next').click();
    await settle(page);
    check('next advances exactly one step', /^1 of/.test(await page.locator('#stepCount').innerText()));
    await page.locator('#back').click();
    await settle(page);
    check('back restores the entered configuration', await state(page) === entered);
    await page.locator('#speed').fill('1');
    await page.locator('#play').click();
    await page.locator('#play').click();
    await settle(page);
    const paused = await state(page);
    await page.waitForTimeout(1200);
    check('pause prevents further turns', await state(page) === paused);
    await page.locator('#play').click();
    await page.waitForFunction(() => document.getElementById('cubeBadge').textContent === 'Solved', null, { timeout: 35000 });
    check('animated solution solves manually entered cube', await state(page) === solved);
    await page.locator('#replay').click();
    check('replay restores solution starting state', await state(page) === entered);
    await page.locator('#gameMode').click();
    check('solving preserves the separate game', await state(page) === scrambled);
    await page.locator('#reset').click();
    check('reset returns game to solved', await state(page) === solved);
    await page.locator('#solveMode').click();
    await page.locator('#findSolution').click();
    check('already solved cube has zero-turn solution', await page.locator('#stepCount').innerText() === '0 of 0 turns complete');
    check('completed solution disables play', await page.locator('#play').isDisabled());
    // A stalled worker verifies cancellation without any external network or server work.
    const stalled = await browser.newPage();
    await stalled.route('**/js/solver-worker.js', route => route.fulfill({ contentType: 'application/javascript', body: 'self.onmessage = () => {};' }));
    await stalled.goto(url);
    await stalled.locator('[data-move="R"]').click();
    await settle(stalled);
    await stalled.locator('#solveMode').click();
    await stalled.locator('#findSolution').click();
    await stalled.locator('#cancelSearch').click();
    await stalled.locator('#findSolution:visible').waitFor();
    check('cancel returns to editable cube', /cancelled/.test(await stalled.locator('#status').innerText()) && await stalled.locator('.sticker[data-index="0"]').isEnabled());
    await stalled.close();
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
    mobile.on('pageerror', error => errors.push(error.message));
    await mobile.goto(url);
    await mobile.locator('[data-move="R"]').tap();
    await settle(mobile);
    check('touch turns work with reduced motion', await state(mobile) === new Cube().move('R').asString());
    await mobile.locator('#solveMode').tap();
    check('mobile has no horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await mobile.screenshot({ path: path.join(output, 'mobile.png'), fullPage: true });
    await mobile.locator('#findSolution').tap();
    await mobile.locator('#player:not([hidden])').waitFor({ timeout: 45000 });
    await mobile.locator('#next').tap();
    await settle(mobile);
    const mobileCube = await mobile.locator('#cube').boundingBox();
    check('cube stays visible while using mobile playback controls', mobileCube.y >= 0 && mobileCube.y + mobileCube.height < 844);
    await mobile.screenshot({ path: path.join(output, 'mobile-playback.png') });
    check('no page errors', errors.length === 0);
    check('all runtime requests stay local', requests.every(request => request.startsWith(url) || request.startsWith(url.replace('/rubiks-cube/', '/css/'))));
    console.log(JSON.stringify({ checks, errors, screenshots: output }, null, 2));
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  } finally {
    await browser.close();
    server.close();
  }
});
