'use strict';

const DINO_UI = {
  en: {
    metaTitle: 'The history of the dinosaurs',
    metaDescription: 'A cinematic, narrated journey for children through the Triassic, Jurassic and Cretaceous—ending with the dinosaurs still around us.',
    skipLink: 'Skip to the current chapter',
    backLabel: 'Back to all games',
    brandName: 'DEEP TIME',
    brandSubtitle: 'Dinosaur field journey',
    infoLabel: 'Open controls, media notes and sources',
    languageLabel: 'Language',
    switchLanguage: 'Switch to Japanese',
    introLanguageLegend: 'Choose your language',
    englishLanguage: 'English',
    japaneseLanguage: '日本語',
    introOverline: 'OPEN THE DEEP-TIME DOOR',
    introTitle: 'The history of the dinosaurs',
    introLede: 'Walk through three changing worlds. Meet small pioneers, feathered fliers and famous giants—and discover why they never all shared one stage.',
    journeyOverview: 'Journey overview',
    chaptersStat: 'chapters',
    durationStat: 'minutes',
    quizzesStat: 'discoveries',
    introCoordinatePrimary: 'MESOZOIC · 252—66 Ma',
    introCoordinateSecondary: 'TRIASSIC / JURASSIC / CRETACEOUS',
    periodTriassic: 'TRIASSIC',
    periodJurassic: 'JURASSIC',
    periodCretaceous: 'CRETACEOUS',
    startKicker: 'English narration',
    startAction: 'Begin the journey',
    headphoneNote: 'Headphones recommended · narration can be changed any time',
    storyStageLabel: 'A journey through dinosaur history',
    panelShow: 'Show story panel',
    panelHide: 'Hide story panel',
    panelLocked: 'The story panel stays open until this discovery is answered',
    panelShort: 'Story',
    captionsShow: 'Show transcript',
    captionsHide: 'Hide transcript',
    captionsShort: 'Transcript',
    soundOn: 'Turn narration on',
    soundOff: 'Turn narration off',
    soundShort: 'Sound',
    transcriptTitle: 'Narration transcript',
    transcriptClose: 'Close transcript',
    transcriptLoading: 'Loading the transcript…',
    transcriptUnavailable: 'The transcript could not be loaded. The chapter summary remains available.',
    previous: 'Back',
    previousLabel: 'Go to the previous scene',
    next: 'Next',
    nextLabel: 'Go to the next scene',
    answerToContinue: 'Choose an answer',
    restartNav: 'Start over',
    restartLabel: 'Restart the journey',
    narrationReady: 'Narration ready',
    narrationLoading: 'Loading narration',
    narrationPlaying: 'English narration playing',
    narrationPaused: 'Narration paused',
    narrationComplete: 'Narration complete',
    narrationMuted: 'Narration is off',
    narrationError: 'Audio unavailable—open the transcript instead',
    narrationProgress: 'Narration progress',
    replayNarration: 'Replay this scene’s narration',
    artDisclosure: 'Artist’s reconstruction',
    termLabel: 'Field word',
    quizLabel: 'Discovery',
    quizGroupLabel: 'Choose one answer',
    correctLead: 'You found it!',
    discoveryLead: 'Good investigation!',
    quizRequiredAnnouncement: 'The story panel opened so you can answer this discovery.',
    panelShownAnnouncement: 'Story panel shown.',
    panelHiddenAnnouncement: 'Story panel hidden. Artwork, narration and all controls remain available.',
    captionsShownAnnouncement: 'Transcript shown.',
    captionsHiddenAnnouncement: 'Transcript hidden.',
    soundOnAnnouncement: 'Narration turned on.',
    soundOffAnnouncement: 'Narration turned off.',
    languageChangedAnnouncement: 'Language changed to English.',
    sceneAnnouncement: 'Scene {current} of {total}: {title}',
    progressLabel: 'Journey progress',
    progressSceneLabel: 'Go to scene {number}: {title}',
    finaleQuizzesLabel: 'Discoveries visited',
    finaleComplete: 'All three discoveries explored',
    finaleOpen: 'You can revisit any discovery from the timeline',
    restartAction: 'Travel again',
    infoOverline: 'FIELD NOTES',
    infoTitle: 'About this journey',
    controlsTitle: 'Controls',
    controlsBody: 'Use the arrow buttons or ← and → to travel. Press 1–3 to answer a discovery, R to replay narration, C for the transcript, M for sound, P for the story panel, and L to change language.',
    panelHelpTitle: 'Image-and-narration mode',
    panelHelpBody: 'Hide the glass story panel whenever you want a clearer view of the artwork. A discovery opens it automatically and restores your saved preference after you leave.',
    mediaTitle: 'Generated media',
    mediaBody: 'The prehistoric scenes are original AI-generated artist’s reconstructions made for this journey. They are guided by current evidence, but colors, soft tissues and behavior are partly uncertain. They are not photographs.',
    narrationDisclosureTitle: 'Narration',
    narrationDisclosureBody: 'English narration uses the local Piper Lessac voice. Japanese narration uses the local Voicevox Shikoku Metan voice. Audio is generated and stored locally; no speech service is contacted while you watch.',
    evidenceTitle: 'How the science is handled',
    evidenceBody: 'Dates are rounded. Fossil ranges show the oldest and youngest fossils currently known—not the exact first and last individual. New discoveries can change a range or a reconstruction.',
    motionTitle: 'Comfort and access',
    motionBody: 'Your reduced-motion setting removes decorative movement. Narration begins only after you start. The transcript, language, sound, navigation and progress controls remain available when the story panel is hidden.',
    sourcesTitle: 'Research sources',
    sourcesIntro: 'The story was checked against the current geological chart and museum, university and space-agency material. Links open the original source.',
    closeDialog: 'Close information',
    sourcesForScene: 'Sources for this scene',
    noscript: 'This journey needs JavaScript enabled.',
  },
  ja: {
    metaTitle: '恐竜の歴史',
    metaDescription: '三畳紀、ジュラ紀、白亜紀をめぐり、今も生きる恐竜へつながる、子どものための映画のような音声ガイド。',
    skipLink: '今の章へ移動',
    backLabel: 'ゲーム一覧へ戻る',
    brandName: 'DEEP TIME',
    brandSubtitle: '恐竜・時間旅行',
    infoLabel: '操作方法、メディアについて、出典を開く',
    languageLabel: '言語',
    switchLanguage: '英語に切り替える',
    introLanguageLegend: '言語を選んでください',
    englishLanguage: 'English',
    japaneseLanguage: '日本語',
    introOverline: '深い時間への扉をひらこう',
    introTitle: '恐竜の歴史',
    introLede: '三つの変わりゆく世界を歩きます。小さな先駆者、羽毛をもつ仲間、有名な巨人たち。じつは、みんなが同じ時代にいたわけではありません。',
    journeyOverview: '旅の概要',
    chaptersStat: 'つの章',
    durationStat: '分ほど',
    quizzesStat: 'つの発見',
    introCoordinatePrimary: '中生代・約2億5200万〜6600万年前',
    introCoordinateSecondary: '三畳紀・ジュラ紀・白亜紀',
    periodTriassic: '三畳紀',
    periodJurassic: 'ジュラ紀',
    periodCretaceous: '白亜紀',
    startKicker: '日本語ナレーション',
    startAction: '時間旅行をはじめる',
    headphoneNote: 'イヤホン推奨・音声はいつでも切り替えられます',
    storyStageLabel: '恐竜の歴史をめぐる旅',
    panelShow: '物語パネルを表示',
    panelHide: '物語パネルを隠す',
    panelLocked: 'この発見に答えるまで、物語パネルは隠せません',
    panelShort: '物語',
    captionsShow: '字幕を表示',
    captionsHide: '字幕を隠す',
    captionsShort: '字幕',
    soundOn: 'ナレーションをオンにする',
    soundOff: 'ナレーションをオフにする',
    soundShort: '音声',
    transcriptTitle: 'ナレーション字幕',
    transcriptClose: '字幕を閉じる',
    transcriptLoading: '字幕を読み込んでいます…',
    transcriptUnavailable: '字幕を読み込めませんでした。章の短い説明はそのまま読めます。',
    previous: 'もどる',
    previousLabel: '前の場面へ',
    next: 'つぎへ',
    nextLabel: '次の場面へ',
    answerToContinue: '答えを選ぼう',
    restartNav: '最初へ',
    restartLabel: '旅を最初から見る',
    narrationReady: 'ナレーションの準備ができました',
    narrationLoading: 'ナレーションを読み込み中',
    narrationPlaying: '日本語ナレーションを再生中',
    narrationPaused: 'ナレーションを一時停止',
    narrationComplete: 'ナレーションを聞き終えました',
    narrationMuted: 'ナレーションはオフです',
    narrationError: '音声を再生できません・字幕をご利用ください',
    narrationProgress: 'ナレーションの進み具合',
    replayNarration: 'この場面のナレーションをもう一度聞く',
    artDisclosure: '想像復元画',
    termLabel: 'フィールドワード',
    quizLabel: '発見',
    quizGroupLabel: '答えを一つ選んでください',
    correctLead: '見つけたね！',
    discoveryLead: 'いい調査です！',
    quizRequiredAnnouncement: '発見に答えられるよう、物語パネルを表示しました。',
    panelShownAnnouncement: '物語パネルを表示しました。',
    panelHiddenAnnouncement: '物語パネルを隠しました。画像、音声、すべての操作は引き続き使えます。',
    captionsShownAnnouncement: '字幕を表示しました。',
    captionsHiddenAnnouncement: '字幕を隠しました。',
    soundOnAnnouncement: 'ナレーションをオンにしました。',
    soundOffAnnouncement: 'ナレーションをオフにしました。',
    languageChangedAnnouncement: '日本語に切り替えました。',
    sceneAnnouncement: '{total}場面中{current}場面目、{title}',
    progressLabel: '旅の進み具合',
    progressSceneLabel: '{number}場面目「{title}」へ移動',
    finaleQuizzesLabel: '立ち寄った発見',
    finaleComplete: '三つの発見をすべて調査しました',
    finaleOpen: 'タイムラインから、いつでも発見へ戻れます',
    restartAction: 'もう一度旅する',
    infoOverline: 'フィールドノート',
    infoTitle: 'この旅について',
    controlsTitle: '操作',
    controlsBody: '画面の矢印、またはキーボードの ← と → で移動します。1〜3で発見に回答、Rで音声を再生、Cで字幕、Mで音声、Pで物語パネル、Lで言語を切り替えます。',
    panelHelpTitle: '画像とナレーションで楽しむモード',
    panelHelpBody: 'ガラスの物語パネルを隠すと、復元画を広く見られます。発見の場面では自動で開き、場面を離れると保存していた表示設定に戻ります。',
    mediaTitle: '生成メディア',
    mediaBody: '太古の場面は、この旅のためにAIで制作したオリジナルの想像復元画です。現在の証拠を参考にしていますが、色、やわらかい組織、行動には不明な点があります。写真ではありません。',
    narrationDisclosureTitle: 'ナレーション',
    narrationDisclosureBody: '英語音声はローカルのPiper・Lessac、日本語音声はローカルのVoicevox・四国めたんで作りました。音声は端末内で生成して保存してあり、視聴中に外部の音声サービスへ接続しません。',
    evidenceTitle: '科学の伝え方',
    evidenceBody: '年代は分かりやすく丸めています。化石が見つかる年代の幅は、現在知られている最古と最新の化石を示すもので、最初と最後の一頭を正確に示すものではありません。新発見で変わることがあります。',
    motionTitle: '快適さとアクセシビリティ',
    motionBody: '端末の「動きを減らす」設定では、飾りの動きを止めます。音声は開始操作のあとにだけ再生します。パネルを隠しても、字幕、言語、音声、移動、進行ボタンは残ります。',
    sourcesTitle: '調査に使った出典',
    sourcesIntro: '最新の地質年代表と、博物館、大学、宇宙機関の資料で内容を確認しました。リンク先は原典です。',
    closeDialog: '情報を閉じる',
    sourcesForScene: 'この場面の出典',
    noscript: 'この旅にはJavaScriptが必要です。',
  },
};

const DINO_SOURCES = [
  {
    id: 'ics-chart',
    url: 'https://stratigraphy.org/ICSchart/ChronostratChart2024-12.pdf',
    title: {
      en: 'International Commission on Stratigraphy · International Chronostratigraphic Chart (2024/12)',
      ja: '国際層序委員会・国際年代層序表（2024年12月版）',
    },
  },
  {
    id: 'nhm-when',
    url: 'https://www.nhm.ac.uk/discover/when-did-dinosaurs-live.html',
    title: {
      en: 'Natural History Museum · When did dinosaurs live?',
      ja: 'ロンドン自然史博物館・恐竜はいつ生きていた？',
    },
  },
  {
    id: 'nhm-origins',
    url: 'https://www.nhm.ac.uk/discover/where-did-dinosaurs-come-from.html',
    title: {
      en: 'Natural History Museum · Where did dinosaurs come from?',
      ja: 'ロンドン自然史博物館・恐竜はどこから来た？',
    },
  },
  {
    id: 'amnh-triassic',
    url: 'https://www.amnh.org/explore/ology/ology-cards/262-triassic-period',
    title: {
      en: 'American Museum of Natural History · Triassic Period',
      ja: 'アメリカ自然史博物館・三畳紀',
    },
  },
  {
    id: 'nhm-diplodocus',
    url: 'https://www.nhm.ac.uk/discover/quick-questions/when-did-diplodocus-live.html',
    title: {
      en: 'Natural History Museum · When did Diplodocus live?',
      ja: 'ロンドン自然史博物館・ディプロドクスが生きた時代',
    },
  },
  {
    id: 'nhm-stegosaurus',
    url: 'https://www.nhm.ac.uk/discover/dino-directory/Stegosaurus.html',
    title: {
      en: 'Natural History Museum · Stegosaurus',
      ja: 'ロンドン自然史博物館・ステゴサウルス',
    },
  },
  {
    id: 'nhm-feathers',
    url: 'https://www.nhm.ac.uk/discover/how-did-birds-and-other-dinosaurs-learn-to-fly.html',
    title: {
      en: 'Natural History Museum · How did birds and other dinosaurs learn to fly?',
      ja: 'ロンドン自然史博物館・鳥と恐竜はどう飛ぶようになった？',
    },
  },
  {
    id: 'amnh-feathers',
    url: 'https://www.amnh.org/exhibitions/dinosaurs-ancient-fossils/liaoning-diorama/figuring-out-feathers',
    title: {
      en: 'American Museum of Natural History · Figuring Out Feathers',
      ja: 'アメリカ自然史博物館・羽毛を読み解く',
    },
  },
  {
    id: 'nhm-spinosaurus',
    url: 'https://www.nhm.ac.uk/discover/dino-directory/spinosaurus.html',
    title: {
      en: 'Natural History Museum · Spinosaurus',
      ja: 'ロンドン自然史博物館・スピノサウルス',
    },
  },
  {
    id: 'nhm-velociraptor',
    url: 'https://www.nhm.ac.uk/discover/dino-directory/velociraptor.html',
    title: {
      en: 'Natural History Museum · Velociraptor',
      ja: 'ロンドン自然史博物館・ヴェロキラプトル',
    },
  },
  {
    id: 'amnh-eggs',
    url: 'https://www.amnh.org/dinosaurs/dinosaur-eggs',
    title: {
      en: 'American Museum of Natural History · Dinosaur Eggs',
      ja: 'アメリカ自然史博物館・恐竜の卵',
    },
  },
  {
    id: 'nhm-tyrannosaurus',
    url: 'https://www.nhm.ac.uk/discover/dino-directory/tyrannosaurus.html',
    title: {
      en: 'Natural History Museum · Tyrannosaurus',
      ja: 'ロンドン自然史博物館・ティラノサウルス',
    },
  },
  {
    id: 'nhm-triceratops',
    url: 'https://www.nhm.ac.uk/discover/dino-directory/triceratops.html',
    title: {
      en: 'Natural History Museum · Triceratops',
      ja: 'ロンドン自然史博物館・トリケラトプス',
    },
  },
  {
    id: 'smithsonian-last',
    url: 'https://naturalhistory.si.edu/exhibits/last-american-dinosaurs-discovering-lost-world',
    title: {
      en: 'Smithsonian National Museum of Natural History · The Last American Dinosaurs',
      ja: 'スミソニアン国立自然史博物館・北アメリカ最後の恐竜',
    },
  },
  {
    id: 'nhm-evidence',
    url: 'https://www.nhm.ac.uk/discover/what-can-scientists-learn-about-dinosaurs-and-how.html',
    title: {
      en: 'Natural History Museum · What can scientists learn about dinosaurs?',
      ja: 'ロンドン自然史博物館・恐竜の何が、どう分かる？',
    },
  },
  {
    id: 'nhm-tracks',
    url: 'https://www.nhm.ac.uk/discover/dinosaur-footprints.html',
    title: {
      en: 'Natural History Museum · Dinosaur footprints',
      ja: 'ロンドン自然史博物館・恐竜の足あと',
    },
  },
  {
    id: 'nhm-extinction',
    url: 'https://www.nhm.ac.uk/discover/dinosaur-extinction.html',
    title: {
      en: 'Natural History Museum · What killed the dinosaurs?',
      ja: 'ロンドン自然史博物館・恐竜を絶滅させたもの',
    },
  },
  {
    id: 'nasa-chicxulub',
    url: 'https://science.nasa.gov/earth/earth-observatory/sediment-swirls-off-the-yucatan-149114/',
    title: {
      en: 'NASA Earth Observatory · Sediment Swirls Off the Yucatán',
      ja: 'NASA地球観測所・ユカタン半島とチクシュルーブ衝突跡',
    },
  },
  {
    id: 'smithsonian-birds',
    url: 'https://www.si.edu/stories/could-dinosaurs-still-exist',
    title: {
      en: 'Smithsonian Institution · Could dinosaurs still exist?',
      ja: 'スミソニアン協会・恐竜は今も生きている？',
    },
  },
  {
    id: 'fukui-periods',
    url: 'https://www.dinosaur.pref.fukui.jp/dino/faq/r02015.html',
    title: {
      en: 'Fukui Prefectural Dinosaur Museum · Names of the dinosaur periods',
      ja: '福井県立恐竜博物館・恐竜が生きていた時代の名前は？',
    },
  },
];

const DINO_SCENES = [
  {
    id: 'deep-time-gateway',
    kind: 'story',
    image: 'assets/images/deep-time-gateway.webp',
    audio: 'deep-time-gateway',
    tone: 'gateway',
    layout: 'left',
    focal: { x: 53, y: 48 },
    sources: ['ics-chart', 'nhm-when', 'fukui-periods'],
    copy: {
      en: {
        progress: 'Deep time',
        eyebrow: '01 · SET THE TIME COMPASS',
        date: '252–66 million years ago',
        title: 'One age? Three changing worlds.',
        lede: 'Dinosaur history lasted so long that continents split and new oceans opened while it was still unfolding.',
        facts: [
          { value: '3', label: 'great periods', caption: 'Triassic · Jurassic · Cretaceous' },
          { value: '~186 million', label: 'years of change', caption: 'using today’s rounded boundaries' },
          { value: 'not one cast', label: 'the big surprise', caption: 'famous dinosaurs lived millions of years apart' },
        ],
        note: 'Amazing fact: pterosaurs in the sky and plesiosaurs in the sea were ancient reptiles, but they were not dinosaurs.',
        term: { name: 'deep time', reading: 'deep time', meaning: 'time far beyond a human lifetime' },
        artAlt: 'An amber sunrise opens beyond a fossil-layered canyon, with one small early dinosaur in the distant prehistoric plain.',
      },
      ja: {
        progress: '深い時間',
        eyebrow: '01 · 時間のコンパス',
        date: '約2億5200万〜6600万年前',
        title: '一つの時代？ いいえ、三つの世界。',
        lede: '恐竜の歴史が続くあいだに、大陸は分かれ、新しい海まで生まれました。',
        facts: [
          { value: '3', label: '大きな時代', caption: '三畳紀・ジュラ紀・白亜紀' },
          { value: '約1億8600万年', label: '変化の長さ', caption: '現在の境界を丸めた数字' },
          { value: '同じ顔ぶれではない', label: '最初の大発見', caption: '有名な恐竜どうしも何千万年も離れていた' },
        ],
        note: 'びっくり事実。空を飛んだ翼竜や、海の首長竜は太古の爬虫類ですが、恐竜ではありません。',
        term: { name: 'deep time', reading: 'ディープ・タイム', meaning: '人の一生では想像しにくい、とても長い時間' },
        artAlt: '化石を含む岩の谷の向こうに朝日が差し、太古の平原に小さな初期の恐竜が見える想像復元画。',
      },
    },
  },
  {
    id: 'triassic-beginnings',
    kind: 'story',
    image: 'assets/images/triassic-beginnings.webp',
    audio: 'triassic-beginnings',
    tone: 'triassic',
    layout: 'right',
    focal: { x: 44, y: 53 },
    sources: ['ics-chart', 'nhm-origins', 'amnh-triassic'],
    copy: {
      en: {
        progress: 'Triassic dawn',
        eyebrow: '02 · SMALL BEGINNINGS',
        date: 'about 230 million years ago',
        title: 'The first team was small.',
        lede: 'The earliest well-established dinosaurs were quick, mostly small animals in a hot world joined into one giant continent.',
        facts: [
          { value: 'Pangaea', label: 'one supercontinent', caption: 'nearly all land joined together' },
          { value: '~230 million', label: 'years ago', caption: 'well-established dinosaurs appear' },
          { value: 'underdogs', label: 'not rulers yet', caption: 'larger crocodile relatives shared the land' },
        ],
        note: 'After a mass extinction at the Triassic’s end, many competing groups vanished. Surviving dinosaurs then spread into many new shapes.',
        term: { name: 'Pangaea', reading: 'pan-JEE-uh', meaning: 'the ancient supercontinent' },
        artAlt: 'Two small, slender Triassic dinosaurs walk beside a red-mud pool while a larger crocodile relative rests in the distance.',
      },
      ja: {
        progress: '三畳紀の夜明け',
        eyebrow: '02 · 小さな始まり',
        date: '約2億3000万年前',
        title: '最初の恐竜は、小さな挑戦者。',
        lede: 'はっきり恐竜と分かる初期の仲間は、暑い一つの大陸を走る、すばしこくて小さな動物でした。',
        facts: [
          { value: 'パンゲア', label: '一つの超大陸', caption: 'ほとんどの陸地がつながっていた' },
          { value: '約2億3000万年前', label: '確かな登場', caption: 'よく分かる恐竜の化石が現れる' },
          { value: 'まだ脇役', label: '最初の立場', caption: '大きなワニの親戚も陸を歩いていた' },
        ],
        note: '三畳紀の終わりの大量絶滅で、多くの競争相手が消えました。生き残った恐竜は、そこから多様な姿へ広がります。',
        term: { name: 'Pangaea', reading: 'パンゲア', meaning: '大昔、陸地が一つにつながった超大陸' },
        artAlt: '赤い泥の水辺を二頭の小さく細身な三畳紀の恐竜が歩き、遠くに大きなワニの親戚がいる想像復元画。',
      },
    },
  },
  {
    id: 'quiz-periods',
    kind: 'quiz',
    image: 'assets/images/deep-time-gateway.webp',
    audio: 'quiz-periods',
    tone: 'gateway',
    layout: 'left',
    focal: { x: 53, y: 48 },
    sources: ['ics-chart', 'nhm-when', 'fukui-periods'],
    copy: {
      en: {
        progress: 'Discovery 1',
        eyebrow: 'DISCOVERY 01 · TIME DOORS',
        date: 'oldest → youngest',
        title: 'Set the time doors in order.',
        lede: 'The three period names are our map through the dinosaur story.',
        question: 'Which path runs from oldest to youngest?',
        options: [
          'Triassic → Jurassic → Cretaceous',
          'Jurassic → Cretaceous → Triassic',
          'Cretaceous → Triassic → Jurassic',
        ],
        answer: 0,
        explanation: 'The route begins in the Triassic, crosses the Jurassic and ends in the Cretaceous. Their current rounded boundaries are 252–201, 201–143 and 143–66 million years ago.',
        term: { name: 'Mesozoic', reading: 'mez-oh-ZOH-ik', meaning: 'the era containing all three periods' },
        artAlt: 'A sunrise beyond layered fossil rock suggests a doorway into the three periods of dinosaur history.',
      },
      ja: {
        progress: '発見 1',
        eyebrow: '発見 01 · 時代の扉',
        date: '古い → 新しい',
        title: '時代の扉を順番に並べよう。',
        lede: '三つの時代の名前が、恐竜の物語を進む地図になります。',
        question: '古い時代から新しい時代へ、正しい順番はどれ？',
        options: [
          '三畳紀 → ジュラ紀 → 白亜紀',
          'ジュラ紀 → 白亜紀 → 三畳紀',
          '白亜紀 → 三畳紀 → ジュラ紀',
        ],
        answer: 0,
        explanation: '道は三畳紀から始まり、ジュラ紀を通って、白亜紀で終わります。現在の境界を丸めると、約2億5200万〜2億100万年前、2億100万〜1億4300万年前、1億4300万〜6600万年前です。',
        term: { name: 'Mesozoic', reading: '中生代・ちゅうせいだい', meaning: '三つの時代をまとめた名前' },
        artAlt: '地層の重なる岩の向こうに朝日が差し、恐竜の三つの時代へ続く扉のように見える想像復元画。',
      },
    },
  },
  {
    id: 'jurassic-giants',
    kind: 'story',
    image: 'assets/images/jurassic-giants.webp',
    audio: 'jurassic-giants',
    tone: 'jurassic',
    layout: 'left',
    focal: { x: 61, y: 50 },
    sources: ['ics-chart', 'nhm-when', 'nhm-diplodocus', 'nhm-stegosaurus'],
    copy: {
      en: {
        progress: 'Jurassic giants',
        eyebrow: '03 · A WORLD GROWS TALL',
        date: '201–143 million years ago',
        title: 'Rain, leaves—and very long necks.',
        lede: 'A wetter Jurassic fed wide fern plains and conifer forests. Dinosaurs expanded into spectacular new body plans.',
        facts: [
          { value: '155–145', label: 'million years ago', caption: 'Diplodocus fossil range used here' },
          { value: '152–145', label: 'million years ago', caption: 'Stegosaurus fossil range used here' },
          { value: 'real neighbors', label: 'same region', caption: 'both are found in western North America' },
        ],
        note: 'Stegosaurus plates stood in its skin, but their main job is still debated. Display, recognition and temperature control are all ideas.',
        term: { name: 'sauropod', reading: 'SAWR-uh-pod', meaning: 'a long-necked, four-legged dinosaur' },
        artAlt: 'A huge Diplodocus crosses a rain-fed Jurassic river while a family of Stegosaurus browses nearby.',
      },
      ja: {
        progress: 'ジュラ紀の巨人',
        eyebrow: '03 · 高くなる世界',
        date: '約2億100万〜1億4300万年前',
        title: '雨と葉っぱ、そして長い首。',
        lede: '雨の増えたジュラ紀には、シダの平原と針葉樹の森が広がり、恐竜は驚くほど多様な体へ進化しました。',
        facts: [
          { value: '1億5500万〜1億4500万年前', label: 'ディプロドクス', caption: 'ここで使う化石年代の幅' },
          { value: '1億5200万〜1億4500万年前', label: 'ステゴサウルス', caption: 'ここで使う化石年代の幅' },
          { value: '本当のとなりどうし', label: '同じ地域', caption: 'どちらも北アメリカ西部で見つかる' },
        ],
        note: 'ステゴサウルスの板は皮膚の中に立っていました。でも主な役目はまだ謎。見せる印、仲間の見分け、体温調節などの説があります。',
        term: { name: 'sauropod', reading: '竜脚類・りゅうきゃくるい', meaning: '首が長く、四本足で歩く恐竜の仲間' },
        artAlt: '巨大なディプロドクスが雨上がりのジュラ紀の川を渡り、近くでステゴサウルスの家族が植物を食べる想像復元画。',
      },
    },
  },
  {
    id: 'feathers-before-flight',
    kind: 'story',
    image: 'assets/images/feathers-before-flight.webp',
    audio: 'feathers-before-flight',
    tone: 'feather',
    layout: 'right',
    focal: { x: 39, y: 44 },
    sources: ['nhm-feathers', 'amnh-feathers', 'smithsonian-birds'],
    copy: {
      en: {
        progress: 'Feathered branch',
        eyebrow: '04 · FEATHERS BEFORE FLIGHT',
        date: 'about 150 million years ago',
        title: 'A warm coat became a wing.',
        lede: 'Many dinosaurs wore feathers. At first, feathers may have kept bodies warm, sent signals or helped with camouflage.',
        facts: [
          { value: 'many, not all', label: 'feathered dinosaurs', caption: 'scales also stayed important' },
          { value: 'Archaeopteryx', label: 'a Jurassic mosaic', caption: 'feathers, teeth, claws and a bony tail' },
          { value: 'small theropods', label: 'the bird branch', caption: 'birds evolved inside the dinosaur family' },
        ],
        note: 'Scientists still debate how strongly Archaeopteryx flew. Pterosaurs could fly too, but they belonged to a different reptile branch.',
        term: { name: 'theropod', reading: 'THEER-uh-pod', meaning: 'the mostly two-legged dinosaur group that includes birds' },
        artAlt: 'A long-tailed, clawed Archaeopteryx-like dinosaur spreads its feathered wings above a Jurassic island lagoon.',
      },
      ja: {
        progress: '羽毛の枝',
        eyebrow: '04 · 飛ぶ前の羽毛',
        date: '約1億5000万年前',
        title: 'あたたかい上着が、翼になった。',
        lede: 'たくさんの恐竜が羽毛をまとっていました。最初は保温、合図、隠れる模様に役立ったのかもしれません。',
        facts: [
          { value: '多くの恐竜', label: '羽毛をもつ仲間', caption: 'すべてではなく、うろこも大切だった' },
          { value: 'アーケオプテリクス', label: 'ジュラ紀のモザイク', caption: '羽毛、歯、かぎ爪、骨のある長い尾' },
          { value: '小さな獣脚類', label: '鳥へ続く枝', caption: '鳥は恐竜の家系の中で進化した' },
        ],
        note: 'アーケオプテリクスがどれほど上手に飛べたかは議論中です。翼竜も飛べましたが、恐竜とは別の爬虫類の枝でした。',
        term: { name: 'theropod', reading: '獣脚類・じゅうきゃくるい', meaning: '主に二本足で歩き、鳥もふくむ恐竜の仲間' },
        artAlt: '長い尾と翼のかぎ爪をもつアーケオプテリクスのような恐竜が、ジュラ紀の島の上で羽毛の翼を広げる想像復元画。',
      },
    },
  },
  {
    id: 'cretaceous-spinosaurus',
    kind: 'story',
    image: 'assets/images/cretaceous-spinosaurus.webp',
    audio: 'cretaceous-spinosaurus',
    tone: 'river',
    layout: 'left',
    focal: { x: 63, y: 55 },
    sources: ['ics-chart', 'nhm-when', 'nhm-spinosaurus'],
    copy: {
      en: {
        progress: 'Cretaceous worlds',
        eyebrow: '05 · CONTINENTS DRIFT APART',
        date: '143–66 million years ago',
        title: 'One period, many different stages.',
        lede: 'Continents separated farther. Shallow seas, new coastlines and increasingly common flowering plants made different worlds.',
        facts: [
          { value: '77 million', label: 'years long', caption: 'the longest Mesozoic period' },
          { value: '99–93.5', label: 'million years ago', caption: 'Spinosaurus in North Africa' },
          { value: 'fish eater', label: 'a narrow snout', caption: 'cone-shaped teeth helped grip slippery prey' },
        ],
        note: 'Spinosaurus had short legs and a paddle-like tail, but how much it swam—and exactly how it moved on land—remain active questions.',
        term: { name: 'Spinosaurus', reading: 'SPINE-oh-SORE-us', meaning: '“spine lizard,” named for its tall sail bones' },
        artAlt: 'A sail-backed Spinosaurus wades at the edge of a broad Cretaceous North African river under storm-lit clouds.',
      },
      ja: {
        progress: '白亜紀の世界',
        eyebrow: '05 · 分かれていく大陸',
        date: '約1億4300万〜6600万年前',
        title: '一つの時代に、いくつもの舞台。',
        lede: '大陸はさらに離れ、浅い海と新しい海岸が生まれました。花を咲かせる植物も、しだいに身近になります。',
        facts: [
          { value: '約7700万年', label: '続いた長さ', caption: '中生代でいちばん長い時代' },
          { value: '約9900万〜9350万年前', label: 'スピノサウルス', caption: '北アフリカで暮らした' },
          { value: '魚を食べた', label: '細長い口', caption: '円すい形の歯で滑る獲物をつかんだ' },
        ],
        note: 'スピノサウルスは短い脚と、へらのような尾をもちました。でも、どれほど泳いだのか、陸でどう動いたのかは今も研究中です。',
        term: { name: 'Spinosaurus', reading: 'スピノサウルス', meaning: '「とげのあるトカゲ」。背中の高い骨からついた名' },
        artAlt: '帆のあるスピノサウルスが、嵐の光を受けた白亜紀の北アフリカの大河の岸辺を歩く想像復元画。',
      },
    },
  },
  {
    id: 'gobi-velociraptor',
    kind: 'story',
    image: 'assets/images/gobi-velociraptor.webp',
    audio: 'gobi-velociraptor',
    tone: 'gobi',
    layout: 'right',
    focal: { x: 48, y: 53 },
    sources: ['nhm-velociraptor', 'amnh-eggs'],
    copy: {
      en: {
        progress: 'Gobi lives',
        eyebrow: '06 · FEATHERS IN THE DESERT',
        date: '74–70 million years ago',
        title: 'The famous raptor was turkey-sized.',
        lede: 'Real Velociraptor lived in Mongolia. It was far smaller and more feathered than its movie-sized cousin.',
        facts: [
          { value: '1.8 m', label: 'nose to tail', caption: 'much of that length was a stiff tail' },
          { value: '~7 kg', label: 'estimated mass', caption: 'around a large turkey’s weight' },
          { value: 'eggs', label: 'every dinosaur', caption: 'all dinosaurs known to us hatched from eggs' },
        ],
        note: 'Nests, eggs and embryos can reveal growth and possible care. They are rare snapshots, so scientists separate evidence from a good guess.',
        term: { name: 'Velociraptor', reading: 'veh-LOSS-ih-RAP-tor', meaning: '“quick plunderer”' },
        artAlt: 'A small feathered Velociraptor walks beside a Gobi stream while two Protoceratops guard a nest of eggs.',
      },
      ja: {
        progress: 'ゴビの暮らし',
        eyebrow: '06 · 砂漠の羽毛',
        date: '約7400万〜7000万年前',
        title: '有名なラプトルは、七キロほど。',
        lede: '本当のヴェロキラプトルはモンゴルで暮らし、映画の姿よりずっと小さく、羽毛に包まれていました。',
        facts: [
          { value: '1.8メートル', label: '頭から尾まで', caption: '長さの多くは、まっすぐな尾' },
          { value: '約7キログラム', label: '推定体重', caption: '大きな七面鳥ほど' },
          { value: '卵', label: 'すべての恐竜', caption: '知られている恐竜はみんな卵から生まれた' },
        ],
        note: '巣、卵、赤ちゃんの化石は、成長や子育ての可能性を教えます。ただし貴重な一場面なので、証拠と推測を分けて考えます。',
        term: { name: 'Velociraptor', reading: 'ヴェロキラプトル', meaning: '「すばやい略奪者」という意味' },
        artAlt: '小さく羽毛のあるヴェロキラプトルがゴビ砂漠の水辺を歩き、二頭のプロトケラトプスが卵の巣を守る想像復元画。',
      },
    },
  },
  {
    id: 'last-neighbors',
    kind: 'story',
    image: 'assets/images/last-neighbors.webp',
    audio: 'last-neighbors',
    tone: 'hell-creek',
    layout: 'left',
    focal: { x: 53, y: 52 },
    sources: ['nhm-tyrannosaurus', 'nhm-triceratops', 'nhm-stegosaurus', 'nhm-velociraptor', 'smithsonian-last'],
    copy: {
      en: {
        progress: 'Last neighbors',
        eyebrow: '07 · THE FINAL TWO MILLION YEARS',
        date: '68–66 million years ago',
        title: 'T. rex and Triceratops really met.',
        lede: 'Their fossils overlap in time and place: both lived in western North America near the Cretaceous ending.',
        facts: [
          { value: '68–66', label: 'million years ago', caption: 'T. rex and Triceratops overlap' },
          { value: '77+ million', label: 'years too early', caption: 'Stegosaurus vanished long before T. rex' },
          { value: 'another continent', label: 'Velociraptor', caption: 'its known range was earlier, in Mongolia' },
        ],
        note: 'Amazing fact: T. rex lived closer in time to us than to Stegosaurus. Dinosaur history is much longer than the time since T. rex.',
        term: { name: 'fossil range', reading: 'FOSS-ul range', meaning: 'the span between currently known fossils' },
        artAlt: 'A mostly scaled Tyrannosaurus and a Triceratops with its juvenile watch one another across a misty Cretaceous river.',
      },
      ja: {
        progress: '最後のとなりどうし',
        eyebrow: '07 · 最後の200万年',
        date: '約6800万〜6600万年前',
        title: 'ティラノとトリケラは、本当に出会った。',
        lede: '二頭の化石は時代も場所も重なります。白亜紀の終わり近く、北アメリカ西部で暮らしていました。',
        facts: [
          { value: '約6800万〜6600万年前', label: '重なる時代', caption: 'ティラノサウルスとトリケラトプス' },
          { value: '7700万年以上前', label: '早すぎた相手', caption: 'ステゴサウルスはずっと先に姿を消した' },
          { value: '別の大陸', label: 'ヴェロキラプトル', caption: 'より古い時代のモンゴルで見つかる' },
        ],
        note: 'びっくり事実。ティラノサウルスから私たちまでの時間は、ティラノサウルスからステゴサウルスまでより短いのです。',
        term: { name: 'fossil range', reading: '化石年代の幅', meaning: '現在知られている最古と最新の化石のあいだ' },
        artAlt: 'うろこにおおわれたティラノサウルスと、子どもを連れたトリケラトプスが、霧の白亜紀の川をはさんで互いを見る想像復元画。',
      },
    },
  },
  {
    id: 'quiz-neighbors',
    kind: 'quiz',
    image: 'assets/images/last-neighbors.webp',
    audio: 'quiz-neighbors',
    tone: 'hell-creek',
    layout: 'left',
    focal: { x: 53, y: 52 },
    sources: ['nhm-tyrannosaurus', 'nhm-triceratops', 'nhm-stegosaurus', 'nhm-velociraptor'],
    copy: {
      en: {
        progress: 'Discovery 2',
        eyebrow: 'DISCOVERY 02 · WHO COULD MEET?',
        date: 'time + place',
        title: 'Choose the real neighbors.',
        lede: 'A meeting needs more than two famous names. Their fossil ranges and regions must overlap.',
        question: 'Which pair lived at the same time and in the same region?',
        options: [
          'Stegosaurus + Tyrannosaurus rex',
          'Velociraptor + Tyrannosaurus rex',
          'Tyrannosaurus rex + Triceratops',
        ],
        answer: 2,
        explanation: 'Tyrannosaurus rex and Triceratops both lived in western North America about 68–66 million years ago. Stegosaurus was at least 77 million years earlier; Velociraptor’s known fossils are earlier and in Mongolia.',
        term: { name: 'contemporary', reading: 'kun-TEM-puh-rair-ee', meaning: 'living during the same time' },
        artAlt: 'Tyrannosaurus and Triceratops stand on opposite banks of the same late-Cretaceous river.',
      },
      ja: {
        progress: '発見 2',
        eyebrow: '発見 02 · だれと出会えた？',
        date: '時代 ＋ 場所',
        title: '本当のとなりどうしを選ぼう。',
        lede: '有名な二頭でも、時代と地域が重ならなければ出会えません。',
        question: '同じ時代、同じ地域で出会った可能性がある二頭は？',
        options: [
          'ステゴサウルス ＋ ティラノサウルス・レックス',
          'ヴェロキラプトル ＋ ティラノサウルス・レックス',
          'ティラノサウルス・レックス ＋ トリケラトプス',
        ],
        answer: 2,
        explanation: 'ティラノサウルス・レックスとトリケラトプスは、どちらも約6800万〜6600万年前の北アメリカ西部で暮らしました。ステゴサウルスは少なくとも7700万年以上前、ヴェロキラプトルの化石はより古いモンゴルのものです。',
        term: { name: 'contemporary', reading: '同時代・どうじだい', meaning: '同じ時代に生きていること' },
        artAlt: '白亜紀末の同じ川の両岸に、ティラノサウルスとトリケラトプスが立つ想像復元画。',
      },
    },
  },
  {
    id: 'fossil-detectives',
    kind: 'story',
    image: 'assets/images/fossil-detectives.webp',
    audio: 'fossil-detectives',
    tone: 'evidence',
    layout: 'right',
    focal: { x: 45, y: 55 },
    sources: ['nhm-evidence', 'nhm-tracks'],
    copy: {
      en: {
        progress: 'Clues in stone',
        eyebrow: '08 · THE EVIDENCE LAB',
        date: 'the investigation continues',
        title: 'A dinosaur picture is a tested idea.',
        lede: 'Paleontologists combine bones, tracks, eggs, rock layers and living animals. Each clue answers some questions—not all of them.',
        facts: [
          { value: 'body fossils', label: 'bones and teeth', caption: 'clues to anatomy, age and food' },
          { value: 'trace fossils', label: 'tracks, nests, poo', caption: 'clues left by activity' },
          { value: 'rare details', label: 'skin and feathers', caption: 'soft tissues need special conditions' },
        ],
        note: 'Most dinosaur colors and sounds are unknown. A few exceptional fossils preserve pigment clues, so some reconstructions are more certain than others.',
        term: { name: 'trace fossil', reading: 'trace FOSS-ul', meaning: 'evidence of activity, such as a footprint' },
        artAlt: 'A diverse field team carefully brushes a fossil skeleton and measures a nearby trail of three-toed footprints.',
      },
      ja: {
        progress: '石の手がかり',
        eyebrow: '08 · 証拠の研究室',
        date: '調査は今も続く',
        title: '恐竜の絵は、確かめ続ける考え。',
        lede: '古生物学者は、骨、足あと、卵、地層、今の動物を組み合わせます。一つの証拠だけですべては分かりません。',
        facts: [
          { value: '体化石', label: '骨と歯', caption: '体のつくり、年齢、食べ物の手がかり' },
          { value: '生痕化石', label: '足あと、巣、ふん', caption: '生きていたときの活動の手がかり' },
          { value: '珍しい細部', label: '皮膚と羽毛', caption: 'やわらかい物は特別な条件で残る' },
        ],
        note: 'ほとんどの恐竜は、色も鳴き声も分かりません。ごく珍しい化石には色素の手がかりが残り、確かさは復元ごとに違います。',
        term: { name: 'trace fossil', reading: '生痕化石・せいこんかせき', meaning: '足あとなど、生き物の活動が残った証拠' },
        artAlt: 'さまざまな古生物学者が化石の骨格を丁寧に刷毛で出し、近くの三本指の足あとを測る場面。',
      },
    },
  },
  {
    id: 'quiz-tracks',
    kind: 'quiz',
    image: 'assets/images/fossil-detectives.webp',
    audio: 'quiz-tracks',
    tone: 'evidence',
    layout: 'right',
    focal: { x: 45, y: 55 },
    sources: ['nhm-tracks', 'nhm-evidence'],
    copy: {
      en: {
        progress: 'Discovery 3',
        eyebrow: 'DISCOVERY 03 · FOSSIL DETECTIVE',
        date: 'read the clues',
        title: 'Which clue records a walk?',
        lede: 'A body fossil and a trace fossil tell different parts of the same story.',
        question: 'Which clue most directly records a dinosaur moving across the ground?',
        options: [
          'A tooth',
          'A trail of footprints',
          'A skull',
        ],
        answer: 1,
        explanation: 'A trackway is movement preserved in stone. The spacing and direction of its prints can reveal stride, speed clues and whether an animal used two legs or four. Teeth and skulls tell us more directly about the body and diet.',
        term: { name: 'trackway', reading: 'TRAK-way', meaning: 'a series of footprints from one moving animal' },
        artAlt: 'Scientists work beside a partly exposed skeleton and a preserved line of dinosaur footprints.',
      },
      ja: {
        progress: '発見 3',
        eyebrow: '発見 03 · 化石探偵',
        date: '手がかりを読もう',
        title: '歩いた記録は、どの証拠？',
        lede: '体の化石と活動の化石は、同じ物語の別の部分を教えます。',
        question: '恐竜が地面を動いたことを、いちばん直接に記録する手がかりは？',
        options: [
          '一本の歯',
          '続いている足あと',
          '頭の骨',
        ],
        answer: 1,
        explanation: '足あとが続く道は、動きが石に残った記録です。間隔と向きから歩幅、速さの手がかり、二本足か四本足かを調べられます。歯や頭骨は、体や食べ物をより直接に教えます。',
        term: { name: 'trackway', reading: '足跡列・そくせきれつ', meaning: '一頭の動物が動いて残した、続く足あと' },
        artAlt: '発掘途中の骨格と、石に残った恐竜の足あとが続くそばで、研究者が作業する場面。',
      },
    },
  },
  {
    id: 'chicxulub-impact',
    kind: 'story',
    image: 'assets/images/chicxulub-impact.webp',
    audio: 'chicxulub-impact',
    tone: 'impact',
    layout: 'left',
    focal: { x: 63, y: 47 },
    sources: ['ics-chart', 'nhm-extinction', 'nasa-chicxulub', 'smithsonian-birds'],
    copy: {
      en: {
        progress: 'The great turning',
        eyebrow: '09 · THE SKY CHANGES',
        date: '66 million years ago',
        title: 'An ending that did not happen at once.',
        lede: 'A huge asteroid struck near today’s Yucatán Peninsula. The impact changed climate and food webs around the planet.',
        facts: [
          { value: '~14 km', label: 'impact object', caption: 'an estimate from the evidence' },
          { value: '~180 km', label: 'hidden crater', caption: 'the Chicxulub structure' },
          { value: '~75%', label: 'species lost', caption: 'across land and sea' },
        ],
        note: 'Dust and debris reduced sunlight, plants struggled and food webs collapsed. Non-bird dinosaurs disappeared—but some early birds survived.',
        term: { name: 'Chicxulub', reading: 'CHEEK-shuh-loob', meaning: 'the impact site near Mexico’s Yucatán Peninsula' },
        artAlt: 'A distant white-gold impact plume rises beyond a dark Cretaceous wetland as animal silhouettes move along the shore.',
      },
      ja: {
        progress: '大きな転換',
        eyebrow: '09 · 空が変わる',
        date: '6600万年前',
        title: '終わりは、一瞬だけではなかった。',
        lede: '巨大な小惑星が、今のユカタン半島近くに衝突しました。その後、地球じゅうの気候と食物網が変わります。',
        facts: [
          { value: '約14キロメートル', label: '衝突した天体', caption: '証拠から考えた大きさ' },
          { value: '約180キロメートル', label: '隠れたクレーター', caption: 'チクシュルーブ衝突跡' },
          { value: '約75パーセント', label: '失われた生物種', caption: '陸でも海でも大きな変化' },
        ],
        note: 'ちりが日光を弱め、植物が育ちにくくなり、食べ物のつながりが崩れました。鳥類以外の恐竜は消えましたが、一部の初期の鳥は生き残りました。',
        term: { name: 'Chicxulub', reading: 'チクシュルーブ', meaning: 'メキシコのユカタン半島近くにある衝突地点' },
        artAlt: '暗い白亜紀の湿地の向こうに白金色の巨大な衝突噴煙が立ち、岸辺を動物の影が移動する想像復元画。',
      },
    },
  },
  {
    id: 'birds-continue',
    kind: 'finale',
    image: 'assets/images/birds-continue.webp',
    audio: 'birds-continue',
    tone: 'today',
    layout: 'right',
    focal: { x: 39, y: 42 },
    sources: ['nhm-feathers', 'smithsonian-birds'],
    copy: {
      en: {
        progress: 'The story flies on',
        eyebrow: 'FINALE · LISTEN OUTSIDE',
        date: '66 million years later',
        title: 'The dinosaurs never completely left.',
        lede: 'The small feathered branch survived, changed and filled the skies. Every living bird is part of Dinosauria.',
        facts: [
          { value: 'time', label: 'the big lesson', caption: 'famous dinosaurs belonged to different worlds' },
          { value: 'clues', label: 'the science', caption: 'every reconstruction can change with evidence' },
          { value: 'birds', label: 'the living branch', caption: 'dinosaurs are still around us' },
        ],
        note: 'Next time you hear a chirp or watch a pigeon walk, notice the two-legged stance, scaly feet and feathers. Deep time is answering back.',
        term: { name: 'avian dinosaur', reading: 'AY-vee-un dinosaur', meaning: 'a bird—the dinosaur branch alive today' },
        artAlt: 'A modern black bird opens its wings above a green sandstone canyon in warm sunrise light.',
      },
      ja: {
        progress: '今も飛ぶ物語',
        eyebrow: 'フィナーレ · 外の声を聞こう',
        date: 'それから6600万年',
        title: '恐竜は、完全にはいなくならなかった。',
        lede: '小さく羽毛のある枝が生き残り、変化し、空へ広がりました。今の鳥はすべて恐竜の仲間です。',
        facts: [
          { value: '時間', label: '大きな学び', caption: '有名な恐竜は別々の世界で暮らした' },
          { value: '手がかり', label: '科学の力', caption: '復元は新しい証拠で変わり続ける' },
          { value: '鳥', label: '生きている枝', caption: '恐竜は今も私たちのそばにいる' },
        ],
        note: '次に鳥の声を聞いたら、二本足の立ち方、うろこのある足、羽毛を見てみよう。深い時間から返事が聞こえます。',
        term: { name: 'avian dinosaur', reading: '鳥類型恐竜・ちょうるいがたきょうりゅう', meaning: '今も生きている恐竜の枝、つまり鳥' },
        artAlt: '現代の黒い鳥が、朝日に照らされた緑豊かな砂岩の谷で翼を広げる場面。',
      },
    },
  },
];

window.DINO_HISTORY = {
  defaultLanguage: 'en',
  supportedLanguages: ['en', 'ja'],
  ui: DINO_UI,
  scenes: DINO_SCENES,
  sources: DINO_SOURCES,
};
