'use strict';

(function exposeCharacters(root) {
  const characters = {
    narrator: {
      id: 'narrator',
      name: 'Narrator',
      pronouns: 'she/her voice',
      role: 'Storyteller',
      portrait: null,
      voice: 'en_US-amy-medium',
      accent: '#ffc247',
      sprite: null,
      expressions: ['measured', 'tender', 'grave', 'hopeful'],
    },
    aren: {
      id: 'aren',
      name: 'Aren Vale',
      shortName: 'Aren',
      pronouns: 'he/him',
      role: 'Willowmere villager',
      age: 19,
      portrait: 'assets/images/portraits/aren.webp',
      portraitAlt: 'Aren, a freckled young man with chestnut hair, a moss-green jacket, and a rust-orange scarf.',
      voice: 'en_US-lessac-medium',
      accent: '#ffc247',
      sprite: {
        skin: '#a96f4f',
        hair: '#5b321f',
        body: '#52613b',
        detail: '#b94f25',
        boots: '#4a3127',
        shape: 'scarf',
      },
      expressions: ['neutral', 'relieved', 'worried', 'determined', 'surprised', 'hurt', 'angry'],
    },
    bram: {
      id: 'bram',
      name: 'Bram Alder',
      shortName: 'Bram',
      pronouns: 'he/him',
      role: 'Woodcutter and former militia fighter',
      age: 45,
      portrait: 'assets/images/portraits/bram.webp',
      portraitAlt: 'Bram, a broad middle-aged woodcutter with graying dark hair, a brick-red shirt, and a forest-green vest.',
      voice: null,
      accent: '#d68755',
      sprite: {
        skin: '#8b5c43',
        hair: '#29251f',
        body: '#7e3d2e',
        detail: '#394b37',
        boots: '#3d3028',
        shape: 'broad',
      },
      expressions: ['guarded', 'rueful', 'worried', 'protective', 'grieving', 'angry'],
    },
    cael: {
      id: 'cael',
      name: 'Sir Cael Varin',
      shortName: 'Cael',
      pronouns: 'he/him',
      role: 'Knight of Veyra',
      age: 37,
      portrait: 'assets/images/portraits/cael.webp',
      portraitAlt: 'Cael, a pale-eyed knight with black half-tied hair, deep-teal layers, one silver shoulder guard, and a pale cloak.',
      voice: null,
      accent: '#6fe5ef',
      sprite: {
        skin: '#8c745e',
        hair: '#111820',
        body: '#163f47',
        detail: '#a8b7bc',
        boots: '#22272d',
        shape: 'cloak',
      },
      expressions: ['guarded', 'pained', 'skeptical', 'determined', 'guilty', 'relieved'],
    },
    mira: {
      id: 'mira',
      name: 'Mira Fen',
      shortName: 'Mira',
      pronouns: 'she/her',
      role: 'Healer and evacuation leader',
      age: 23,
      portrait: 'assets/images/portraits/mira.webp',
      portraitAlt: 'Mira, a young healer with dark-auburn curls, brass hair pins, a cream blouse, and a jade apron-coat.',
      voice: null,
      accent: '#17c696',
      sprite: {
        skin: '#b27b55',
        hair: '#6c2d23',
        body: '#285844',
        detail: '#d9d0bd',
        boots: '#46362d',
        shape: 'apron',
      },
      expressions: ['focused', 'warm', 'worried', 'determined', 'surprised', 'irritated'],
    },
    mara: {
      id: 'mara',
      name: 'Mara “Cinder” Vell',
      shortName: 'Mara',
      pronouns: 'she/her',
      role: 'Inventor of the Starling',
      age: 39,
      portrait: 'assets/images/portraits/mara.webp',
      portraitAlt: 'Mara, a dark-skinned airship engineer with asymmetrical silver hair, amber goggles, and an Ember-orange shirt.',
      voice: null,
      accent: '#ff6a1f',
      sprite: {
        skin: '#684334',
        hair: '#a9a9ad',
        body: '#252b31',
        detail: '#d85521',
        boots: '#302922',
        shape: 'goggles',
      },
      expressions: ['appraising', 'grinning', 'calculating', 'determined', 'surprised', 'angry'],
    },
    edric: {
      id: 'edric',
      name: 'King Edric Aurel',
      shortName: 'Edric',
      pronouns: 'he/him',
      role: 'King of Asterra',
      age: 52,
      portrait: 'assets/images/portraits/edric.webp',
      portraitAlt: 'King Edric, an exhausted bearded ruler with swept silver-streaked hair, a narrow circlet, dark coat, and wine-red sash.',
      voice: null,
      accent: '#ff6a1f',
      sprite: {
        skin: '#9a7b63',
        hair: '#50483f',
        body: '#22242a',
        detail: '#6e2738',
        boots: '#15171a',
        shape: 'cape',
      },
      expressions: ['controlled', 'tender', 'suspicious', 'commanding', 'furious', 'defeated'],
    },
    elara: {
      id: 'elara',
      name: 'Queen Elara Aurel',
      shortName: 'Elara',
      pronouns: 'she/her',
      role: 'Queen and natural philosopher',
      age: 50,
      portrait: 'assets/images/portraits/elara.webp',
      portraitAlt: 'Queen Elara, a composed woman with green eyes, a braided brown-and-silver coil, a moonflower pin, and a sage-gray gown.',
      voice: null,
      accent: '#b8c9a2',
      sprite: {
        skin: '#b89578',
        hair: '#92775b',
        body: '#869181',
        detail: '#c0a65a',
        boots: '#44484b',
        shape: 'gown',
      },
      expressions: ['calm', 'fatigued', 'worried', 'firm', 'relieved'],
    },
    lucen: {
      id: 'lucen',
      name: 'Prince Lucen Aurel',
      shortName: 'Lucen',
      pronouns: 'he/him',
      role: 'Crown prince',
      age: 26,
      portrait: 'assets/images/portraits/lucen.webp',
      portraitAlt: 'Prince Lucen, a young man with jaw-length dark hair, one silver temple streak, a navy vest, and an Ember shoulder cord.',
      voice: null,
      accent: '#8ab4d7',
      sprite: {
        skin: '#a58269',
        hair: '#2e2825',
        body: '#182d47',
        detail: '#cf5924',
        boots: '#292b31',
        shape: 'cord',
      },
      expressions: ['diplomatic', 'relieved', 'worried', 'resolved', 'surprised', 'grieving'],
    },
    rowan: {
      id: 'rowan',
      name: 'Rowan',
      shortName: 'Rowan',
      pronouns: 'she/her',
      role: 'Keeper of Rowanstead Farm',
      age: 68,
      portrait: null,
      voice: null,
      accent: '#9aa3b2',
      sprite: {
        skin: '#a98268',
        hair: '#d2d2ce',
        body: '#39436b',
        detail: '#ffc247',
        boots: '#41342c',
        shape: 'lantern',
      },
      expressions: ['steady'],
    },
    holt: {
      id: 'holt',
      name: 'Commander Holt',
      shortName: 'Holt',
      pronouns: 'he/him',
      role: 'Royal field commander',
      age: 38,
      portrait: null,
      voice: null,
      accent: '#ff6a1f',
      sprite: {
        skin: '#8d6952',
        hair: '#3a342e',
        body: '#292d35',
        detail: '#d95726',
        boots: '#17191d',
        shape: 'helmet',
      },
      expressions: ['disciplined'],
    },
    system: {
      id: 'system',
      name: 'Story',
      pronouns: '',
      role: 'Interface',
      portrait: null,
      voice: null,
      accent: '#ffc247',
      sprite: null,
      expressions: [],
    },
  };

  root.GAME_CHARACTERS = Object.freeze(characters);
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = root.GAME_CHARACTERS;
  }
}(typeof window !== 'undefined' ? window : globalThis));

