'use strict';

(function exposeMaps(root) {
  const TILE_SIZE = 48;
  const LEGEND = Object.freeze({
    '#': { name: 'cliff or boundary', solid: true },
    'T': { name: 'tree', solid: true },
    'H': { name: 'building', solid: true },
    '~': { name: 'deep water', solid: true },
    'L': { name: 'lava', solid: true },
    'I': { name: 'ice cliff', solid: true },
    'C': { name: 'crystal plinth', solid: true },
    'O': { name: 'large object', solid: true },
    '.': { name: 'natural ground', solid: false },
    ':': { name: 'path', solid: false },
    '=': { name: 'bridge or walkway', solid: false },
    'r': { name: 'rubble', solid: false },
    'V': { name: 'steam vent', solid: false },
    's': { name: 'snow', solid: false },
    'f': { name: 'interior floor', solid: false },
    '*': { name: 'small story detail', solid: false },
  });

  const maps = {
    birchwood: {
      id: 'birchwood',
      name: 'Birchwood',
      subtitle: 'Above Willowmere · Late afternoon',
      chapter: 'I · An ordinary day',
      ambience: 'Leaves, distant water, and the last quiet hour.',
      palette: {
        ground: '#273c32',
        groundAlt: '#30483a',
        path: '#665441',
        wall: '#17221e',
        water: '#163c49',
        detail: '#d5b866',
        haze: '#90a993',
      },
      tiles: [
        '########################',
        '#....TTT......TTT......#',
        '#....T..............O..#',
        '#...*T..:::::::........#',
        '#......::.....::..TT...#',
        '#...T.::..*...::..T....#',
        '#...T.::......::.......#',
        '#.....::..TT..::::::...#',
        '#..TT.::.......*..::...#',
        '#.....:::::.......::...#',
        '#..TT.....:::::::......#',
        '#...T............TT....#',
        '#..........::::........#',
        '########################',
      ],
      spawns: [
        { id: 'grove', x: 7.5, y: 9.5, facing: 'up' },
        { id: 'ridge_retry', x: 11.5, y: 11.4, facing: 'down' },
      ],
      npcs: [],
      interactions: [
        {
          id: 'mushroom_coppercap',
          type: 'object',
          x: 4,
          y: 3,
          label: 'Pick the coppercaps',
          sceneId: 'mushroom_coppercap',
        },
        {
          id: 'mushroom_moonbell',
          type: 'object',
          x: 10,
          y: 5,
          label: 'Pick the moonbells',
          sceneId: 'mushroom_moonbell',
        },
        {
          id: 'mushroom_foxear',
          type: 'object',
          x: 17,
          y: 8,
          label: 'Pick the fox-ears',
          sceneId: 'mushroom_foxear',
        },
        {
          id: 'weathered_gate_stone',
          type: 'object',
          x: 19,
          y: 2,
          label: 'Inspect the weathered stone',
          sceneId: 'inspect_gate_stone',
          repeatSceneId: 'inspect_gate_stone_repeat',
        },
        {
          id: 'ridge_trail',
          type: 'exit',
          x: 11,
          y: 12,
          label: 'Follow the trail home',
          sceneId: 'ridge_smoke',
          requires: { counter: 'mushroomsGathered', gte: 3 },
          lockedMessage: 'Aren still needs three kinds of mushrooms for supper.',
        },
      ],
      triggers: [],
    },

    willowmere: {
      id: 'willowmere',
      name: 'Willowmere & Rowanstead',
      subtitle: 'The eastern finger · Nightfall',
      chapter: 'I · What the fire left',
      ambience: 'Wet ash, lantern smoke, and people refusing to disappear.',
      palette: {
        ground: '#312f2c',
        groundAlt: '#3b3732',
        path: '#605247',
        wall: '#211d1c',
        water: '#203b43',
        detail: '#d28a45',
        haze: '#7d7670',
      },
      tiles: [
        '########################',
        '#HHH..r....::::....HHHH#',
        '#HHH..rr...:..:....H..H#',
        '#.....rr...:..:....H..H#',
        '#..rrr.....:..:::::H..H#',
        '#..rHH.....:......:HHHH#',
        '#..rHH..*..::::...:....#',
        '#..r....r.....:...:....#',
        '#....*..r.....:::::....#',
        '#..HHH..r.........:....#',
        '#..HHH..::::::....:....#',
        '#.............:::::....#',
        '#......................#',
        '########################',
      ],
      spawns: [
        { id: 'ruins_entry', x: 4.5, y: 11.5, facing: 'up' },
        { id: 'farm_retry', x: 15.5, y: 7.5, facing: 'right' },
      ],
      npcs: [
        {
          id: 'bram_willowmere',
          characterId: 'bram',
          x: 5,
          y: 8,
          label: 'Speak with Bram',
          sceneId: 'meet_bram',
          repeatSceneId: 'bram_after_meeting',
          when: { not: { flag: 'bramJoined', equals: true } },
        },
        {
          id: 'bram_willowmere_after',
          characterId: 'bram',
          x: 7,
          y: 9,
          label: 'Speak with Bram',
          sceneId: 'bram_after_meeting',
          when: { flag: 'bramJoined', equals: true },
        },
        {
          id: 'rowan_farm',
          characterId: 'rowan',
          x: 18,
          y: 4,
          label: 'Enter Rowanstead Farm',
          sceneId: 'rowanstead_cael',
          repeatSceneId: 'rowanstead_repeat',
          requires: { flag: 'bramJoined', equals: true },
          lockedMessage: 'The road can wait. Someone is calling from the ruined well.',
        },
      ],
      interactions: [
        {
          id: 'willowmere_memorial',
          type: 'object',
          x: 8,
          y: 6,
          label: 'Tie a ribbon at the memorial',
          sceneId: 'willowmere_memorial',
          repeatSceneId: 'willowmere_memorial_repeat',
        },
        {
          id: 'royal_shield',
          type: 'object',
          x: 8,
          y: 8,
          label: 'Inspect the abandoned shield',
          sceneId: 'inspect_royal_shield',
          repeatSceneId: 'inspect_royal_shield_repeat',
        },
      ],
      triggers: [],
    },

    greenwake: {
      id: 'greenwake',
      name: 'Greenwake',
      subtitle: 'The reed finger · Morning',
      chapter: 'II · Whom can you reach?',
      ambience: 'Waterwheels, reed bells, and a village holding its breath.',
      palette: {
        ground: '#294338',
        groundAlt: '#345243',
        path: '#7b684c',
        wall: '#1e2d27',
        water: '#1b5260',
        detail: '#e0b95d',
        haze: '#8db7a3',
      },
      tiles: [
        '########################',
        '#HHH...::.....HHH......#',
        '#H.H...::.....H.H..TT..#',
        '#HHH...::.....HHH..TT..#',
        '#......::..............#',
        '#~~~~~~==~~~~~~~~~~~~~~#',
        '#~~~~~~==~~~~~~~~~~~~~~#',
        '#......::......O.......#',
        '#..HH..::::::..:::.....#',
        '#..HH.......:..:HHH....#',
        '#.....TT....::::H.H....#',
        '#.....TT........HHH....#',
        '#......................#',
        '########################',
      ],
      spawns: [
        { id: 'west_bridge', x: 6.5, y: 4.5, facing: 'down' },
        { id: 'late_arrival', x: 5.5, y: 11.5, facing: 'up' },
      ],
      npcs: [
        {
          id: 'mira_greenwake_first',
          characterId: 'mira',
          x: 10,
          y: 8,
          label: 'Warn Mira',
          sceneId: 'warn_greenwake',
          repeatSceneId: 'mira_greenwake_repeat',
          when: {
            all: [
              { flag: 'firstFinger', equals: 'greenwake' },
              { not: { flag: 'greenwakeResolved', equals: true } },
            ],
          },
        },
        {
          id: 'mira_greenwake_late',
          characterId: 'mira',
          x: 10,
          y: 8,
          label: 'Speak with Mira',
          sceneId: 'greenwake_late',
          repeatSceneId: 'greenwake_late_repeat',
          when: {
            all: [
              { flag: 'firstFinger', equals: 'ashfinger' },
              { not: { flag: 'greenwakeResolved', equals: true } },
            ],
          },
        },
      ],
      interactions: [
        {
          id: 'greenwake_sluice',
          type: 'object',
          x: 14,
          y: 7,
          label: 'Inspect the old sluice controls',
          sceneId: 'inspect_sluice',
          repeatSceneId: 'inspect_sluice_repeat',
        },
        {
          id: 'reed_bells',
          type: 'object',
          x: 20,
          y: 2,
          label: 'Listen to the reed bells',
          sceneId: 'inspect_reed_bells',
          repeatSceneId: 'inspect_reed_bells_repeat',
        },
      ],
      triggers: [],
    },

    ashfinger: {
      id: 'ashfinger',
      name: 'Ashfinger',
      subtitle: 'The mill finger · Rain',
      chapter: 'II · Under the royal banner',
      ambience: 'Floodwater, bells, and a battle nobody here chose.',
      palette: {
        ground: '#323b3b',
        groundAlt: '#3c4543',
        path: '#62594d',
        wall: '#222829',
        water: '#204854',
        detail: '#d6a84a',
        haze: '#75868a',
      },
      tiles: [
        '########################',
        '#HHH..::.....HHH.......#',
        '#H.H..::.....H.H..###..#',
        '#HHH..::.....HHH..#C#..#',
        '#.....::..........###..#',
        '#~~~~~==~~~~~~~~~~~~~~~#',
        '#~~~~~==~~~~~~~~~~~~~~~#',
        '#.....::..rrrr.........#',
        '#..HH.::::rrr..:::HHH..#',
        '#..HH.....rr...:..H.H..#',
        '#.....O...::::::..HHH..#',
        '#.........:............#',
        '#.........::::::::.....#',
        '########################',
      ],
      spawns: [
        { id: 'south_lane', x: 10.5, y: 11.5, facing: 'up' },
        { id: 'late_lane', x: 4.5, y: 10.5, facing: 'right' },
      ],
      npcs: [
        {
          id: 'mira_ashfinger',
          characterId: 'mira',
          x: 12,
          y: 8,
          label: 'Help Mira reach the bell',
          sceneId: 'ashfinger_encounter',
          when: {
            all: [
              { flag: 'firstFinger', equals: 'ashfinger' },
              { not: { flag: 'ashfingerResolved', equals: true } },
            ],
          },
        },
      ],
      interactions: [
        {
          id: 'ashfinger_sluice',
          type: 'object',
          x: 6,
          y: 5,
          label: 'Study the flood sluice',
          sceneId: 'inspect_ash_sluice',
          repeatSceneId: 'inspect_sluice_repeat',
          when: { not: { flag: 'ashfingerResolved', equals: true } },
        },
        {
          id: 'cracked_army_order',
          type: 'object',
          x: 9,
          y: 10,
          label: 'Inspect the mud-soaked army order',
          sceneId: 'inspect_army_order',
          repeatSceneId: 'inspect_army_order_repeat',
        },
        {
          id: 'ashfinger_late_site',
          type: 'object',
          x: 20,
          y: 4,
          label: 'Approach the silent crystal site',
          sceneId: 'ashfinger_late',
          when: {
            all: [
              { flag: 'firstFinger', equals: 'greenwake' },
              { not: { flag: 'ashfingerResolved', equals: true } },
            ],
          },
        },
      ],
      triggers: [],
    },

    cinder_thumb: {
      id: 'cinder_thumb',
      name: 'Cinder Thumb',
      subtitle: 'The volcanic reach · Near dusk',
      chapter: 'III · The king in the fire',
      ambience: 'Basalt, steam, and the pulse of a crystal under strain.',
      palette: {
        ground: '#302e2e',
        groundAlt: '#3b3431',
        path: '#574840',
        wall: '#171719',
        water: '#1d3942',
        detail: '#ff9c39',
        haze: '#8a5d43',
      },
      tiles: [
        '########################',
        '#....V....##....V......#',
        '#..::::...##...::::....#',
        '#..:..:...##...:..:....#',
        '#..:..::::==::::..:....#',
        '#..:.....L==L.....:....#',
        '#..VV....L==L....VV....#',
        '#..:.....L==L.....:....#',
        '#..:..::::==::::..:....#',
        '#..::::...##...::::....#',
        '#....V....##....V......#',
        '#.........##...........#',
        '#......................#',
        '########################',
      ],
      spawns: [
        { id: 'basalt_shelf', x: 4.5, y: 11.5, facing: 'up' },
        { id: 'standoff_retry', x: 8.5, y: 9.5, facing: 'up' },
      ],
      npcs: [
        {
          id: 'bram_cinder',
          characterId: 'bram',
          x: 6,
          y: 10,
          label: 'Speak with Bram',
          sceneId: 'bram_cinder_warning',
          repeatSceneId: 'bram_cinder_repeat',
        },
      ],
      interactions: [
        {
          id: 'steam_vent_pattern',
          type: 'object',
          x: 4,
          y: 6,
          label: 'Map the steam vent rhythm',
          sceneId: 'inspect_steam_vents',
          repeatSceneId: 'inspect_steam_vents_repeat',
        },
        {
          id: 'scorched_locket_clasp',
          type: 'object',
          x: 16,
          y: 10,
          label: 'Inspect the fallen clasp',
          sceneId: 'inspect_locket_clasp',
          repeatSceneId: 'inspect_locket_clasp_repeat',
        },
        {
          id: 'cinder_standoff_site',
          type: 'object',
          x: 18,
          y: 4,
          label: 'Approach the royal causeway',
          sceneId: 'cinder_standoff',
          requires: { flag: 'bramCinderWarning', equals: true },
          lockedMessage: 'Bram is studying the causeway. Hear what he has noticed first.',
          when: { not: { flag: 'cinderResolved', equals: true } },
        },
      ],
      triggers: [],
    },

    crown_city: {
      id: 'crown_city',
      name: 'Crown City',
      subtitle: 'The northern palm · Before dawn',
      chapter: 'IV · What the crown concealed',
      ambience: 'Archive dust above, forge sparks below, and a city choosing sides quietly.',
      palette: {
        ground: '#2c3036',
        groundAlt: '#343a42',
        path: '#665948',
        wall: '#1b1e24',
        water: '#213c48',
        detail: '#d5a44e',
        haze: '#78818c',
      },
      tiles: [
        '########################',
        '#HHHHH..::::..HHHHHH...#',
        '#HfffH..:..:..HffffH...#',
        '#Hf*fH..:..:..Hf*fH....#',
        '#HfffH..::::..HffffH...#',
        '#HH:HH....:...HH:HHH...#',
        '#..........:...........#',
        '#..::::::..:::::::.....#',
        '#..:....:........:.....#',
        '#..:O...::::::...:HHH..#',
        '#..:.............:HfH..#',
        '#..:::::::::::::::HHH..#',
        '#......................#',
        '########################',
      ],
      spawns: [
        { id: 'south_gate', x: 4.5, y: 12, facing: 'up' },
        { id: 'workshop_retry', x: 16.5, y: 10.5, facing: 'up' },
      ],
      npcs: [
        {
          id: 'lucen_archive',
          characterId: 'lucen',
          x: 4,
          y: 4,
          label: 'Speak with Prince Lucen',
          sceneId: 'meet_lucen',
          repeatSceneId: 'lucen_repeat',
        },
        {
          id: 'mara_workshop',
          characterId: 'mara',
          x: 18,
          y: 10,
          label: 'Speak with Mara',
          sceneId: 'meet_mara',
          repeatSceneId: 'mara_repeat',
        },
        {
          id: 'cael_confession_npc',
          characterId: 'cael',
          x: 14,
          y: 8,
          label: 'Hear Cael’s full account',
          sceneId: 'cael_confession',
          repeatSceneId: 'cael_confession_repeat',
          requires: {
            all: [
              { flag: 'lucenMet', equals: true },
              { flag: 'maraMet', equals: true },
            ],
          },
          lockedMessage: 'The workshop is not secure yet. Find Lucen and Mara first.',
          when: { not: { flag: 'caelConfessed', equals: true } },
        },
      ],
      interactions: [
        {
          id: 'elara_journal',
          type: 'object',
          x: 3,
          y: 3,
          label: 'Read Queen Elara’s field journal',
          sceneId: 'inspect_elara_journal',
          repeatSceneId: 'inspect_elara_journal_repeat',
        },
        {
          id: 'gate_ledger',
          type: 'object',
          x: 16,
          y: 3,
          label: 'Read the gate-energy ledger',
          sceneId: 'inspect_gate_ledger',
          repeatSceneId: 'inspect_gate_ledger_repeat',
        },
        {
          id: 'starling_cradle',
          type: 'object',
          x: 5,
          y: 9,
          label: 'Release the Starling',
          sceneId: 'workshop_escape',
          repeatSceneId: 'starling_repeat',
          requires: { flag: 'caelConfessed', equals: true },
          lockedMessage: 'The Starling is ready, but the choice of mission is not.',
          when: { not: { flag: 'workshopResolved', equals: true } },
        },
      ],
      triggers: [],
    },

    frostcrown: {
      id: 'frostcrown',
      name: 'Frostcrown Isle',
      subtitle: 'Beyond the Hand · Total eclipse',
      chapter: 'V · Seven circles, one choice',
      ambience: 'Wind over black water. The eclipse makes every crystal quiet enough to break.',
      palette: {
        ground: '#374653',
        groundAlt: '#435461',
        path: '#66717b',
        wall: '#1b252e',
        water: '#0d2634',
        detail: '#87e3e9',
        haze: '#c0ccd3',
      },
      tiles: [
        'IIIIIIIIIIIIIIIIIIIIIIII',
        'I~~~~~~~sssss~~~~~~~~~~I',
        'I~~~~~sssssssss~~~~~~~~I',
        'I~~~sss:::::::sss~~~~~~I',
        'I~~ss::.......::ss~~~~~I',
        'I~ss:...IIIII...:ss~~~~I',
        'I~s:...I..C..I...:s~~~~I',
        'I~s:...I.....I...:s~~~~I',
        'I~ss:...II:II...:ss~~~~I',
        'I~~ss::.......::ss~~~~~I',
        'I~~~sss:::::::sss~~~~~~I',
        'I~~~~~sssssssss~~~~~~~~I',
        'I~~~~~~~sssss~~~~~~~~~~I',
        'IIIIIIIIIIIIIIIIIIIIIIII',
      ],
      spawns: [
        { id: 'airship_ledge', x: 8.5, y: 10.5, facing: 'up' },
        { id: 'final_retry', x: 9.5, y: 9.5, facing: 'up' },
      ],
      npcs: [
        {
          id: 'cael_frost',
          characterId: 'cael',
          x: 7,
          y: 8,
          label: 'Speak with Cael',
          sceneId: 'cael_frost',
          repeatSceneId: 'cael_frost_repeat',
        },
        {
          id: 'mira_frost',
          characterId: 'mira',
          x: 11,
          y: 9,
          label: 'Speak with Mira',
          sceneId: 'mira_frost',
          repeatSceneId: 'mira_frost_repeat',
          when: { flag: 'miraJoined', equals: true },
        },
      ],
      interactions: [
        {
          id: 'starling_anchor',
          type: 'object',
          x: 5,
          y: 10,
          label: 'Inspect the Starling’s anchor line',
          sceneId: 'inspect_anchor',
          repeatSceneId: 'inspect_anchor_repeat',
        },
        {
          id: 'seven_grooves',
          type: 'object',
          x: 12,
          y: 7,
          label: 'Study the seven grooves',
          sceneId: 'inspect_seven_grooves',
          repeatSceneId: 'inspect_seven_grooves_repeat',
        },
        {
          id: 'final_circle',
          type: 'object',
          x: 11,
          y: 6,
          label: 'Enter the final circle',
          sceneId: 'frostcrown_final',
          requires: { flag: 'caelFrostSpoken', equals: true },
          lockedMessage: 'Cael is waiting by the outer ring. Speak with him before entering.',
          when: { not: { flag: 'finalResolved', equals: true } },
        },
      ],
      triggers: [],
    },
  };

  const data = Object.freeze({
    tileSize: TILE_SIZE,
    legend: LEGEND,
    maps,
    mapOrder: [
      'birchwood',
      'willowmere',
      'greenwake',
      'ashfinger',
      'cinder_thumb',
      'crown_city',
      'frostcrown',
    ],
  });

  root.GAME_MAPS = data;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = data;
  }
}(typeof window !== 'undefined' ? window : globalThis));
