'use strict';

(() => {
  const sources = [
    {
      label: 'CERN · CMS looks deep inside quarks (2026)',
      url: 'https://home.cern/cms-looks-deep-inside-quarks/',
    },
    {
      label: 'NIST · 2022 CODATA fundamental constants',
      url: 'https://physics.nist.gov/cuu/pdf/JPCRD2022CODATA.pdf',
    },
    {
      label: 'NIST · Macro, Micro, Nano scale poster',
      url: 'https://www.nist.gov/system/files/documents/2017/05/09/macro-micro-nano-scaleofthings-poster.pdf',
    },
    {
      label: 'National Human Genome Research Institute · DNA scale',
      url: 'https://www.genome.gov/2007-national-dna-day-online-chatroom-transcript',
    },
    {
      label: 'NIH / NCBI · Virus structure and classification',
      url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7150055/',
    },
    {
      label: 'NIH / NIGMS · A tour of cell organelles',
      url: 'https://nigms.nih.gov/biobeat/2021/03/take-a-tour-of-your-cells-organelles',
    },
    {
      label: 'USGS · Sand grain-size definitions',
      url: 'https://apps.usgs.gov/thesaurus/term-simple.php?code=1011&thcode=2',
    },
    {
      label: 'NOAA Fisheries · Blue whale',
      url: 'https://www.fisheries.noaa.gov/species/blue-whale',
    },
    {
      label: 'USGS · Understanding map scale',
      url: 'https://www.usgs.gov/educational-resources/27-ideas-teaching-topographic-maps-0',
    },
    {
      label: 'NASA Science · Facts about Earth',
      url: 'https://science.nasa.gov/earth/facts/',
    },
    {
      label: 'NASA JPL · Modeling the Earth–Moon system',
      url: 'https://www.jpl.nasa.gov/edu/pdfs/earth_moon_distance-worksheet.pdf',
    },
    {
      label: 'NASA · The Sun in depth',
      url: 'https://solarsystem.nasa.gov/solar-system/sun/in-depth.amp',
    },
    {
      label: 'NASA · The voyage to interstellar space',
      url: 'https://www.nasa.gov/solar-system/the-voyage-to-interstellar-space/',
    },
    {
      label: 'NASA · Our nearest stars',
      url: 'https://imagine.gsfc.nasa.gov/features/cosmic/nearest_star_info.html',
    },
    {
      label: 'ESA Gaia · Milky Way map',
      url: 'https://www.cosmos.esa.int/web/gaia/milky-way',
    },
    {
      label: 'NASA Science · How big is space?',
      url: 'https://science.nasa.gov/universe/exoplanets/our-milky-way-galaxy-how-big-is-space/',
    },
    {
      label: 'BIPM · SI Brochure, 9th edition',
      url: 'https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf/2d2b50bf-f2b4-9661-f402-5f9d66e4b507',
    },
  ];

  const ui = {
    en: {
      documentTitle: 'THE LONG ZOOM · From Quarks to Galaxies',
      description: 'A bilingual cinematic narrated journey across more than forty powers of ten, from quarks to giant galaxies.',
      skip: 'Skip to the current chapter',
      back: 'Back to games',
      brandSubtitle: 'A journey through scale',
      languageLabel: 'Language',
      chooseLanguage: 'Choose your language',
      english: 'English',
      japanese: '日本語',
      panelHide: 'Hide story panel',
      panelShow: 'Show story panel',
      panelShort: 'Story',
      captionsShow: 'Open transcript',
      captionsHide: 'Close transcript',
      captionsShort: 'Transcript',
      soundOff: 'Mute narration',
      soundOn: 'Unmute narration',
      soundShort: 'Sound',
      infoOpen: 'Open information and sources',
      introKicker: 'FROM THE ALMOST POINT-LIKE TO THE ALMOST UNIMAGINABLE',
      introTitle: 'THE LONG ZOOM',
      introSubtitle: 'From quarks to galaxies',
      introLede: 'Stand at human scale for one breath. Then travel outward—and inward—across more than forty powers of ten.',
      introScenes: 'chapters',
      introDuration: 'about 12 min',
      introDurationLabel: 'narrated journey',
      introQuizzes: 'scale pauses',
      startEyebrow: 'English narration',
      start: 'Begin the zoom',
      headphone: 'Headphones recommended · narration can be changed at any time',
      openingCoordinate: 'YOU ARE HERE · ABOUT 10⁰ METRES',
      storyLabel: 'The Long Zoom story',
      narrationReady: 'Narration ready',
      narrationLoading: 'Loading narration',
      narrationPlaying: 'English narration playing',
      narrationPaused: 'Narration paused',
      narrationComplete: 'Narration complete',
      narrationMuted: 'Narration is muted',
      narrationError: 'Audio unavailable — transcript remains available',
      narrationBlocked: 'Press replay to hear this chapter',
      replay: 'Replay this chapter narration',
      transcriptTitle: 'Exact narration transcript',
      transcriptLoading: 'Loading transcript…',
      transcriptError: 'The transcript file could not be loaded.',
      transcriptClose: 'Close transcript',
      previous: 'Previous',
      previousAria: 'Previous chapter',
      next: 'Next',
      nextAria: 'Next chapter',
      restart: 'Restart',
      restartAria: 'Return to the opening screen',
      sceneOf: 'Scene {current} of {total}',
      progressAria: 'Direct chapter navigation, {total} scenes',
      progressScene: 'Go to scene {number}: {title}',
      scaleWord: 'Scale word',
      representativeScale: 'Representative scale',
      factsLabel: 'Three things to notice',
      quizKicker: 'SCALE PAUSE',
      quizPrompt: 'Choose one answer.',
      quizCorrect: 'Exactly.',
      quizIncorrect: 'Good guess.',
      quizAnswered: 'Answered',
      answerAria: 'Answer {number}: {answer}',
      infoKicker: 'FIELD NOTES',
      infoTitle: 'About this journey',
      infoClose: 'Close information',
      controlsTitle: 'Controls',
      controlsText: 'Use the bottom arrows, the progress rail, or ← and →. Press R to replay, C for the transcript, M for sound, P for the story panel, L to switch language, and I for this dialog. Keys 1–3 answer a scale pause.',
      panelHelp: 'Hiding the story panel leaves narration and every navigation, language, sound, transcript, and help control available. Your panel, sound, and language choices are remembered when storage is available.',
      accessibilityTitle: 'Motion and access',
      accessibilityText: 'Reduced-motion preferences remove decorative drift and crossfade movement without removing content. Controls have visible focus, touch-sized targets, landmarks, and live announcements.',
      mediaTitle: 'Generated media',
      mediaText: 'All scene images were generated specifically for this experience and are artist’s impressions. Quantum, cellular, heliospheric, and galaxy views cannot be literal photographs or are shown from impossible viewpoints. No external images load at runtime.',
      voiceTitle: 'Narration',
      voiceText: 'English narration uses the local Piper Lessac voice. Japanese narration uses the local Voicevox Shikoku Metan voice. WAV masters and exact UTF-8 transcripts are retained; the browser plays local MP3 exports.',
      accuracyTitle: 'Reading the scale',
      accuracyText: 'Values are rounded for listening. “Size” may mean diameter, width, charge radius, separation, or an estimated visible extent; every chapter says which. Objects vary, boundaries can be fuzzy, and the first and final limits are deliberately cautious.',
      sourcesTitle: 'Research sources',
      sourcesNote: 'Authoritative sources checked 19 August 2026. Links open in a new tab.',
      statusStarted: 'Journey started. Scene 1 of 19.',
      statusLanguage: 'Language changed to English. Narration and transcript replaced for this scene.',
      statusPanelShown: 'Story panel shown.',
      statusPanelHidden: 'Story panel hidden. Narration and controls remain available.',
      statusCaptionsShown: 'Transcript opened.',
      statusCaptionsHidden: 'Transcript closed.',
      statusSoundOn: 'Narration unmuted.',
      statusSoundOff: 'Narration muted.',
      statusScene: 'Scene {current} of {total}: {title}.',
      notApplicable: 'not a literal diameter',
    },
    ja: {
      documentTitle: 'はてしないズーム · クォークから銀河へ',
      description: 'クォークから巨大銀河まで、四十桁以上のスケールをめぐる日英二言語の映画的な音声体験。',
      skip: '現在の章へ移動',
      back: 'ゲーム一覧へ戻る',
      brandSubtitle: 'スケールをめぐる旅',
      languageLabel: '言語',
      chooseLanguage: '言語を選んでください',
      english: 'English',
      japanese: '日本語',
      panelHide: '物語パネルを隠す',
      panelShow: '物語パネルを表示',
      panelShort: '物語',
      captionsShow: '字幕を開く',
      captionsHide: '字幕を閉じる',
      captionsShort: '字幕',
      soundOff: 'ナレーションをミュート',
      soundOn: 'ナレーションをオン',
      soundShort: '音声',
      infoOpen: '案内と出典を開く',
      introKicker: '点のような世界から、想像をこえる広がりへ',
      introTitle: 'はてしないズーム',
      introSubtitle: 'クォークから銀河へ',
      introLede: 'まず一呼吸、人の大きさに立ってみましょう。そこから内へ、外へ。四十桁以上のスケールを旅します。',
      introScenes: '章',
      introDuration: '約12分',
      introDurationLabel: '音声の旅',
      introQuizzes: 'つの小クイズ',
      startEyebrow: '日本語ナレーション',
      start: 'ズームをはじめる',
      headphone: 'イヤホン推奨 · ナレーションはいつでも切り替えられます',
      openingCoordinate: 'あなたはここ · およそ10の0乗メートル',
      storyLabel: 'はてしないズームの物語',
      narrationReady: 'ナレーション準備完了',
      narrationLoading: 'ナレーションを読み込み中',
      narrationPlaying: '日本語ナレーション再生中',
      narrationPaused: 'ナレーション一時停止',
      narrationComplete: 'ナレーションを聞き終えました',
      narrationMuted: 'ナレーションはミュート中です',
      narrationError: '音声を再生できません。字幕は利用できます',
      narrationBlocked: '再生ボタンを押すと、この章を聞けます',
      replay: 'この章のナレーションをもう一度聞く',
      transcriptTitle: 'ナレーション全文',
      transcriptLoading: '字幕を読み込んでいます…',
      transcriptError: '字幕ファイルを読み込めませんでした。',
      transcriptClose: '字幕を閉じる',
      previous: 'もどる',
      previousAria: '前の章へ',
      next: 'つぎへ',
      nextAria: '次の章へ',
      restart: 'もう一度',
      restartAria: 'オープニング画面へ戻る',
      sceneOf: '{total}場面中 {current}場面',
      progressAria: '全{total}場面へ直接移動',
      progressScene: '{number}場面目「{title}」へ移動',
      scaleWord: 'スケールの言葉',
      representativeScale: '代表的なスケール',
      factsLabel: '覚えておきたい三つ',
      quizKicker: 'スケール・ポーズ',
      quizPrompt: 'ひとつ選んでください。',
      quizCorrect: 'そのとおり。',
      quizIncorrect: 'いい推理です。',
      quizAnswered: '回答済み',
      answerAria: '答え{number}、{answer}',
      infoKicker: '旅のノート',
      infoTitle: 'この体験について',
      infoClose: '案内を閉じる',
      controlsTitle: '操作',
      controlsText: '画面下の矢印、進行レール、または ← → で移動します。R は再生、C は字幕、M は音声、P は物語パネル、L は言語、I はこの案内です。小クイズは 1〜3 キーでも答えられます。',
      panelHelp: '物語パネルを隠しても、ナレーション、移動、言語、音声、字幕、案内の操作は残ります。保存機能が使える場合は、パネル・音声・言語の設定を記憶します。',
      accessibilityTitle: '動きとアクセシビリティ',
      accessibilityText: '端末の「視差効果を減らす」設定では、内容を失わず装飾的な動きとクロスフェードを抑えます。見えるフォーカス、押しやすい操作、ランドマーク、音声読み上げ向けの通知を備えています。',
      mediaTitle: '生成メディア',
      mediaText: 'すべての場面画像は、この体験のために生成したアーティスト・インプレッションです。量子、細胞、太陽圏、銀河などは、写真にできない姿や実際には置けない視点から表現しています。実行時に外部画像は読み込みません。',
      voiceTitle: 'ナレーション',
      voiceText: '英語はローカルのパイパー、レサック音声。日本語はローカルのボイスボックス、四国めたん音声です。WAVマスターと完全一致するUTF-8字幕を保存し、ブラウザーではローカルMP3を再生します。',
      accuracyTitle: 'スケールの読み方',
      accuracyText: '聞きやすいよう数値は丸めています。「大きさ」は直径、幅、電荷半径、距離、推定される広がりなど、章によって意味が違います。物には個体差があり、境界がぼやける場合もあります。最初と最後の限界は特に慎重に表現しました。',
      sourcesTitle: '調査出典',
      sourcesNote: '2026年8月19日に公的・研究機関の資料を確認しました。リンクは別タブで開きます。',
      statusStarted: '旅を始めました。全19場面の1場面目です。',
      statusLanguage: '言語を日本語に変更しました。この場面の音声と字幕を差し替えました。',
      statusPanelShown: '物語パネルを表示しました。',
      statusPanelHidden: '物語パネルを隠しました。ナレーションと操作は引き続き使えます。',
      statusCaptionsShown: '字幕を開きました。',
      statusCaptionsHidden: '字幕を閉じました。',
      statusSoundOn: 'ナレーションをオンにしました。',
      statusSoundOff: 'ナレーションをミュートしました。',
      statusScene: '全{total}場面の{current}場面目、「{title}」。',
      notApplicable: '実体の直径ではありません',
    },
  };

  const scenes = [
    {
      id: 'quantum-edge',
      kind: 'story',
      image: 'assets/images/01-quantum.webp',
      tone: 'quantum',
      layout: 'left',
      focal: '50% 50%',
      order: -20,
      scale: '< 10⁻²⁰ m',
      en: {
        chapter: '01 · THE PROBED EDGE',
        title: 'Small does not end with a tiny ball.',
        lede: 'Quarks and electrons behave as fundamental, point-like particles. Experiments set limits—not little measured diameters.',
        facts: [
          ['< 10⁻²⁰ m', 'quark structure probed', 'No inner parts appeared in the 2026 CMS result'],
          ['6', 'quark flavours', 'Up, down, charm, strange, top, bottom'],
          ['point-like', 'best current model', 'A mathematical statement, not a photograph'],
        ],
        note: 'This artwork makes invisible interactions visible. Color and shape are interpretive; the collision evidence is real.',
        term: ['zepto', 'ZEP-toh', 'the SI prefix for 10⁻²¹'],
        narration: 'Begin before anything has a familiar surface. In our best-tested model, quarks and electrons are fundamental and point-like. That does not prove they are infinitely small. It means experiments have found no inner structure. In 2026, CERN reported quarks still looking point-like down to about ten to the minus twenty metres. Here, the light is an artist’s language for interaction. Our first step is therefore not a measured diameter, but an honest frontier: the smallest scale we have directly tested.',
      },
      ja: {
        chapter: '01 · 観測の最前線',
        title: '小ささの果ては、小さな玉ではない。',
        lede: 'クォークと電子は、基本的で点のような粒子として振る舞います。実験が示すのは直径ではなく、上限です。',
        facts: [
          ['10のマイナス20乗m未満', '調べた内部構造', '2026年のシー・エム・エス実験でも見つからず'],
          ['6種類', 'クォーク', 'アップ、ダウン、チャーム、ストレンジ、トップ、ボトム'],
          ['点のよう', '現在の最良モデル', '写真ではなく、数学的な表現'],
        ],
        note: 'この画像は、見えない相互作用を見える形にした表現です。色と形は創作ですが、衝突実験の証拠は実在します。',
        term: ['ゼプト', 'ぜぷと', '10のマイナス21乗を表す接頭語'],
        narration: 'まだ表面という言葉さえ似合わない場所から始めます。現在もっともよく確かめられた理論では、クォークと電子は、基本的で、点のような粒子です。無限に小さいと証明されたわけではありません。内部構造が見つかっていない、という意味です。2026年、セルンは、クォークが10のマイナス20乗メートルほどまで、点のように見えると報告しました。ここに見える光は、相互作用を表すための創作です。最初の一歩は直径ではなく、私たちが直接確かめた、正直な最前線なのです。',
      },
    },
    {
      id: 'proton',
      kind: 'story',
      image: 'assets/images/02-proton.webp',
      tone: 'quantum',
      layout: 'right',
      focal: '50% 50%',
      order: -15,
      scale: '0.84 fm radius',
      en: {
        chapter: '02 · INSIDE A PROTON',
        title: 'A particle can be a crowd.',
        lede: 'A proton is a restless quantum system: three valence quarks, gluons, and a shifting sea of quark–antiquark pairs.',
        facts: [
          ['0.84075 fm', 'charge radius', 'The 2022 CODATA recommended value'],
          ['3', 'valence quarks', 'Two up and one down set its identity'],
          ['most', 'of its mass', 'Comes from the energy of the strong interaction'],
        ],
        note: 'A proton has no hard outer shell. Its “radius” depends on what is measured; this chapter uses the rms charge radius.',
        term: ['femto', 'FEM-toh', 'the SI prefix for 10⁻¹⁵'],
        narration: 'Zoom out one hundred thousand times and a structure appears: the proton. Even now, do not imagine a neat container with three beads inside. A proton is a storm of quantum fields. Three valence quarks establish its electric charge, while gluons and short-lived quark pairs surge through the same tiny region. Its recommended charge radius is about zero point eight four femtometres. Much of the proton’s mass comes not from adding quark masses, but from the energy of this confined motion. The apparently solid world begins with something astonishingly restless.',
      },
      ja: {
        chapter: '02 · 陽子の内側',
        title: 'ひとつの粒子が、群れでもある。',
        lede: '陽子は静かな玉ではありません。三つの価クォーク、グルーオン、現れては消えるクォークの対が動く量子系です。',
        facts: [
          ['0.84075fm', '電荷半径', '2022年コデータ推奨値'],
          ['3個', '価クォーク', 'アップ二つとダウン一つが正体を決める'],
          ['大部分', '陽子の質量', '強い相互作用のエネルギーから生まれる'],
        ],
        note: '陽子に硬い殻はありません。「半径」は測り方で意味が変わり、ここでは二乗平均平方根の電荷半径を使います。',
        term: ['フェムト', 'ふぇむと', '10のマイナス15乗を表す接頭語'],
        narration: '十万倍ほど引いてみると、陽子の構造が現れます。それでも、三つの玉が箱に入っている姿を想像しないでください。陽子は量子場の嵐です。三つの価クォークが電荷を決め、グルーオンと、短い時間だけ現れるクォークの対が、同じ小さな領域を駆けめぐります。推奨される電荷半径は、およそ0.84フェムトメートル。陽子の質量の多くは、クォークの重さを足したものではなく、閉じ込められた運動のエネルギーから生まれます。固く見える世界の始まりは、驚くほど落ち着きがありません。',
      },
    },
    {
      id: 'atom',
      kind: 'quiz',
      image: 'assets/images/03-atom.webp',
      tone: 'atomic',
      layout: 'left',
      focal: '50% 50%',
      order: -10,
      scale: '≈ 0.1 nm',
      en: {
        chapter: '03 · THE ATOM',
        title: 'Matter is mostly room.',
        lede: 'An atom is roughly a tenth of a nanometre across. Its tiny nucleus sits inside a much wider electron probability cloud.',
        facts: [
          ['≈ 10⁻¹⁰ m', 'atomic scale', 'About one ångström'],
          ['99.99%+', 'not nucleus', 'The atom’s extent is overwhelmingly cloud'],
          ['cloud', 'electron location', 'Probability replaces a little orbiting planet'],
        ],
        note: 'Atoms have no sharp edge. Their effective size changes with element, bond, and definition.',
        term: ['ångström', 'ANG-strum', '10⁻¹⁰ metre, common in atomic science'],
        narration: 'Another one hundred thousand times outward brings us to the atom, around a tenth of a nanometre across. The nucleus holds almost all the mass, yet occupies only a minute fraction of the span. Electrons do not circle it on tidy tracks. Quantum mechanics gives us a probability cloud: regions where an electron may be found. That makes the atom spacious without making it empty of physics. Electric forces, wave behaviour, and exclusion rules give matter its shape. The chair beneath you feels solid because these diffuse atomic worlds resist being pushed through one another.',
        quiz: {
          question: 'If an atomic nucleus were widened to 1 centimetre, about how wide would the whole atom be?',
          options: ['A small room', 'About 1 kilometre', 'The diameter of Earth'],
          answer: 1,
          explanation: 'Atomic span is roughly 100,000 times nuclear span. A 1 cm nucleus would sit inside an atom about 1 km wide; the exact analogy varies by atom and definition.',
        },
      },
      ja: {
        chapter: '03 · 原子',
        title: '物質の中は、ほとんどが広がり。',
        lede: '原子の直径は、およそ0.1ナノメートル。ごく小さな原子核を、はるかに広い電子の確率雲が包みます。',
        facts: [
          ['約10のマイナス10乗m', '原子のスケール', 'およそ1オングストローム'],
          ['99.99%以上', '原子核ではない範囲', '原子の広がりの大半は電子雲'],
          ['確率雲', '電子の位置', '小さな惑星の軌道ではない'],
        ],
        note: '原子に鋭い縁はありません。元素、結合、定義によって、有効な大きさは変わります。',
        term: ['オングストローム', 'おんぐすとろーむ', '原子科学で使う10のマイナス10乗メートル'],
        narration: 'さらに十万倍ほど引くと、原子に届きます。大きさは、およそ0.1ナノメートル。原子核は質量のほとんどを持ちますが、占める場所はごくわずかです。電子は、整った線の上を回る小さな惑星ではありません。量子力学が示すのは、電子が見つかりうる領域、確率の雲です。原子は広々としていますが、物理的に空っぽではありません。電気の力、波の性質、そして重なりを許さない規則が、物質の形を作ります。椅子が固く感じられるのは、こうしたぼんやり広がる原子の世界が、互いに通り抜けることへ抵抗するからです。',
        quiz: {
          question: '原子核を直径1センチまで広げたら、原子全体はどれくらいになるでしょう？',
          options: ['小さな部屋くらい', 'およそ1キロメートル', '地球の直径くらい'],
          answer: 1,
          explanation: '原子の広がりは、原子核のおよそ十万倍です。1センチの原子核なら、原子全体は約1キロメートル。原子や定義によって比率は少し変わります。',
        },
      },
    },
    {
      id: 'dna',
      kind: 'story',
      image: 'assets/images/04-dna.webp',
      tone: 'molecular',
      layout: 'right',
      focal: '50% 50%',
      order: -8.7,
      scale: '≈ 2 nm wide',
      en: {
        chapter: '04 · THE MOLECULAR THREAD',
        title: 'Information has a width.',
        lede: 'The DNA double helix is about two nanometres wide: a molecular thread whose sequence can be copied and read.',
        facts: [
          ['≈ 2 nm', 'helix width', 'Twenty or so hydrogen atoms across'],
          ['4', 'chemical bases', 'Their order stores biological instructions'],
          ['packed', 'inside cells', 'Long molecules fold around proteins'],
        ],
        note: 'The familiar ladder is a useful structural model. Real DNA bends, twists, moves, and interacts constantly.',
        term: ['nano', 'NAN-oh', 'the SI prefix for 10⁻⁹'],
        narration: 'At two nanometres wide, chemistry begins to feel like architecture. DNA’s two backbones twist into a double helix, while paired chemical bases make the rungs between them. The sequence of four base types stores instructions that cells can copy, repair, and read. Yet DNA is not a motionless ladder. It bends, vibrates, coils around proteins, and folds again so an enormously long molecule can work inside a microscopic cell. Information here is not floating abstraction. It has mass, shape, and a width—about two billionths of a metre.',
      },
      ja: {
        chapter: '04 · 分子の糸',
        title: '情報にも、幅がある。',
        lede: 'DNAの二重らせんは、幅およそ2ナノメートル。配列を読み、写すことのできる分子の糸です。',
        facts: [
          ['約2nm', 'らせんの幅', '水素原子およそ二十個ぶん'],
          ['4種類', '化学塩基', '並び順が生物の情報を蓄える'],
          ['折りたたむ', '細胞の中で', '長い分子をタンパク質に巻きつける'],
        ],
        note: 'はしごの形は便利な構造モデルです。実際のDNAは曲がり、ねじれ、動き、絶えず周囲と関わります。',
        term: ['ナノ', 'なの', '10のマイナス9乗を表す接頭語'],
        narration: '幅2ナノメートルの場所では、化学が建築のように見えてきます。DNAの二本の骨格は二重らせんを作り、その間を、対になった化学塩基が横木のようにつなぎます。四種類の塩基の並びには、細胞が写し、直し、読み取れる情報が蓄えられています。ただしDNAは、止まったはしごではありません。曲がり、揺れ、タンパク質に巻きつき、さらに折りたたまれて、とても長い分子が小さな細胞の中で働けるようになります。ここで情報は、宙に浮く抽象ではありません。質量と形、そして、およそ20億分の1メートルという幅を持っています。',
      },
    },
    {
      id: 'virus',
      kind: 'story',
      image: 'assets/images/05-virus.webp',
      tone: 'bio',
      layout: 'left',
      focal: '48% 50%',
      order: -7,
      scale: '≈ 100 nm typical',
      en: {
        chapter: '05 · A BORROWED MACHINE',
        title: 'Small enough to need a host.',
        lede: 'A typical influenza virion is about one hundred nanometres across. Viruses vary enormously and reproduce only through host cells.',
        facts: [
          ['≈ 100 nm', 'influenza scale', 'A useful middle-sized virus example'],
          ['20–200 nm', 'many human viruses', 'Some are smaller; some are far larger'],
          ['no cell', 'viral structure', 'Genome and protein, sometimes wrapped in membrane'],
        ],
        note: 'This is a colorized artist’s impression. Electron microscopes supply structure, not this visible-light color palette.',
        term: ['virion', 'VEER-ee-on', 'one complete virus particle outside a cell'],
        narration: 'At roughly one hundred nanometres, an influenza virion is large compared with DNA and tiny beside a cell. Its genetic material travels in a protein package wrapped in membrane borrowed from a previous host. Surface proteins help it attach to another cell. Then the striking part: a virus does not carry the complete machinery to reproduce itself. It redirects the host’s molecular workshop. Viruses range from about the size of large protein assemblies to forms larger than some bacteria, so one number never describes them all. This is a scale waypoint, not a definition of life.',
      },
      ja: {
        chapter: '05 · 借りものの機械',
        title: '宿主が必要なほど、小さい。',
        lede: '典型的なインフルエンザのウイルス粒子は、直径およそ100ナノメートル。ウイルスの大きさは幅広く、増えるには宿主細胞が必要です。',
        facts: [
          ['約100nm', 'インフルエンザの目安', '中くらいのウイルスの一例'],
          ['20〜200nm', '多くのヒトウイルス', 'さらに小さいものも、ずっと大きいものもある'],
          ['細胞ではない', 'ウイルスの構造', '遺伝物質とタンパク質、ときに膜を持つ'],
        ],
        note: 'これは色をつけた創作表現です。電子顕微鏡で構造は分かりますが、この色が見えるわけではありません。',
        term: ['ビリオン', 'びりおん', '細胞の外にある、完成したウイルス粒子'],
        narration: 'およそ100ナノメートル。インフルエンザのウイルス粒子は、DNAより大きく、細胞よりはるかに小さい存在です。遺伝物質はタンパク質の容器に入り、以前の宿主から借りた膜に包まれています。表面のタンパク質で次の細胞に取りつきます。ここからが特徴的です。ウイルスは、自分だけで増えるための機械を一式持っていません。宿主の分子工場の向きを変えて利用します。ウイルスには、大きなタンパク質ほどのものから、一部の細菌より大きなものまであります。ひとつの数値ですべては語れません。これはスケールの目印であって、生命の定義ではないのです。',
      },
    },
    {
      id: 'cell',
      kind: 'quiz',
      image: 'assets/images/06-cell.webp',
      tone: 'bio',
      layout: 'right',
      focal: '50% 50%',
      order: -4.7,
      scale: '≈ 20 µm typical',
      en: {
        chapter: '06 · A LIVING ROOM',
        title: 'A cell is a world with traffic.',
        lede: 'A typical animal cell spans around ten to thirty micrometres. Membranes organize thousands of simultaneous chemical tasks.',
        facts: [
          ['10–30 µm', 'typical animal cell', 'Cells vary dramatically in shape and size'],
          ['nucleus', 'genome library', 'One organelle among many specialized regions'],
          ['constant', 'molecular traffic', 'Cargo moves, membranes fold, energy changes form'],
        ],
        note: 'This cutaway combines structures for clarity. A real cell is translucent, dynamic, crowded, and never arranged for a camera.',
        term: ['micro', 'MY-kroh', 'the SI prefix for 10⁻⁶'],
        narration: 'Now the scene becomes a living room—though nothing stays still. A typical animal cell is ten to thirty micrometres across. Inside, folded membranes build and move molecules. Mitochondria transform energy. Vesicles carry cargo. Fibres brace the cell and serve as tracks. The nucleus protects a working copy of the genome, but it is not a tiny manager issuing every command. Life emerges from many chemical conversations happening at once. Compared with a one-hundred-nanometre influenza particle, a twenty-micrometre cell spans about two hundred virus widths.',
        quiz: {
          question: 'About how many 100 nm virus widths fit across a 20 µm cell?',
          options: ['2', '200', '20,000'],
          answer: 1,
          explanation: 'Twenty micrometres equals 20,000 nanometres. Divide by 100 nanometres and the answer is about 200.',
        },
      },
      ja: {
        chapter: '06 · 生きている部屋',
        title: '細胞は、交通のある世界。',
        lede: '典型的な動物細胞は、およそ10〜30マイクロメートル。膜で空間を分け、何千もの化学反応を同時に進めます。',
        facts: [
          ['10〜30µm', '典型的な動物細胞', '形も大きさも細胞ごとに大きく異なる'],
          ['細胞核', 'ゲノムの書庫', '専門化した数多くの領域のひとつ'],
          ['休みなく', '分子の交通', '荷物が動き、膜が折れ、エネルギーが姿を変える'],
        ],
        note: 'この断面図は、分かりやすさのため構造を組み合わせています。実際の細胞は透明で、混み合い、動き続け、カメラ向けには並びません。',
        term: ['マイクロ', 'まいくろ', '10のマイナス6乗を表す接頭語'],
        narration: 'ここからは、生きている部屋です。ただし、何ひとつ止まってはいません。典型的な動物細胞は、10から30マイクロメートルほど。折りたたまれた膜が分子を作り、運びます。ミトコンドリアがエネルギーを変換し、小胞が荷物を運び、繊維が体を支えながら通路にもなります。細胞核はゲノムの作業用コピーを守りますが、すべてに命令する小さな司令官ではありません。生命は、同時に進む多くの化学的な会話から現れます。20マイクロメートルの細胞なら、100ナノメートルのウイルス、およそ二百個ぶんの幅があります。',
        quiz: {
          question: '幅20マイクロメートルの細胞には、幅100ナノメートルのウイルスが何個ぶん並ぶでしょう？',
          options: ['2個', '200個', '2万個'],
          answer: 1,
          explanation: '20マイクロメートルは、2万ナノメートルです。100ナノメートルで割ると、およそ200個になります。',
        },
      },
    },
    {
      id: 'sand-grain',
      kind: 'story',
      image: 'assets/images/07-sand.webp',
      tone: 'earthy',
      layout: 'left',
      focal: '50% 50%',
      order: -3.3,
      scale: '≈ 0.5 mm example',
      en: {
        chapter: '07 · THE GRAIN',
        title: 'A speck becomes a landscape.',
        lede: 'Sand is a size class, not one material. This half-millimetre quartz grain carries fractures, inclusions, and a travel history.',
        facts: [
          ['0.0625–2 mm', 'sand range', 'The widely used Wentworth size class'],
          ['quartz', 'common mineral', 'Hard enough to survive long transport'],
          ['rounded', 'worn edges', 'Water, wind, and collisions reshape a grain'],
        ],
        note: 'A grain in your shoe feels tiny to you; to a cell it would be a cliff roughly twenty-five cell widths across.',
        term: ['milli', 'MIL-ee', 'the SI prefix for 10⁻³'],
        narration: 'At half a millimetre, the invisible becomes a speck you can feel between your fingers—or in your shoe. Geologists define sand by size: from about zero point zero six two five to two millimetres, whatever mineral the grain is made from. This one is imagined as quartz, with worn edges and inclusions recording an untold journey through rock, river, and shore. Set beside a twenty-micrometre cell, it spans roughly twenty-five cell widths. Every beach is therefore a crowd of small landscapes, each grain far larger than the living rooms we just left.',
      },
      ja: {
        chapter: '07 · 一粒',
        title: '小さな点が、風景になる。',
        lede: '砂は物質名ではなく、大きさの分類です。この0.5ミリメートルの石英粒には、割れ目、内包物、旅の痕跡があります。',
        facts: [
          ['0.0625〜2mm', '砂の範囲', '広く使われるウェントワース粒径区分'],
          ['石英', 'よくある鉱物', '硬く、長い移動にも残りやすい'],
          ['丸み', '削れた角', '水、風、衝突が粒を作り変える'],
        ],
        note: '靴に入れば小さな砂粒も、細胞から見れば、幅およそ二十五個ぶんの崖です。',
        term: ['ミリ', 'みり', '10のマイナス3乗を表す接頭語'],
        narration: '0.5ミリメートルまで来ると、見えなかった世界が、指でつまめる粒になります。靴の中なら、すぐ気づく大きさです。地質学では、砂を物質ではなく大きさで分けます。およそ0.0625ミリメートルから2ミリメートルまで。どの鉱物でできていても、この範囲なら砂です。この一粒は石英。削れた角や内包物には、岩、川、海岸を通った、名もない旅が刻まれています。20マイクロメートルの細胞と並べれば、およそ二十五個ぶん。浜辺は、小さな風景が集まった場所なのです。',
      },
    },
    {
      id: 'hand',
      kind: 'story',
      image: 'assets/images/08-hand.webp',
      tone: 'human',
      layout: 'right',
      focal: '50% 50%',
      order: -1,
      scale: '≈ 10 cm',
      en: {
        chapter: '08 · THE FIRST RULER',
        title: 'Your hand already knows scale.',
        lede: 'A palm is roughly ten centimetres across. Before formal units, bodies offered portable, imperfect measures.',
        facts: [
          ['≈ 10 cm', 'palm-scale guide', 'Useful, never universal'],
          ['touch', 'a scale sensor', 'Texture changes as features reach fingertip size'],
          ['variable', 'human measure', 'Age, body, and culture resist one standard hand'],
        ],
        note: 'Hands connect measurement with daily life: a pinch of salt, a cup held warm, a distance shown to a friend.',
        term: ['centi', 'SEN-tee', 'the SI prefix for 10⁻²'],
        narration: 'At ten centimetres, scale becomes personal. A hand can cup water, test a surface, cradle a stone, or show another person how large something was. Bodies served as convenient measures long before standardized rulers, but they also reveal why standards matter: no two hands are exactly alike. Touch changes our sense of size. A ridge too small to see may still catch a fingertip; a grain becomes roughness; a warm cup fits a palm. Measurement is not only numbers read by machines. It began as a conversation between bodies and the world.',
      },
      ja: {
        chapter: '08 · 最初のものさし',
        title: '手はもう、スケールを知っている。',
        lede: '手のひらは、およそ10センチメートル。正式な単位より前から、体は持ち運べる、少し不揃いなものさしでした。',
        facts: [
          ['約10cm', '手のひらの目安', '便利でも、誰にでも同じではない'],
          ['触覚', '大きさのセンサー', '指先ほどになると、形が手触りへ変わる'],
          ['個人差', '体による計測', '年齢、体格、文化をひとつにそろえられない'],
        ],
        note: '塩をひとつまみ、温かいカップを包む、友だちに幅を示す。手は計測と暮らしをつなぎます。',
        term: ['センチ', 'せんち', '10のマイナス2乗を表す接頭語'],
        narration: '10センチメートルになると、スケールは自分のものになります。手は水をすくい、表面を確かめ、石を包み、どれくらい大きかったかを誰かに示せます。標準のものさしができる前、体は便利な測定器でした。同時に、なぜ標準が必要かも教えます。まったく同じ手は、二つとありません。触覚も大きさの感じ方を変えます。見えないほど細い筋が指先に引っかかり、砂粒の集まりは、ざらざらへ変わる。温かいカップは手のひらに収まります。測ることは、機械が読む数字だけではありません。体と世界の会話から始まったのです。',
      },
    },
    {
      id: 'human',
      kind: 'story',
      image: 'assets/images/09-human.webp',
      tone: 'human',
      layout: 'left',
      focal: '50% 52%',
      order: 0.23,
      scale: '≈ 1.7 m guide',
      en: {
        chapter: '09 · YOU ARE HERE',
        title: 'The middle is where you stand.',
        lede: 'Human height is around the metre scale. It is not the centre of nature—only the scale from which our intuitions begin.',
        facts: [
          ['≈ 1.7 m', 'illustrative adult height', 'People are wonderfully variable'],
          ['1 second', 'a resting heartbeat scale', 'Body size also shapes rhythms'],
          ['20 powers', 'from the probed edge', 'A rough logarithmic climb to us'],
        ],
        note: 'We call some things tiny and others huge because this is our viewing platform. Change the observer and the adjectives change.',
        term: ['metre', 'MEE-ter', 'the SI base unit of length'],
        narration: 'Here is the scale your intuition calls normal: roughly a metre or two, the span of a person. It is tempting to call this the middle, but nature has no obligation to centre itself on us. Human scale is simply our balcony. From here, a virus is invisible, sand is small, a whale is enormous, and the stars look like points. We build doors, tools, music, and stories around bodies of this size. The journey has already crossed about twenty powers of ten to reach us. Now turn around. The outward half begins under the same sky.',
      },
      ja: {
        chapter: '09 · あなたはここ',
        title: '真ん中とは、立っている場所。',
        lede: '人の身長は、だいたいメートルのスケール。自然の中心ではなく、私たちの直感が始まる場所です。',
        facts: [
          ['約1.7m', '大人の身長の一例', '人の体格には豊かな個人差がある'],
          ['約1秒', '安静時の鼓動の間隔', '体の大きさは時間の感覚にも関わる'],
          ['約20桁', '観測の最前線から', '対数の階段を上って人に届く'],
        ],
        note: '小さい、大きいという言葉は、ここが観測台だから生まれます。観測者が変われば、形容詞も変わります。',
        term: ['メートル', 'めーとる', '長さを表す国際単位系の基本単位'],
        narration: 'ここが、直感にとっての普通の大きさです。およそ1メートルから2メートル、人ひとりの広がり。真ん中と呼びたくなりますが、自然が人を中心に並ぶ理由はありません。人のスケールは、私たちの観測台にすぎないのです。ここから見ると、ウイルスは見えず、砂は小さく、クジラは巨大で、星は点になります。私たちは、この大きさの体に合わせて、扉、道具、音楽、物語を作ります。最前線からここまで、すでに約二十桁。では振り返りましょう。同じ空の下で、外へ向かう旅が始まります。',
      },
    },
    {
      id: 'blue-whale',
      kind: 'story',
      image: 'assets/images/10-blue-whale.webp',
      tone: 'ocean',
      layout: 'right',
      focal: '50% 50%',
      order: 1.5,
      scale: 'up to ≈ 33.5 m',
      en: {
        chapter: '10 · A LIVING GIANT',
        title: 'Thirty metres can still be alive.',
        lede: 'Antarctic blue whales can reach about thirty-three metres. Their immense bodies are sustained by gatherings of tiny krill.',
        facts: [
          ['up to 110 ft', 'reported length', 'About 33.5 metres in Antarctic animals'],
          ['330,000+ lb', 'reported mass', 'More than 149 metric tonnes'],
          ['krill', 'small prey', 'A giant life depends on countless small lives'],
        ],
        note: 'Maximum records are not an average. Population, sex, age, and measurement method all matter.',
        term: ['megafauna', 'MEG-uh-faw-nuh', 'the largest animals in an ecosystem'],
        narration: 'Thirty metres is not just a building dimension. It can breathe. The blue whale is the largest animal known to live on Earth, and Antarctic individuals can reach around thirty-three metres. Yet this body is assembled cell by cell and nourished largely by krill only a few centimetres long. A feeding whale turns ocean water into a moving calculation: accelerate, open the pleated mouth, engulf tonnes of water, then strain the prey through baleen. Immense scale does not escape the small. It gathers the small, coordinates it, and makes a heartbeat that can travel through the sea.',
      },
      ja: {
        chapter: '10 · 生きている巨体',
        title: '三十メートルが、呼吸している。',
        lede: '南極海のシロナガスクジラは、約33メートルに達することがあります。巨体を支えるのは、小さなオキアミの群れです。',
        facts: [
          ['最大110フィート', '報告された体長', '南極海では約33.5メートル'],
          ['33万ポンド超', '報告された体重', '約149トンをこえる'],
          ['オキアミ', '小さな獲物', '巨大な命が無数の小さな命に支えられる'],
        ],
        note: '最大記録は平均ではありません。個体群、性別、年齢、測り方によって値は変わります。',
        term: ['メガファウナ', 'めがふぁうな', '生態系の中で、とても大きな動物たち'],
        narration: '30メートルは、建物の寸法だけではありません。呼吸することもできます。シロナガスクジラは、地球で知られている最大の動物です。南極海の個体は、およそ33メートルに達します。それでも、この体は一つ一つの細胞からでき、主に、数センチほどのオキアミに養われます。食事をするクジラは、海水の中を動く計算のようです。加速し、ひだのある口を大きく開き、大量の水を取りこみ、ひげ板で獲物だけをこし取ります。巨大になっても、小さな世界から離れるわけではありません。小さなものを集め、協調させ、海を伝わる鼓動に変えるのです。',
      },
    },
    {
      id: 'city',
      kind: 'story',
      image: 'assets/images/11-city.webp',
      tone: 'city',
      layout: 'left',
      focal: '50% 54%',
      order: 4,
      scale: '≈ 10 km view',
      en: {
        chapter: '11 · THE COLLECTIVE BODY',
        title: 'A city is distance made social.',
        lede: 'Across ten kilometres, footsteps become transit lines, rooms become neighbourhoods, and millions of choices leave a pattern.',
        facts: [
          ['≈ 10 km', 'this imagined view', 'A representative city-scale span'],
          ['networks', 'hidden anatomy', 'Water, power, food, data, and transport'],
          ['many scales', 'one place', 'Hands repair streets; satellites help map them'],
        ],
        note: 'The city is fictional so no changing population or boundary is presented as a universal standard.',
        term: ['kilo', 'KEE-loh', 'the SI prefix for 10³'],
        narration: 'At ten kilometres, no single person can take in every detail from the ground. A city becomes a pattern: blocks, bridges, parks, roofs, and rivers. Listen closer and the pattern is made of daily rituals—doors opening, kettles boiling, trains braking, shoes crossing pavement. Water pipes, power lines, food routes, and data links form an anatomy that no one sees at once. Unlike a whale, a city has no skin and no agreed edge. It grows through decisions. Scale becomes social: the distance between home and school, market and kitchen, neighbour and neighbour.',
      },
      ja: {
        chapter: '11 · 集合する体',
        title: '都市は、距離を社会に変える。',
        lede: '10キロメートルの広がりでは、足音が交通網へ、部屋が街区へ変わり、無数の選択が模様を残します。',
        facts: [
          ['約10km', 'この架空の眺め', '都市スケールを示す代表的な範囲'],
          ['ネットワーク', '隠れた体の仕組み', '水、電気、食べ物、情報、交通'],
          ['多くの尺度', 'ひとつの場所', '手で道を直し、衛星で地図を作る'],
        ],
        note: '人口や境界の変化を普遍的な基準にしないよう、都市は特定の実在都市ではなく創作しました。',
        term: ['キロ', 'きろ', '10の3乗を表す接頭語'],
        narration: '10キロメートルになると、地上に立つ一人の目では、すべてを同時に見渡せません。都市は、街区、橋、公園、屋根、川が作る模様になります。けれど耳を近づければ、その模様は毎日の儀式でできています。扉が開き、やかんが沸き、電車が止まり、靴が歩道を渡る。水道、電力、食べ物の経路、情報網は、誰にも一度には見えない体の仕組みです。クジラと違い、都市には皮膚も、全員が同意する縁もありません。選択の積み重ねで育ちます。家と学校、市場と台所、隣人と隣人。その距離が社会を作るのです。',
      },
    },
    {
      id: 'earth',
      kind: 'story',
      image: 'assets/images/12-earth.webp',
      tone: 'planet',
      layout: 'right',
      focal: '50% 50%',
      order: 7.1,
      scale: '12,756 km equator',
      en: {
        chapter: '12 · THE WHOLE WEATHER',
        title: 'A world fits in one view.',
        lede: 'Earth spans 12,756 kilometres at the equator. From far enough away, every border disappears beneath one moving atmosphere.',
        facts: [
          ['12,756 km', 'equatorial diameter', 'Slightly wider than pole to pole'],
          ['≈ 30 km', 'average continental crust', 'A very thin skin on this scale'],
          ['1 AU', 'from the Sun', 'About 150 million kilometres on average'],
        ],
        note: 'Clouds make every portrait temporary. This generated Earth is plausible, not a record of a particular date.',
        term: ['planet', 'PLAN-it', 'a world orbiting a star; definitions matter'],
        narration: 'At twelve thousand seven hundred fifty-six kilometres across the equator, Earth finally fits into one frame. Mountains that filled a horizon barely texture its surface. The solid continental crust averages only about thirty kilometres thick—a fragile skin over mantle and core. Above it, the atmosphere has no visible political borders. Air and ocean move heat around the globe; weather links places that feel far apart. This view is powerful, but remember the trick: we had to leave every street, face, cell, and molecule behind to see the whole. A complete picture always trades detail for connection.',
      },
      ja: {
        chapter: '12 · 天気をまるごと',
        title: 'ひとつの世界が、一枚に収まる。',
        lede: '地球の赤道直径は1万2756キロメートル。十分に離れると、すべての国境が、動く大気の下に消えます。',
        facts: [
          ['12,756km', '赤道直径', '極から極より、わずかに広い'],
          ['平均約30km', '大陸地殻', 'この尺度では、とても薄い皮'],
          ['1天文単位', '太陽まで', '平均およそ1億5千万キロメートル'],
        ],
        note: '雲が動くため、地球の肖像はいつも一時的です。この画像はもっともらしい表現で、特定の日の記録ではありません。',
        term: ['プラネット', 'ぷらねっと', '恒星を回る世界。定義には条件がある'],
        narration: '赤道で直径1万2756キロメートル。ここで地球が、ようやく一つの画面に収まります。地平線を埋めた山々も、表面の小さな手触りにしか見えません。大陸地殻の平均的な厚さは、およそ30キロメートル。マントルと核を包む、薄い皮です。その上を覆う大気には、政治的な境界線が見えません。空気と海が熱を運び、遠く感じる場所どうしを天気が結びます。ただし、この全体像には仕掛けがあります。街路も、顔も、細胞も、分子も置き去りにしなければ、全体は見えません。完全な眺めはいつも、細部と引き換えに、つながりを見せるのです。',
      },
    },
    {
      id: 'earth-moon',
      kind: 'quiz',
      image: 'assets/images/13-earth-moon.webp',
      tone: 'space',
      layout: 'left',
      focal: '50% 50%',
      order: 8.6,
      scale: '384,400 km average',
      en: {
        chapter: '13 · THE FIRST GREAT GAP',
        title: 'The Moon is mostly a distance.',
        lede: 'Earth and Moon average 384,400 kilometres apart. Most classroom pictures shrink the separation so both bodies remain visible.',
        facts: [
          ['384,400 km', 'average separation', 'Measured centre to centre'],
          ['3,475 km', 'Moon diameter', 'A little over one quarter of Earth’s'],
          ['≈ 1.3 seconds', 'light travel time', 'One way, at the average distance'],
        ],
        note: 'The orbit is elliptical, so the distance changes. “Average” is essential, not decorative.',
        term: ['lunar', 'LOO-ner', 'relating to the Moon'],
        narration: 'The Moon looks close because it shares our sky, but its defining feature is the gap. On average, centre to centre, it is three hundred eighty-four thousand four hundred kilometres from Earth. Light crosses that space in about one point three seconds. Human voices sent through radio therefore return with a noticeable pause. Most diagrams pull Earth and Moon together; otherwise both become tiny on the page. Here, the darkness is the subject. Space is not the backdrop between objects. At cosmic scales, the interval often occupies almost everything.',
        quiz: {
          question: 'Roughly how many Earths could fit side by side in the average Earth–Moon gap?',
          options: ['3', '30', '300'],
          answer: 1,
          explanation: 'The average gap is about thirty Earth diameters. It varies because the Moon follows an elliptical orbit.',
        },
      },
      ja: {
        chapter: '13 · 最初の大きな間',
        title: '月の大部分は、距離である。',
        lede: '地球と月は、平均38万4400キロメートル離れています。教科書の図では、両方を見せるため距離を縮めることがよくあります。',
        facts: [
          ['384,400km', '平均距離', '中心から中心まで'],
          ['3,475km', '月の直径', '地球の四分の一より少し大きい'],
          ['約1.3秒', '光の移動時間', '平均距離を片道で'],
        ],
        note: '軌道は楕円なので、距離は変化します。「平均」は飾りではなく、大切な条件です。',
        term: ['ルナー', 'るなー', '月に関係する、という意味'],
        narration: '月は同じ空に見えるので、近く感じられます。けれど月を特徴づけるのは、その間です。中心から中心まで、平均38万4400キロメートル。光でも、片道およそ1.3秒かかります。電波で送った人の声が戻るとき、無視できない間が生まれます。多くの図は、地球と月を近づけて描きます。本当の距離を保つと、両方が紙の上で小さくなりすぎるからです。ここでは暗闇そのものが主役。宇宙は、物と物の後ろにある背景ではありません。大きなスケールでは、間隔がほとんどすべてを占めるのです。',
        quiz: {
          question: '地球と月の平均的な間には、地球が横におよそ何個並ぶでしょう？',
          options: ['3個', '30個', '300個'],
          answer: 1,
          explanation: '平均的な間は、地球の直径およそ三十個ぶんです。月の軌道は楕円なので、実際の距離は変化します。',
        },
      },
    },
    {
      id: 'sun',
      kind: 'story',
      image: 'assets/images/14-sun.webp',
      tone: 'solar',
      layout: 'right',
      focal: '48% 50%',
      order: 9.14,
      scale: '≈ 1.39 million km',
      en: {
        chapter: '14 · OUR ORDINARY STAR',
        title: 'A million kilometres of weather.',
        lede: 'The Sun is about 1.4 million kilometres across. Its visible surface seethes as energy works outward from the core.',
        facts: [
          ['≈ 1.39 million km', 'diameter', 'About 109 Earths across'],
          ['≈ 4.5 billion years', 'age', 'Roughly halfway through its stable lifetime'],
          ['8 min 20 s', 'sunlight to Earth', 'Across one astronomical unit'],
        ],
        note: 'Color and contrast are enhanced to reveal texture. Never look directly at the Sun without proper certified protection.',
        term: ['stellar', 'STEL-er', 'relating to a star'],
        narration: 'The Sun is about one point four million kilometres wide—roughly one hundred nine Earths across. What looks like a smooth disk from the ground is a shifting surface of hot plasma. Granules rise and sink. Magnetic fields twist. Prominences arc beyond the limb. Deep inside, fusion turns hydrogen into helium and releases energy that may wander for ages before escaping as light. Once free, that light needs only about eight minutes and twenty seconds to reach Earth. Our days, weather, food, and fossil fuels all borrow from the output of this ordinary, indispensable star.',
      },
      ja: {
        chapter: '14 · 私たちの普通の恒星',
        title: '百万キロメートルの天気。',
        lede: '太陽の直径は、およそ140万キロメートル。核から外へ進むエネルギーが、見える表面を煮え立たせます。',
        facts: [
          ['約139万km', '直径', '地球およそ109個ぶん'],
          ['約45億年', '年齢', '安定した一生のおよそ半ば'],
          ['8分20秒', '太陽光が地球まで', '1天文単位を進む'],
        ],
        note: '模様を見せるため、色とコントラストを強めています。認証された保護具なしで太陽を直接見ないでください。',
        term: ['ステラー', 'すてらー', '恒星に関係する、という意味'],
        narration: '太陽の直径は、およそ140万キロメートル。地球が横に約109個並びます。地上から滑らかな円盤に見える表面は、熱いプラズマが動き続ける場所です。粒状の模様が上がって沈み、磁場がねじれ、プロミネンスが縁の外へ弧を描きます。深い内部では、核融合が水素をヘリウムへ変えます。生まれたエネルギーは、長い時間をかけて外へ進み、光として飛び出すと、わずか8分20秒ほどで地球へ届きます。昼も、天気も、食べ物も、化石燃料も、この普通で、欠かせない恒星の出力を借りています。',
      },
    },
    {
      id: 'heliosphere',
      kind: 'story',
      image: 'assets/images/15-heliosphere.webp',
      tone: 'solar',
      layout: 'left',
      focal: '50% 50%',
      order: 13.3,
      scale: '≈ 120 AU to boundary',
      en: {
        chapter: '15 · THE SUN’S BREATH',
        title: 'A star is larger than its light.',
        lede: 'The solar wind inflates the heliosphere. Voyager 1 crossed its outer plasma boundary at about 122 astronomical units.',
        facts: [
          ['≈ 120 AU', 'heliopause crossing scale', 'The boundary shifts with conditions'],
          ['2012', 'Voyager 1 crossing', 'First spacecraft in interstellar plasma'],
          ['2018', 'Voyager 2 crossing', 'A second path through a different region'],
        ],
        note: 'The heliosphere is dynamic and asymmetric. Its global shape remains an active research subject; the visible glow is interpretive.',
        term: ['heliosphere', 'HEE-lee-oh-sfeer', 'the Sun-shaped bubble in surrounding space'],
        narration: 'The Sun does not stop at its glowing surface. It exhales a solar wind of charged particles that inflates a vast, changing region called the heliosphere. Far beyond the planets, that wind slows and meets interstellar material at the heliopause. Voyager One crossed into interstellar plasma in 2012 at roughly one hundred twenty-two times the Earth–Sun distance; Voyager Two followed in 2018 along another route. Calling this the edge of the solar system is convenient, not final. The Sun’s gravity reaches farther, and the boundary itself breathes with solar activity and the interstellar environment.',
      },
      ja: {
        chapter: '15 · 太陽の呼吸',
        title: '恒星は、光る表面より大きい。',
        lede: '太陽風が、太陽圏という領域をふくらませます。ボイジャー1号は、約122天文単位でプラズマの境界を越えました。',
        facts: [
          ['約120天文単位', 'ヘリオポーズの尺度', '条件によって境界は動く'],
          ['2012年', 'ボイジャー1号', '星間プラズマへ入った最初の探査機'],
          ['2018年', 'ボイジャー2号', '別の方向から二度目の通過'],
        ],
        note: '太陽圏は動的で左右非対称です。全体の形は研究が続いており、見える光は創作表現です。',
        term: ['ヘリオスフィア', 'へりおすふぃあ', '周囲の宇宙に広がる、太陽が作った領域'],
        narration: '太陽は、光る表面で終わりません。電気を帯びた粒子の風を吐き出し、太陽圏、ヘリオスフィアと呼ばれる、巨大で変化する領域をふくらませます。惑星よりはるか外側で、太陽風は遅くなり、星間物質と出会います。その境界がヘリオポーズです。ボイジャー1号は2012年、地球と太陽の距離のおよそ122倍で星間プラズマへ入りました。2号も2018年、別の方向から続きました。ここを太陽系の端と呼ぶのは便利ですが、最終的な答えではありません。太陽の重力はさらに遠くまで届き、境界そのものも太陽活動と星間環境に合わせて呼吸しています。',
      },
    },
    {
      id: 'star-gap',
      kind: 'story',
      image: 'assets/images/16-star-gap.webp',
      tone: 'space',
      layout: 'right',
      focal: '50% 50%',
      order: 16.6,
      scale: '4.25 light-years',
      en: {
        chapter: '16 · BETWEEN STARS',
        title: 'The next light is four years away.',
        lede: 'Proxima Centauri, the nearest star beyond the Sun, is about 4.25 light-years away. Even our enormous heliosphere becomes a speck.',
        facts: [
          ['4.25 ly', 'to Proxima Centauri', 'About 40 trillion kilometres'],
          ['9.46 trillion km', 'one light-year', 'A distance, not a duration'],
          ['mostly', 'the gap', 'Thin gas, dust, fields, and cosmic rays—not nothing'],
        ],
        note: 'Both stars are enlarged until visible. At a single honest scale, they would be far smaller than pixels on this screen.',
        term: ['light-year', 'LIGHT-yeer', 'the distance light travels in one year'],
        narration: 'Now the numbers force a new unit. A light-year is distance: about nine point four six trillion kilometres. Proxima Centauri, the closest star beyond our Sun, is roughly four point two five light-years away. Light leaving there today will reach us more than four years from now. On a model where the Sun is a grain of sand, the next star would still be many kilometres away. Interstellar space is not perfectly empty; sparse gas, dust, magnetic fields, and cosmic rays pass through it. But compared with everything we have seen, the defining object here is absence measured across years of light.',
      },
      ja: {
        chapter: '16 · 恒星と恒星の間',
        title: '次の光まで、四年。',
        lede: '太陽の次に近い恒星、プロキシマ・ケンタウリまでは約4.25光年。巨大な太陽圏さえ、点になります。',
        facts: [
          ['4.25光年', 'プロキシマ・ケンタウリまで', 'およそ40兆キロメートル'],
          ['9兆4600億km', '1光年', '時間ではなく、距離'],
          ['ほとんど', '間が占めるもの', '薄いガス、ちり、場、宇宙線があり、完全な無ではない'],
        ],
        note: '二つの恒星は、見えるよう大きく描いています。同じ正確な縮尺なら、この画面の一画素よりはるかに小さくなります。',
        term: ['光年', 'こうねん', '光が一年で進む距離'],
        narration: 'ここで数値は、新しい単位を必要とします。光年は時間ではなく距離。1光年は、およそ9兆4600億キロメートルです。太陽の次に近い恒星、プロキシマ・ケンタウリまでは約4.25光年。今日そこを出た光は、四年以上かけて私たちに届きます。太陽を砂粒に縮める模型でも、次の恒星は何キロメートルも先です。星間空間は完全な空っぽではありません。薄いガス、ちり、磁場、宇宙線が通ります。それでも、これまで見てきた物に比べると、ここで主役になるのは、光の年月で測る不在そのものです。',
      },
    },
    {
      id: 'milky-way',
      kind: 'story',
      image: 'assets/images/17-milky-way.webp',
      tone: 'galaxy',
      layout: 'left',
      focal: '50% 50%',
      order: 21,
      scale: '≈ 100,000 light-years',
      en: {
        chapter: '17 · OUR GALAXY',
        title: 'A hundred billion suns become a shape.',
        lede: 'The Milky Way is a barred spiral roughly one hundred thousand light-years across. We map it from inside, star by star.',
        facts: [
          ['≈ 100,000 ly', 'disk diameter', 'The faint halo extends farther'],
          ['100–400 billion', 'estimated stars', 'Counting from inside is difficult'],
          ['inside', 'our viewpoint', 'No spacecraft has photographed the whole galaxy'],
        ],
        note: 'This is a data-informed artist’s impression. Gaia has revised details of the bar and arms; galactic maps remain works in progress.',
        term: ['galaxy', 'GAL-uk-see', 'stars, gas, dust, and dark matter bound by gravity'],
        narration: 'At one hundred thousand light-years, stars stop being isolated points and become anatomy. The Milky Way is a barred spiral galaxy with dust lanes, star-forming regions, a central bulge, and a faint halo extending beyond the bright disk. Estimates place between one hundred and four hundred billion stars here. We cannot step outside to take its portrait. Instead, missions such as Gaia measure stars from within, using position and motion to infer the larger shape. Every unaided star in Earth’s night sky belongs to this one galaxy. The pale band overhead is our home seen edge-on, from inside the crowd.',
      },
      ja: {
        chapter: '17 · 私たちの銀河',
        title: '千億の太陽が、ひとつの形になる。',
        lede: '天の川銀河は、直径およそ10万光年の棒渦巻銀河です。私たちは内側から、星を一つずつ測って地図を作ります。',
        facts: [
          ['約10万光年', '円盤の直径', '淡いハローはさらに外へ広がる'],
          ['1千億〜4千億', '推定される恒星', '内側から数えるのは難しい'],
          ['内側', '私たちの視点', '銀河全体を宇宙船で撮影した写真はない'],
        ],
        note: 'これは観測データに基づく創作図です。ガイアは棒や腕の理解を更新し、銀河地図は今も作り直されています。',
        term: ['ギャラクシー', 'ぎゃらくしー', '重力で結ばれた恒星、ガス、ちり、暗黒物質'],
        narration: '10万光年の尺度では、恒星は孤立した点ではなく、体の構造になります。天の川銀河は、ちりの帯、星が生まれる領域、中央のふくらみ、明るい円盤の外まで続く淡いハローを持つ、棒渦巻銀河です。恒星は、千億から四千億個と推定されています。私たちは外へ出て、全体写真を撮ることができません。代わりにガイアのような探査機が、内側から星の位置と動きを測り、大きな形を推理します。地球から肉眼で見える星は、すべてこの銀河の仲間。夜空の淡い帯は、星の群れの内側から、私たちの家を横向きに見た姿です。',
      },
    },
    {
      id: 'ic-1101',
      kind: 'story',
      image: 'assets/images/18-ic1101.webp',
      tone: 'galaxy',
      layout: 'right',
      focal: '50% 50%',
      order: 22.6,
      scale: 'up to ≈ 4 million ly',
      en: {
        chapter: '18 · A GIANT WITHOUT A SHARP EDGE',
        title: 'Largest depends on where you stop counting.',
        lede: 'NASA describes the giant elliptical galaxy IC 1101 as spanning as much as four million light-years. The cautious words matter.',
        facts: [
          ['up to ≈ 4 million ly', 'reported span', 'Its faint outer light makes the edge definition-sensitive'],
          ['elliptical', 'galaxy type', 'A broad golden stellar population, not spiral arms'],
          ['cluster centre', 'environment', 'Its history is tied to many surrounding galaxies'],
        ],
        note: 'This is not presented as an uncontested “largest galaxy.” Surveys, wavelengths, distance estimates, and edge definitions can change rankings.',
        term: ['extent', 'ik-STENT', 'how far something is judged to spread'],
        narration: 'Our final outward stop is deliberately cautious. The giant elliptical galaxy I C eleven-oh-one has been described by NASA as spanning as much as four million light-years. But a galaxy is not a coin with a machined rim. Its light fades into a halo; stars mingle with the cluster around it; measurements depend on wavelength, distance, and the brightness threshold chosen as an edge. So “largest” is not a permanent trophy. The memorable idea is better: a galaxy can spread millions of light-years while refusing to tell us exactly where it ends. At the grandest scales, precision includes uncertainty.',
      },
      ja: {
        chapter: '18 · 鋭い縁のない巨人',
        title: '最大は、どこまで数えるかで変わる。',
        lede: 'ナサは巨大楕円銀河アイシー千百一を、最大約400万光年に広がると説明します。「最大約」という慎重な言葉が大切です。',
        facts: [
          ['最大約400万光年', '報告される広がり', '外側の淡い光により、縁の定義で変わる'],
          ['楕円銀河', '銀河の種類', '渦巻腕ではなく、金色に見える広い恒星集団'],
          ['銀河団の中心', '周囲の環境', '近くの多くの銀河と歴史を共有する'],
        ],
        note: '議論の余地がない「最大の銀河」とは紹介しません。観測、波長、距離推定、縁の定義によって順位は変わります。',
        term: ['エクステント', 'えくすてんと', 'どこまで広がっていると判断するか'],
        narration: '外へ向かう最後の場所では、あえて慎重になります。巨大楕円銀河、アイシー千百一は、ナサによって最大約400万光年に広がると説明されています。けれど銀河は、機械で切った硬貨のような縁を持ちません。光はハローへ薄く消え、恒星は周囲の銀河団と混じります。測定結果は、使う波長、距離の推定、そして、どの明るさを縁と決めるかで変わります。ですから最大という言葉は、永久のトロフィーではありません。もっと心に残る考えがあります。銀河は数百万光年に広がりながら、どこで終わるのかを、はっきり教えてくれない。最大のスケールでは、不確かさを示すことも精密さの一部なのです。',
      },
    },
    {
      id: 'finale',
      kind: 'finale',
      image: 'assets/images/09-human.webp',
      tone: 'finale',
      layout: 'left',
      focal: '50% 52%',
      order: 0.23,
      scale: 'you are here',
      en: {
        chapter: '19 · RETURN TO ONE',
        title: 'Every scale was here all along.',
        lede: 'The galaxy, the person, the cell, the proton: not a ladder of importance, but nested ways for nature to organize matter and distance.',
        facts: [
          ['42+', 'powers of ten crossed', 'From the probed quark scale to a giant galaxy estimate'],
          ['19', 'chapters', 'One route through an expandable story'],
          ['1', 'place to return', 'The scale of your next breath'],
        ],
        note: 'Look up, look down, or hold out your hand. The long zoom does not end; it changes which relationships you notice.',
        term: ['perspective', 'per-SPEK-tiv', 'a view shaped by where you stand'],
        narration: 'Return to the figure under the stars. Nothing here is merely in the middle. Your body contains cells; cells arrange molecules; molecules are built from atoms; atoms carry protons; and those protons seethe with fields. Above you, Earth moves inside the Sun’s breath, one star crosses the Milky Way, and our galaxy shares space with giants whose edges fade into uncertainty. We crossed more than forty-two powers of ten, but size never became importance. The smallest shapes the largest, and the largest gives the smallest a place. Take one breath. You are not outside the scale of things. You are one of its temporary, wondering arrangements.',
      },
      ja: {
        chapter: '19 · 1へ帰る',
        title: 'すべてのスケールは、最初からここにあった。',
        lede: '銀河、人、細胞、陽子。重要さの順位ではなく、物質と距離を自然が組み立てる、入れ子の方法です。',
        facts: [
          ['42桁以上', '旅した10の階段', '調べたクォーク尺度から巨大銀河の推定まで'],
          ['19章', 'この物語', 'あとから増やせる、ひとつの道筋'],
          ['1か所', '帰る場所', '次の呼吸がある大きさ'],
        ],
        note: '空を見る。足元を見る。手を伸ばす。はてしないズームは終わらず、気づく関係が変わります。',
        term: ['パースペクティブ', 'ぱーすぺくてぃぶ', '立つ場所によって形づくられる見方'],
        narration: '星の下に立つ人へ戻りましょう。ここは、ただの真ん中ではありません。体には細胞があり、細胞は分子を並べ、分子は原子からでき、原子は陽子を持ち、その陽子では量子場が動いています。頭上では、地球が太陽の呼吸の中を進み、一つの恒星が天の川銀河をめぐり、その銀河は、縁が不確かさへ溶ける巨人たちと宇宙を共有します。四十二桁以上を旅しても、大きさが重要さの順位になることはありませんでした。小さなものが大きなものを形づくり、大きなものが小さなものに居場所を与えます。一度、息をしてください。あなたはスケールの外にいるのではありません。驚くことのできる、一時的な組み合わせとして、その中にいるのです。',
      },
    },
  ];

  window.SCALE_STORY = {
    meta: {
      id: 'small-large',
      sceneCount: scenes.length,
      quizCount: scenes.filter((scene) => scene.kind === 'quiz').length,
      openingImage: 'assets/images/09-human.webp',
      audioBase: 'assets/audio',
      languages: ['en', 'ja'],
      sourceChecked: '2026-08-19',
    },
    ui,
    sources,
    scenes,
  };
})();
