'use strict';

const GALAXY_CENTER_STORY = {
  meta: {
    title: 'Journey to the center of our galaxy',
    shortTitle: 'GALACTIC CENTER',
    chapters: 8,
    quizzes: 3,
    duration: '10–15',
    researchChecked: '2026-07-29',
    voice: 'en_US-lessac-medium',
  },

  ui: {
    documentLanguage: 'en',
    pageTitle: 'Journey to the center of our galaxy',
    metaDescription: 'A cinematic, narrated journey for young explorers from our Solar System to the black hole at the center of the Milky Way.',
    skipLink: 'Skip to the current chapter',
    backToGames: 'Back to games',
    brandLabel: 'Journey to the center of our galaxy',
    brandSubtitle: 'A MILKY WAY EXPEDITION',
    infoOpen: 'Open controls, media notes, and research sources',
    panelControl: 'Story',
    panelHide: 'Hide the story panel',
    panelShow: 'Show the story panel',
    panelQuizLocked: 'The story panel stays open until this discovery is answered',
    panelShownAnnouncement: 'Story panel shown.',
    panelHiddenAnnouncement: 'Story panel hidden. The artwork, narration, transcript, and journey controls remain available.',
    captionsControl: 'Transcript',
    captionsShow: 'Show narration transcript',
    captionsHide: 'Hide narration transcript',
    captionsShownAnnouncement: 'Narration transcript shown.',
    captionsHiddenAnnouncement: 'Narration transcript hidden.',
    soundControl: 'Sound',
    soundOff: 'Turn narration off',
    soundOn: 'Turn narration on',
    soundOnAnnouncement: 'Narration turned on.',
    soundOffAnnouncement: 'Narration turned off.',
    storyStageLabel: 'A journey through the Milky Way',
    introOverline: 'OUR GALAXY IS CALLING',
    introKicker: 'FROM THE ORION SPUR TO SAGITTARIUS A*',
    introLede: 'Follow starlight past nearby suns, newborn worlds, a stellar lighthouse, and the dusty heart of the Milky Way.',
    introStatsLabel: 'Experience overview',
    chapterStatLabel: 'chapters',
    durationStatLabel: 'minutes',
    quizStatLabel: 'discoveries',
    startHint: 'English narration begins after you press start',
    startLabel: 'Launch the journey',
    headphoneNote: 'Headphones welcome · sound can be changed anytime',
    introCoordinatePrimary: 'HOME SIGNAL · ORION SPUR',
    introCoordinateSecondary: 'DESTINATION · GALACTIC CENTER',
    previous: 'Back',
    previousAria: 'Previous scene',
    next: 'Continue inward',
    nextAria: 'Next scene',
    answerToContinue: 'Choose an answer',
    answerToContinueAria: 'Choose an answer before continuing',
    restartLabel: 'Begin again',
    restartAria: 'Restart the journey from our Solar System',
    navigationLabel: 'Journey navigation',
    scenesLabel: '{count} scenes',
    progressSceneAria: 'Go to scene {number}, {title}',
    sceneAnnouncement: 'Scene {number} of {count}. {title}',
    narrationReady: 'Narration ready',
    narrationLoading: 'Loading narration…',
    narrationPlaying: 'English narration playing',
    narrationPaused: 'Narration paused',
    narrationComplete: 'Narration complete',
    narrationMuted: 'Narration is off',
    narrationError: 'Audio unavailable · transcript ready',
    narrationPlayPrompt: 'Press replay to hear this scene',
    narrationReplay: 'Replay this scene’s narration',
    narrationProgress: 'Narration progress',
    transcriptHeading: 'Narration transcript',
    transcriptAria: 'Narration transcript',
    transcriptClose: 'Close transcript',
    transcriptLoading: 'Loading transcript…',
    transcriptError: 'The transcript could not be loaded. The shorter chapter text remains available.',
    signalWord: 'SIGNAL WORD',
    quizGroup: 'Answer choices: {question}',
    quizOption: 'Choice {number}: {label}',
    quizCorrectLead: 'Bright thinking!',
    quizDiscoverLead: 'A new discovery!',
    quizCorrectAnnouncement: 'That is right. {explanation}',
    quizDiscoverAnnouncement: 'Here is the discovery. {explanation}',
    finaleVisitedLabel: 'Discoveries visited',
    finaleComplete: 'All three curious pauses explored',
    finaleIncomplete: 'Every discovery remains open on the route',
    restart: 'Travel again ↺',
    infoOverline: 'MISSION NOTES',
    infoTitle: 'About this journey',
    infoClose: 'Close',
    controlsHeading: 'Controls',
    controlsCopyOne: 'Use the arrows below, the route points, or the ← and → keys to move. Number keys 1–3 answer a discovery.',
    controlsCopyTwo: 'Press R to replay narration, C for the transcript, M for sound, and P for the story panel. Escape closes the transcript or this dialog.',
    controlsCopyThree: 'Hiding the panel leaves navigation, sound, transcript, help, and progress available. Discoveries open the panel automatically and restore your preference on the next scene.',
    mediaHeading: 'Media & accessibility',
    mediaCopyOne: 'Every scene image was generated for this experience. They are cinematic artist interpretations informed by current observations—not photographs, cockpit views, or scale diagrams. Invisible wavelengths are translated into visible color.',
    mediaCopyTwo: 'English narration was made locally with the Piper Lessac voice. Browser-ready MP3 files, exact transcripts, and WAV masters are stored with the app; no media service is contacted at runtime.',
    mediaCopyThree: 'Decorative motion follows your reduced-motion setting. Narration starts only after the launch button, and the transcript opens independently of the story panel.',
    sourcesHeading: 'Research sources',
    sourcesIntro: 'Facts were checked against these NASA, ESA, and ESO resources on July 29, 2026. Distances and galaxy dimensions are rounded for young listeners, and scientific models continue to improve.',
  },

  sources: [
    {
      url: 'https://science.nasa.gov/universe/galaxies/',
      title: 'NASA Science · Galaxies and our Milky Way',
    },
    {
      url: 'https://science.nasa.gov/resource/the-milky-way-galaxy/',
      title: 'NASA Science · The Milky Way Galaxy and the Orion Spur',
    },
    {
      url: 'https://science.nasa.gov/solar-system/solar-system-facts/',
      title: 'NASA Science · Solar System facts and the galactic year',
    },
    {
      url: 'https://www.esa.int/Science_Exploration/Space_Science/Gaia/Gaia_factsheet',
      title: 'European Space Agency · Gaia mission factsheet',
    },
    {
      url: 'https://science.nasa.gov/universe/exoplanets/eso-discovers-earth-size-planet-in-habitable-zone-of-nearest-star/',
      title: 'NASA Exoplanets · Proxima Centauri b',
    },
    {
      url: 'https://science.nasa.gov/mission/webb/science-overview/science-explainers/what-is-webb-revealing-about-the-trappist-1-system/',
      title: 'NASA Webb · What we know about TRAPPIST-1',
    },
    {
      url: 'https://science.nasa.gov/exoplanets/whats-a-transit/',
      title: 'NASA Exoplanets · What is a transit?',
    },
    {
      url: 'https://science.nasa.gov/mission/hubble/science/science-highlights/finding-planetary-construction-zones/',
      title: 'NASA Hubble · Planetary construction zones in Orion',
    },
    {
      url: 'https://science.nasa.gov/asset/hubble/hubbles-sharpest-view-of-the-orion-nebula/',
      title: 'NASA Hubble · The Orion Nebula and the Trapezium',
    },
    {
      url: 'https://science.nasa.gov/3d-resources/crab-nebula/',
      title: 'NASA Science · Crab Nebula and its pulsar',
    },
    {
      url: 'https://www.eso.org/public/images/eso2603a/',
      title: 'European Southern Observatory · The Central Molecular Zone with ALMA',
    },
    {
      url: 'https://www.eso.org/public/images/eso0949f/',
      title: 'European Southern Observatory · Stars and dust near the Galactic Center',
    },
    {
      url: 'https://www.eso.org/public/news/eso2119/',
      title: 'European Southern Observatory · Stars orbiting Sagittarius A*',
    },
    {
      url: 'https://www.hq.eso.org/public/news/eso2208-eht-mw/',
      title: 'European Southern Observatory and EHT · First image of Sagittarius A*',
    },
  ],

  scenes: [
    {
      id: 'home-orion-spur',
      kind: 'story',
      image: 'assets/images/01-orion-spur-departure.webp',
      tone: 'home',
      layout: 'left',
      focal: { desktop: '54% 50%', mobile: '58% 50%' },
      waypoint: 'HOME SIGNAL',
      audio: '01-home-orion-spur',
      term: {
        name: 'galaxy',
        pronunciation: 'GAL-uk-see',
        meaning: 'a vast family of stars, gas, dust, and dark matter',
      },
      copy: {
        progress: 'Our galactic address',
        eyebrow: '01 · HOME ON THE MAP',
        location: 'ORION SPUR',
        title: 'We already live inside the adventure.',
        lede: 'The Milky Way is our enormous star city, and the Sun shines from a smaller lane called the Orion Spur.',
        facts: [
          { value: '100,000+', label: 'Light-years wide', caption: 'Even light needs an immense time to cross the disk' },
          { value: '≈26,000 ly', label: 'From the center', caption: 'Our Solar System sits well away from the crowded heart' },
          { value: 'Inside view', label: 'A difficult map', caption: 'We chart the galaxy while living inside it' },
        ],
        note: 'This is an imagined viewpoint based on many measurements. No spacecraft has flown above the Milky Way to photograph it.',
      },
    },
    {
      id: 'alpha-centauri',
      kind: 'story',
      image: 'assets/images/02-alpha-centauri.webp',
      tone: 'neighbor',
      layout: 'left',
      focal: { desktop: '64% 52%', mobile: '61% 52%' },
      waypoint: '4.24 LIGHT-YEARS',
      audio: '02-alpha-centauri',
      term: {
        name: 'star system',
        pronunciation: 'STAR SIS-tum',
        meaning: 'one or more stars and the worlds held by their gravity',
      },
      copy: {
        progress: 'The nearest star family',
        eyebrow: '02 · ALPHA CENTAURI',
        location: 'OUR STELLAR NEIGHBOR',
        title: 'Three stars, one surprising family.',
        lede: 'Two Sun-like stars dance together while little red Proxima Centauri travels much farther out.',
        facts: [
          { value: '4.24 ly', label: 'Nearest star', caption: 'Proxima is the closest known star beyond the Sun' },
          { value: 'A + B', label: 'Bright pair', caption: 'Alpha Centauri A and B orbit one another' },
          { value: '11 days', label: 'Proxima b year', caption: 'Its rocky planet circles close to a cool red star' },
        ],
        note: 'Proxima b is in the star’s habitable zone, but that does not promise life—or even an atmosphere. Its pictured surface is imagined.',
      },
    },
    {
      id: 'quiz-light-year',
      kind: 'quiz',
      image: 'assets/images/02-alpha-centauri.webp',
      tone: 'neighbor',
      layout: 'left',
      focal: { desktop: '64% 52%', mobile: '61% 52%' },
      waypoint: 'DISCOVERY 1 / 3',
      audio: '03-quiz-light-year',
      term: {
        name: 'light-year',
        pronunciation: 'LIGHT YEER',
        meaning: 'the distance light travels in one year',
      },
      copy: {
        progress: 'A ruler made of light',
        eyebrow: 'DISCOVERY 01 · COSMIC RULER',
        location: 'PAUSE AND PREDICT',
        title: 'What does a light-year measure?',
        lede: 'Space is so large that kilometers become clumsy. Astronomers let the fastest messenger in nature become their ruler.',
        question: 'A light-year is a measure of…',
        options: [
          'how old a star is',
          'how far light travels in one year',
          'how long a planet’s daytime lasts',
        ],
        answer: 1,
        explanation: 'A light-year is a distance: about 9.46 trillion kilometers. Proxima’s light takes about 4.24 years to reach us, so every look at it is also a look into the past.',
      },
    },
    {
      id: 'trappist-transits',
      kind: 'story',
      image: 'assets/images/03-trappist-1.webp',
      tone: 'ember',
      layout: 'right',
      focal: { desktop: '40% 52%', mobile: '43% 51%' },
      waypoint: '41 LIGHT-YEARS',
      audio: '04-trappist-transits',
      term: {
        name: 'transit',
        pronunciation: 'TRAN-zit',
        meaning: 'a planet crossing in front of its star from our viewpoint',
      },
      copy: {
        progress: 'Seven shadows',
        eyebrow: '03 · TRAPPIST-1',
        location: 'A COMPACT PLANET FAMILY',
        title: 'Seven worlds hide in tiny shadows.',
        lede: 'Around one cool red star, seven roughly Earth-size rocky planets complete amazingly short years.',
        facts: [
          { value: '7', label: 'Rocky worlds', caption: 'All are roughly Earth-size' },
          { value: '1.5–19 days', label: 'A whole year', caption: 'Each orbit is shorter than one Earth month' },
          { value: 'Tiny dip', label: 'How we found them', caption: 'A transit briefly dims the star' },
        ],
        note: 'All seven orbit closer to their star than Mercury orbits our Sun. We do not yet know whether any has oceans, breathable air, or life.',
      },
    },
    {
      id: 'orion-nursery',
      kind: 'story',
      image: 'assets/images/04-orion-nursery.webp',
      tone: 'nursery',
      layout: 'left',
      focal: { desktop: '66% 48%', mobile: '63% 48%' },
      waypoint: '≈1,500 LIGHT-YEARS',
      audio: '05-orion-nursery',
      term: {
        name: 'proplyd',
        pronunciation: 'PROH-plid',
        meaning: 'a planet-making disk around a young star',
      },
      copy: {
        progress: 'A stellar nursery',
        eyebrow: '04 · ORION NEBULA',
        location: 'STARS IN THE MAKING',
        title: 'Clouds can grow stars—and worlds.',
        lede: 'Gravity gathers cold gas and dust into warm baby stars. Leftover material flattens into disks where planets may begin.',
        facts: [
          { value: '≈1,500 ly', label: 'From Earth', caption: 'The nearest region forming massive stars' },
          { value: '4 bright stars', label: 'The Trapezium', caption: 'Young giants light and sculpt the cloud' },
          { value: 'Nearly 200', label: 'Disks imaged', caption: 'Hubble has resolved many Orion proplyds' },
        ],
        note: 'The colors combine clues from different wavelengths. They help us see heat, gas, dust, and starlight that our eyes alone would miss.',
      },
    },
    {
      id: 'spiral-crossing',
      kind: 'story',
      image: 'assets/images/05-spiral-crossing.webp',
      tone: 'disk',
      layout: 'left',
      focal: { desktop: '68% 48%', mobile: '61% 52%' },
      waypoint: 'ACROSS THE DISK',
      audio: '06-spiral-crossing',
      term: {
        name: 'galactic year',
        pronunciation: 'guh-LAK-tik YEER',
        meaning: 'one orbit of the Sun around the Milky Way',
      },
      copy: {
        progress: 'Crossing spiral country',
        eyebrow: '05 · THE MILKY WAY DISK',
        location: 'INWARD THROUGH THE ARMS',
        title: 'The spiral arms are busy neighborhoods.',
        lede: 'Gas and dust gather in the arms, where many new stars glow blue. Older stars crowd toward the central bar and bulge.',
        facts: [
          { value: '≈230 million', label: 'Years per lap', caption: 'One galactic year for the Sun' },
          { value: '2 billion', label: 'Gaia objects', caption: 'Only about one percent of the galaxy’s stars' },
          { value: '3 trillion+', label: 'Gaia observations', caption: 'Tiny motions build a changing 3D map' },
        ],
        note: 'Our map is still improving. Living inside the disk is like trying to map a forest while standing among its trees.',
      },
    },
    {
      id: 'quiz-galactic-year',
      kind: 'quiz',
      image: 'assets/images/05-spiral-crossing.webp',
      tone: 'disk',
      layout: 'left',
      focal: { desktop: '68% 48%', mobile: '61% 52%' },
      waypoint: 'DISCOVERY 2 / 3',
      audio: '07-quiz-galactic-year',
      term: {
        name: 'orbit',
        pronunciation: 'OR-bit',
        meaning: 'a curved path made by gravity',
      },
      copy: {
        progress: 'The galaxy’s slow clock',
        eyebrow: 'DISCOVERY 02 · GALACTIC CLOCK',
        location: 'PAUSE AND PREDICT',
        title: 'How long is the Sun’s galactic year?',
        lede: 'Earth circles the Sun in one year. The whole Solar System also circles the Milky Way’s center on a much larger clock.',
        question: 'One trip around the galaxy takes about…',
        options: [
          '230 days',
          '230 thousand years',
          '230 million years',
        ],
        answer: 2,
        explanation: 'One galactic year is about 230 million Earth years. Our Solar System moves quickly, but the path around the enormous Milky Way is even more enormous.',
      },
    },
    {
      id: 'crab-pulsar',
      kind: 'story',
      image: 'assets/images/06-crab-pulsar.webp',
      tone: 'pulsar',
      layout: 'left',
      focal: { desktop: '66% 49%', mobile: '62% 50%' },
      waypoint: 'A 6,500-LY SIGNAL',
      audio: '08-crab-pulsar',
      term: {
        name: 'pulsar',
        pronunciation: 'PULL-sar',
        meaning: 'a spinning neutron star whose beam sweeps past us',
      },
      copy: {
        progress: 'A lighthouse made by a star',
        eyebrow: '06 · THE CRAB PULSAR',
        location: 'A STELLAR AFTERLIFE',
        title: 'A city-size core flashes 30 times a second.',
        lede: 'A massive star exploded. Its crushed center became a neutron star that spins, beams, and powers the glowing Crab Nebula.',
        facts: [
          { value: '≈10 km', label: 'Tiny diameter', caption: 'A stellar core small enough to fit across a city' },
          { value: '30 / second', label: 'Lighthouse flashes', caption: 'Its beams sweep past Earth as it spins' },
          { value: '≈6,500 ly', label: 'Signal distance', caption: 'The remnant glows in many kinds of light' },
        ],
        note: 'This scene combines X-ray and visible-light structure. The bright ring is energized material around a neutron star, not a black hole.',
      },
    },
    {
      id: 'central-molecular-zone',
      kind: 'story',
      image: 'assets/images/07-central-molecular-zone.webp',
      tone: 'cmz',
      layout: 'right',
      focal: { desktop: '39% 52%', mobile: '44% 52%' },
      waypoint: 'THE INNER 1,000 LY',
      audio: '09-central-molecular-zone',
      term: {
        name: 'wavelength',
        pronunciation: 'WAVE-length',
        meaning: 'a kind of light, including light our eyes cannot see',
      },
      copy: {
        progress: 'The storm around the heart',
        eyebrow: '07 · CENTRAL MOLECULAR ZONE',
        location: 'DUST, GAS, AND STAR CLUSTERS',
        title: 'The center hides behind a cosmic dust storm.',
        lede: 'The inner galaxy is crowded with old stars, young clusters, tangled gas, and dark clouds that block ordinary visible light.',
        facts: [
          { value: 'Infrared', label: 'Through the dust', caption: 'Longer wavelengths reveal hidden stars' },
          { value: 'Radio', label: 'Molecules on a map', caption: 'ALMA traces cold gas by its faint signals' },
          { value: 'Arches', label: 'Young star cluster', caption: 'About a thousand hot stars live close together' },
        ],
        note: 'These colors translate several invisible wavelengths. They are a science map made beautiful—not the view human eyes would see.',
      },
    },
    {
      id: 'sagittarius-a',
      kind: 'story',
      image: 'assets/images/08-sagittarius-a.webp',
      tone: 'heart',
      layout: 'left',
      focal: { desktop: '68% 49%', mobile: '64% 49%' },
      waypoint: '≈27,000 LIGHT-YEARS',
      audio: '10-sagittarius-a',
      term: {
        name: 'event horizon',
        pronunciation: 'ee-VENT huh-RYE-zun',
        meaning: 'the boundary beyond which light cannot return',
      },
      copy: {
        progress: 'At the center',
        eyebrow: '08 · SAGITTARIUS A*',
        location: 'THE MILKY WAY’S BLACK HOLE',
        title: 'We found the invisible by watching a star dance.',
        lede: 'At the exact center sits Sagittarius A*, a black hole with more than four million times the Sun’s mass.',
        facts: [
          { value: '4.3 million', label: 'Suns of mass', caption: 'Packed into a remarkably compact region' },
          { value: '16 years', label: 'Star S2’s orbit', caption: 'Its path tests gravity near the black hole' },
          { value: 'Earth-sized', label: 'Virtual telescope', caption: 'Eight radio observatories made the 2017 image data' },
        ],
        note: 'The black hole itself is dark. Glowing gas and bent radio light create the ring-like shadow image released in 2022.',
      },
    },
    {
      id: 'quiz-invisible-center',
      kind: 'quiz',
      image: 'assets/images/08-sagittarius-a.webp',
      tone: 'heart',
      layout: 'left',
      focal: { desktop: '68% 49%', mobile: '64% 49%' },
      waypoint: 'DISCOVERY 3 / 3',
      audio: '11-quiz-invisible-center',
      term: {
        name: 'evidence',
        pronunciation: 'EV-ih-dens',
        meaning: 'clues tested carefully to explain what we observe',
      },
      copy: {
        progress: 'Clues around the invisible',
        eyebrow: 'DISCOVERY 03 · GRAVITY DETECTIVE',
        location: 'PAUSE AND PREDICT',
        title: 'How did we know a black hole was there?',
        lede: 'A black hole sends no light from inside its horizon, so astronomers had to follow the clues around it.',
        question: 'Which clue first revealed the hidden giant?',
        options: [
          'A photograph of its solid black surface',
          'Stars racing around one tiny unseen point',
          'A loud rumble traveling through empty space',
        ],
        answer: 1,
        explanation: 'Astronomers tracked stars whipping around a tiny invisible region for decades. Their orbits revealed millions of Suns’ worth of mass. Later, the Event Horizon Telescope imaged the glowing radio ring around its shadow.',
      },
    },
    {
      id: 'finale-one-galaxy',
      kind: 'finale',
      image: 'assets/images/09-home-thread-finale.webp',
      tone: 'finale',
      layout: 'right',
      focal: { desktop: '53% 48%', mobile: '52% 48%' },
      waypoint: 'HOME IS STILL SHINING',
      audio: '12-finale-one-galaxy',
      term: {
        name: 'curiosity',
        pronunciation: 'kyoor-ee-OSS-ih-tee',
        meaning: 'the brave habit of asking one more good question',
      },
      copy: {
        progress: 'The light leads home',
        eyebrow: 'FINALE · ONE GALAXY',
        location: 'THE JOURNEY CONTINUES',
        title: 'The center was never separate from home.',
        lede: 'Every star family, planet-making cloud, stellar remnant, and hidden radio signal belongs to the same Milky Way we see at night.',
        facts: [
          { value: 'One galaxy', label: 'Many neighborhoods', caption: 'No two studied star systems look quite the same' },
          { value: 'Light', label: 'Our messenger', caption: 'Color, timing, and motion carry distant clues' },
          { value: 'Questions', label: 'Still ahead', caption: 'Better telescopes keep changing the map' },
        ],
        note: 'We cannot make this physical trip yet. But every careful observation lets our minds travel—and the next discovery may begin with your question.',
      },
    },
  ],
};

window.GALAXY_CENTER_STORY = GALAXY_CENTER_STORY;
