'use strict';

const STORY_SLIDES = [
  {
    id: 'land-of-light',
    kind: 'story',
    image: 'assets/images/archipelago-hero.webp',
    tone: 'coast',
    layout: 'left',
    progress: '海と光',
    eyebrow: '01 · LAND & LIGHT',
    date: '北緯55°–69°',
    title: '北へ、細長い国。',
    lede: 'ノルウェーと背中を合わせ、バルト海へひらくスウェーデン。南北の長さは、季節そのものの表情を変えます。',
    details: [
      { value: 'Stockholm', label: '首都', caption: '島々を橋で結ぶ水辺の都市' },
      { value: 'krona', label: '通貨', caption: 'スウェーデン・クローナ' },
      { value: '青 × 黄', label: '国旗', caption: '空と光を思わせる二色' },
    ],
    note: '北極圏より北では、夏に太陽が沈まない日が続き、冬には太陽が昇らない時期があります。',
    word: { sv: 'hej', jp: 'こんにちは', pronunciation: 'ヘイ' },
    audio: 'land-of-light',
  },
  {
    id: 'viking-routes',
    kind: 'story',
    image: 'assets/images/viking-routes.webp',
    tone: 'history',
    layout: 'right',
    progress: '海の道',
    eyebrow: '02 · VIKING AGE',
    date: '800–1050',
    title: '海は、境界ではなく道だった。',
    lede: 'スウェーデンから出たヴァイキング時代の旅人は、略奪だけでなく交易と移住のため、主に東へ向かいました。',
    details: [
      { value: '東へ', label: '主な航路', caption: 'バルト海から河川をたどる' },
      { value: '2,500+', label: 'ルーン石碑', caption: '今も国内に残る記憶の石' },
      { value: '交易', label: '運んだもの', caption: '毛皮・鉄・銀、そして物語' },
    ],
    note: '船は現在のロシアを通り、黒海やカスピ海、ビザンツ帝国やアラブ世界につながりました。「ヴァイキング＝戦士」だけではない歴史です。',
    word: { sv: 'resa', jp: '旅をする', pronunciation: 'レーサ' },
    audio: 'viking-routes',
  },
  {
    id: 'quiz-viking',
    kind: 'quiz',
    image: 'assets/images/viking-routes.webp',
    tone: 'history',
    layout: 'right',
    progress: '小クイズ',
    eyebrow: 'QUIZ 01 · 海図をひらく',
    date: '発見 1 / 3',
    title: 'スウェーデンの船は、どちらへ？',
    lede: 'ヴァイキング時代、スウェーデンからの遠征・交易が特に伸びた方向を選んでください。',
    question: 'もっとも特徴的な航路は？',
    options: [
      '西へ、大西洋を越えて北米へ',
      '東へ、バルト海と河川をたどって',
      '南へ、アフリカ西岸をまわって',
    ],
    answer: 1,
    explanation: '正解は「東へ」。現在のロシアを流れる川をたどり、黒海・カスピ海方面まで交易圏を広げました。北米へ渡った航海は、主にノルウェーやアイスランド側の物語です。',
    word: { sv: 'öster', jp: '東', pronunciation: 'エステル' },
    audio: 'quiz-viking',
  },
  {
    id: 'vasa-era',
    kind: 'story',
    image: 'assets/images/vasa-1628.webp',
    tone: 'royal',
    layout: 'left',
    progress: '王国と巨船',
    eyebrow: '03 · KINGDOM & VASA',
    date: '1523–1628',
    title: '王国は強くなり、船は沈んだ。',
    lede: '1523年、グスタフ・ヴァーサが王に選ばれ、近代スウェーデン国家の土台が築かれます。17世紀にはバルト海の大国へ。',
    details: [
      { value: '1523', label: '新しい王国', caption: 'カルマル同盟から離れる' },
      { value: '1628', label: 'ヴァーサ号', caption: '処女航海で港内に沈没' },
      { value: '1961', label: 'ふたたび光へ', caption: '333年後に引き揚げ' },
    ],
    note: '豪華な軍艦ヴァーサ号は、出港後まもなく風を受けて傾き沈没。冷たく酸素の少ない海水が木材を守り、現在はストックホルムでほぼ実物の姿に出会えます。',
    word: { sv: 'skepp', jp: '船', pronunciation: 'フェップ' },
    audio: 'vasa-era',
  },
  {
    id: 'modern-democracy',
    kind: 'story',
    image: 'assets/images/democracy-1921.webp',
    tone: 'civic',
    layout: 'left',
    progress: '声の時代',
    eyebrow: '04 · A MODERN SOCIETY',
    date: '1766–2024',
    title: '力の時代から、声の時代へ。',
    lede: '大国の時代が終わると、議会・産業・市民社会が国の形を変えていきました。一直線ではない、長い社会づくりです。',
    details: [
      { value: '1766', label: '出版の自由', caption: '世界で最初に法律で確立' },
      { value: '1921', label: '普通・平等選挙', caption: '女性も国政選挙で投票' },
      { value: '1995', label: 'EU加盟', caption: '欧州統合へ参加' },
      { value: '2024', label: 'NATO加盟', caption: '非同盟政策の大きな転換' },
    ],
    note: '19世紀末から工業化が進み、20世紀には福祉国家の制度が整えられました。現在は国王を国家元首とする議会制民主主義です。',
    word: { sv: 'rösta', jp: '投票する', pronunciation: 'レスター' },
    audio: 'modern-democracy',
  },
  {
    id: 'nature-access',
    kind: 'story',
    image: 'assets/images/sapmi-midnight-sun.webp',
    tone: 'nature',
    layout: 'left',
    progress: '森とサープミ',
    eyebrow: '05 · NATURE & SÁPMI',
    date: 'MIDNIGHT SUN',
    title: '森は、みんなの教室。',
    lede: '国土のおよそ7割は森林。湖、群島、山地を身近に感じる暮らしを支えるのが「自然享受権」です。',
    details: [
      { value: 'allemansrätten', label: '自然享受権', caption: '私有地でも一定範囲で自然へ' },
      { value: 'Sápmi', label: 'サープミ', caption: '国境を越えて続くサーミの文化圏' },
      { value: '白夜', label: '北極圏の夏', caption: '夜になっても太陽が沈まない' },
    ],
    note: '自然享受権は「どこでも自由」という意味ではありません。住居や耕作地を避け、地域の規則を守り、自然を傷つけない責任と一組です。',
    word: { sv: 'skog', jp: '森', pronunciation: 'スクーグ' },
    audio: 'nature-access',
  },
  {
    id: 'quiz-nature',
    kind: 'quiz',
    image: 'assets/images/sapmi-midnight-sun.webp',
    tone: 'nature',
    layout: 'left',
    progress: '小クイズ',
    eyebrow: 'QUIZ 02 · 森の約束',
    date: '発見 2 / 3',
    title: '自由とセットになるものは？',
    lede: '自然享受権「アッレマンスレット」を表す、いちばん大切な考え方を選んでください。',
    question: '森や湖を楽しむときの合言葉は？',
    options: [
      '早い者勝ち、好きなだけ持ち帰る',
      '国立公園の中だけ自由に歩ける',
      '邪魔をしない、壊さない',
    ],
    answer: 2,
    explanation: '「邪魔をしない、壊さない」が核心です。歩く、泳ぐ、ベリーを摘む自由には、家や畑から距離を取り、動植物と土地の持ち主へ配慮する責任があります。',
    word: { sv: 'frihet', jp: '自由', pronunciation: 'フリーヘート' },
    audio: 'quiz-nature',
  },
  {
    id: 'fika-culture',
    kind: 'story',
    image: 'assets/images/fika.webp',
    tone: 'fika',
    layout: 'left',
    progress: '湯気の時間',
    eyebrow: '06 · EVERYDAY SWEDEN',
    date: 'COFFEE O’CLOCK',
    title: 'フィーカは、急がない技術。',
    lede: 'コーヒーと甘いものを囲み、いったん手を止める。フィーカは食べ物の名前ではなく、人と時間を分け合う習慣です。',
    details: [
      { value: 'fika', label: 'ひと休み', caption: '家でも職場でも、誰かと一緒に' },
      { value: 'kanelbulle', label: 'シナモンロール', caption: 'カルダモンと粒砂糖の香り' },
      { value: 'lagom', label: 'ほどよく', caption: '多すぎず、少なすぎず' },
    ],
    note: '「ラーゴム」は魔法の国民性ではなく、場面に応じた“ちょうどよさ”を表す日常語。フィーカも形式より、会話の余白をつくることが主役です。',
    word: { sv: 'fika', jp: 'お茶の時間を楽しむ', pronunciation: 'フィーカ' },
    audio: 'fika-culture',
  },
  {
    id: 'ideas-nobel',
    kind: 'story',
    image: 'assets/images/ideas-inventions.webp',
    tone: 'ideas',
    layout: 'left',
    progress: '世界への発明',
    eyebrow: '07 · IDEAS THAT TRAVEL',
    date: '1742–',
    title: '小さな国から、日常を変える。',
    lede: '温度の測り方、安全ベルト、世界的な賞。スウェーデン発のアイデアには「広く役立つ形へ」という視点が見えます。',
    details: [
      { value: '1742', label: 'セルシウス尺度', caption: '最初は0と100が今と逆向き' },
      { value: '1901', label: '最初のノーベル賞', caption: '遺言から生まれた国際賞' },
      { value: '1959', label: '三点式シートベルト', caption: 'ニルス・ボーリンが開発' },
    ],
    note: 'ノーベル賞の物理学・化学・生理学または医学・文学はストックホルムで、平和賞だけはノルウェーのオスロで授与されます。',
    word: { sv: 'idé', jp: 'アイデア', pronunciation: 'イデー' },
    audio: 'ideas-nobel',
  },
  {
    id: 'quiz-nobel',
    kind: 'quiz',
    image: 'assets/images/ideas-inventions.webp',
    tone: 'ideas',
    layout: 'left',
    progress: '小クイズ',
    eyebrow: 'QUIZ 03 · 金色の封筒',
    date: '発見 3 / 3',
    title: 'ひとつだけ、別の街へ。',
    lede: 'ノーベル賞のうち、授賞式がストックホルムではなくオスロで開かれる分野はどれでしょう？',
    question: 'ノルウェーで授与されるのは？',
    options: [
      'ノーベル平和賞',
      'ノーベル文学賞',
      'ノーベル物理学賞',
    ],
    answer: 0,
    explanation: '平和賞だけがオスロで授与されます。アルフレッド・ノーベルの遺言で、平和賞の選考はノルウェーの委員会に託されました。',
    word: { sv: 'fred', jp: '平和', pronunciation: 'フレード' },
    audio: 'quiz-nobel',
  },
  {
    id: 'pop-culture',
    kind: 'story',
    image: 'assets/images/pop-studio.webp',
    tone: 'pop',
    layout: 'left',
    progress: 'ポップとデザイン',
    eyebrow: '08 · CULTURE, AMPLIFIED',
    date: 'FROM 1970s TO NOW',
    title: '北のメロディーが、世界で鳴る。',
    lede: 'ABBA、ロクセット、アヴィーチー、そして数多くの作曲家。スウェーデンは長く、世界のポップ音楽を裏側からも動かしてきました。',
    details: [
      { value: 'ABBA', label: '世界へ開いた扉', caption: '歌える旋律と国際的な視点' },
      { value: 'music schools', label: '地域の音楽教育', caption: '若い才能が楽器と出会う場所' },
      { value: 'streaming', label: '音楽 × 技術', caption: 'Spotifyもストックホルム生まれ' },
    ],
    note: '長い冬の内向きな時間、自治体の音楽教育、早いデジタル化、小さな国内市場から外へ向かう視線。その組み合わせが「スウェーデン音楽の奇跡」を支えました。',
    word: { sv: 'musik', jp: '音楽', pronunciation: 'ムシーク' },
    audio: 'pop-culture',
  },
  {
    id: 'finale',
    kind: 'finale',
    image: 'assets/images/archipelago-hero.webp',
    tone: 'coast',
    layout: 'left',
    progress: '旅の余韻',
    eyebrow: 'TACK · 旅のおわり',
    date: 'また会う日まで',
    title: '青と金の、その先へ。',
    lede: '海を道にした人々、沈んだ巨船、森と自由の約束、湯気の向こうの会話、世界へ旅したアイデア。スウェーデンの入口は、ひとつではありません。',
    details: [
      { value: '歴史', label: '覚えておきたいこと', caption: '大国から議会制民主主義へ' },
      { value: '自然', label: '持ち帰りたい約束', caption: '邪魔をしない、壊さない' },
      { value: '余白', label: '試してみたい習慣', caption: '誰かとフィーカをする' },
    ],
    note: '旅はここで終わり。でも次に青と黄色の旗を見たとき、きっとその奥に、森の匂いとシナモンの香りが少しだけ見えるはずです。',
    word: { sv: 'tack så mycket', jp: 'どうもありがとう', pronunciation: 'タック ソー ミュッケ' },
    audio: 'finale',
  },
];

window.STORY_SLIDES = STORY_SLIDES;
