openapi: 3.1.0
info:
  title: Lentmiien Core API
  version: '1.0.0'
  summary: Primary JSON endpoints that power bin packing, health logs, chat exports, and automation hand-offs.
  description: |
    This document captures the REST endpoints mounted under `/api`. They back the Vue tools,
    health log dashboards, and automation agents that seed Chat5 conversations and schedule tasks.
    All routes require an authenticated session cookie (`connect.sid`) unless otherwise noted.
servers:
  - url: http://localhost:3000
    description: Local development
  - url: https://lentmiien.local
    description: Internal tunnel
tags:
  - name: BinPacking
    description: 3D bin packing helper endpoints.
  - name: Health
    description: Health diary CRUD operations.
  - name: Chat
    description: Chat transcript exports for downstream tooling.
  - name: Automation
    description: Utility endpoints for schedule/task automation.
security:
  - sessionCookie: []
paths:
  /api/binpacking:
    post:
      summary: Run a 3D bin packing attempt
      description: >
        Validates the requested container/items payload and forwards it to the configured
        `binPackingService`. Bruteforce requests are capped at 7 total items to protect the worker.
      tags: [BinPacking]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BinPackingRequest'
      responses:
        '200':
          description: Bin packing attempt accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BinPackingResponse'
        '400':
          description: Validation failure or bruteforce guardrail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'
        '502':
          description: Upstream packer failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'
  /api/getHealthEntries:
    get:
      summary: List health log entries
      description: >
        Returns either all entries or the slice inside `[start, end]`. Results are sorted descending
        by `dateOfEntry`.
      tags: [Health]
      parameters:
        - in: query
          name: start
          schema:
            type: string
            format: date
          description: Inclusive start date (`YYYY-MM-DD`). Provide both `start` and `end` to filter.
        - in: query
          name: end
          schema:
            type: string
            format: date
          description: Inclusive end date (`YYYY-MM-DD`). Provide both `start` and `end` to filter.
      responses:
        '200':
          description: Array of entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthEntry'
  /api/updateHealthEntry:
    post:
      summary: Upsert a health entry
      tags: [Health]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthEntryMutation'
      responses:
        '200':
          description: Persisted entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthEntry'
        '400':
          description: Invalid date format or payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'
  /api/uploadHealthCsv:
    post:
      summary: Append batched vitals from CSV
      description: >
        Accepts a structured array generated by the CSV uploader and applies the key/value pairs to
        either `basicData` or `medicalRecord`.
      tags: [Health]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthCsvUpload'
      responses:
        '200':
          description: Entries that were created/updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthEntry'
  /api/deleteHealthEntry:
    post:
      summary: Delete a health entry by date
      tags: [Health]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - date
              properties:
                date:
                  type: string
                  format: date
      responses:
        '200':
          description: Confirmation payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Invalid date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemResponse'
  /api/getChatEntries:
    get:
      summary: Export Chat5 conversations by date range
      description: >
        Fetches the requesting user's Chat5 conversations updated between `start` and `end`
        (inclusive) and returns them in a streamlined transcript format suitable for agents.
      tags: [Chat]
      parameters:
        - in: query
          name: start
          schema:
            type: string
            format: date
          required: true
        - in: query
          name: end
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          description: Array of exported chats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConversationExport'
  /api/testConnect:
    get:
      summary: Lightweight connectivity probe
      tags: [Automation]
      responses:
        '200':
          description: OK ping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusEnvelope'
  /api/fetchFeedback:
    get:
      summary: Retrieve the latest feedback message stub
      description: >
        Loads a hard-coded Chat5 conversation (`689d3d435f68766cf42f085f`) and returns the most
        recent assistant reply. Used by voice assistants to read nightly recaps.
      tags: [Chat]
      responses:
        '200':
          description: Last assistant message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/setTask:
    post:
      summary: Create a lightweight schedule task
      description: >
        Automation-friendly endpoint that mirrors the `/scheduleTask` forms. If no `userId` is
        provided, the authenticated user's name is used instead.
      tags: [Automation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetTaskRequest'
      responses:
        '200':
          description: Creation status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetTaskResponse'
components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: connect.sid
      description: Obtained after signing in via `/login`.
  schemas:
    ProblemResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          default: false
        message:
          type: string
        issues:
          type: object
          additionalProperties: true
    StatusEnvelope:
      type: object
      properties:
        status:
          type: string
          example: OK
    BinPackingRequest:
      type: object
      required:
        - algorithm
        - container
        - items
      properties:
        algorithm:
          type: string
          enum: [laff, plain, bruteforce]
          description: Bruteforce is capped at 7 total item instances.
        container:
          $ref: '#/components/schemas/Container'
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Item'
    Container:
      type: object
      required: [id, w, d, h, emptyWeight, maxLoadWeight]
      properties:
        id:
          type: string
        w:
          type: number
          minimum: 0
        d:
          type: number
          minimum: 0
        h:
          type: number
          minimum: 0
        emptyWeight:
          type: number
          minimum: 0
        maxLoadWeight:
          type: number
          minimum: 0
    Item:
      type: object
      required: [id, w, d, h, weight, qty]
      properties:
        id:
          type: string
        w:
          type: number
          minimum: 0
        d:
          type: number
          minimum: 0
        h:
          type: number
          minimum: 0
        weight:
          type: number
          minimum: 0
        qty:
          type: integer
          minimum: 1
    BinPackingResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          description: Raw response from the bin packing worker.
          type: object
        meta:
          $ref: '#/components/schemas/BinPackingMeta'
    BinPackingMeta:
      type: object
      properties:
        algorithm:
          type: string
        totalItemCount:
          type: integer
        uniqueItems:
          type: integer
        containerId:
          type: string
    HealthEntryMutation:
      type: object
      required:
        - date
      properties:
        date:
          type: string
          format: date
        basic:
          $ref: '#/components/schemas/HealthMap'
        medical:
          $ref: '#/components/schemas/HealthMap'
        diary:
          description: Comma-separated string or array of message IDs.
          oneOf:
            - type: string
            - type: array
              items:
                type: string
    HealthCsvUpload:
      type: object
      required:
        - inputDataArray
        - type
      properties:
        type:
          type: string
          enum: [basic, medical]
        inputDataArray:
          type: array
          items:
            type: object
            required:
              - date
              - dataToAppend
            properties:
              date:
                type: string
                format: date
              dataToAppend:
                $ref: '#/components/schemas/HealthMap'
    HealthEntry:
      type: object
      properties:
        _id:
          type: string
        dateOfEntry:
          type: string
          format: date
        basicData:
          $ref: '#/components/schemas/HealthMap'
        medicalRecord:
          $ref: '#/components/schemas/HealthMap'
        diary:
          type: array
          items:
            type: string
        measurementType:
          type: string
        measurementContext:
          type: string
        tags:
          type: array
          items:
            type: string
        notes:
          type: string
        personalizedThresholds:
          type: object
          additionalProperties:
            type: object
            properties:
              min:
                type: number
              max:
                type: number
        analyticsSummary:
          type: object
          properties:
            windowSize:
              type: number
            insights:
              type: array
              items:
                type: object
                properties:
                  metric:
                    type: string
                  trend:
                    type: string
            alerts:
              type: array
              items:
                type: object
                properties:
                  metric:
                    type: string
                  threshold:
                    type: number
                  value:
                    type: number
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    HealthMap:
      type: object
      additionalProperties:
        type: string
    ConversationExport:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        updated_date:
          type: string
          format: date-time
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ConversationMessage'
    ConversationMessage:
      type: object
      properties:
        role:
          type: string
          enum: [user, assistant]
        text:
          type: string
        html:
          type: string
        images:
          type: array
          items:
            type: string
            description: Image filename relative to `public/img`.
    SetTaskRequest:
      type: object
      required:
        - title
        - type
      properties:
        title:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [presence, todo, tobuy]
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        userId:
          type: string
        location:
          type: string
        purpose:
          type: string
    SetTaskResponse:
      type: object
      properties:
        status:
          type: string
          enum: [OK, Failed]
        doc:
          type: object
          description: Newly created `Task` document when available.
x-yaml-viewer:
  domain: Core API
  highlights:
    - Health metrics ingestion & diary exports for the analytics notebooks.
    - Bin packing helper shared with the Vue dashboard and CLI runners.
    - Automation-friendly task creator used by calendar agents.
  examples:
    - label: Fetch health entries
      description: Pull a 7-day window to hydrate local notebooks.
      snippet: |
        curl -b cookie.txt \
          "http://localhost:3000/api/getHealthEntries?start=2025-01-01&end=2025-01-07"
    - label: Bin packing (plain)
      description: Minimal payload leveraging the `plain` heuristic.
      snippet: |
        curl -b cookie.txt -H "Content-Type: application/json" \
          -X POST http://localhost:3000/api/binpacking \
          -d @payloads/binpacking-sample.json
