'use strict';

const STORY_SLIDES = [
  {
    id: 'the-signal',
    kind: 'story',
    chapter: 'Origin',
    image: 'assets/images/first-signal.webp',
    tone: 'signal',
    layout: 'left',
    focal: '50% 50%',
    progress: 'The first signal',
    eyebrow: '01 · ORIGIN',
    date: '1964',
    title: 'A ladder made of light.',
    lede: 'Nikolai Kardashev began with a practical SETI question: what kind of distant technology could a telescope actually notice?',
    details: [
      { value: '1964', label: 'The proposal', caption: 'A scale born from radio astronomy' },
      { value: '3', label: 'Original classes', caption: 'World · star · galaxy' },
      { value: '1 axis', label: 'What it measures', caption: 'Available power, not wisdom' },
    ],
    note: 'This journey uses the familiar modern normalization: Type I ≈ 10¹⁶ W, Type II ≈ 10²⁶ W, and Type III ≈ 10³⁶ W. Kardashev’s original numerical thresholds were different.',
    term: { label: 'Signal word', name: 'technosignature', meaning: 'a detectable effect of technology' },
    audio: 'the-signal',
  },
  {
    id: 'humanity-073',
    kind: 'story',
    chapter: 'Baseline',
    image: 'assets/images/humanity-night.webp',
    tone: 'earth',
    layout: 'right',
    focal: '50% 50%',
    progress: 'Humanity now',
    eyebrow: '02 · OUR COORDINATE',
    date: 'K ≈ 0.73',
    title: 'We are a decimal civilization.',
    lede: 'Humanity moves a little over twenty trillion watts on average—immense on a human scale, still a fraction of a planetary one.',
    details: [
      { value: '≈ 2 × 10¹³ W', label: 'Humanity now', caption: 'Using recent total-energy demand' },
      { value: 'K ≈ 0.73', label: 'Continuous scale', caption: 'An estimate, not a precise rank' },
      { value: '≈ 500×', label: 'To Type I', caption: 'The wattage gap alone' },
    ],
    note: 'Different energy-accounting methods move the estimate by a few hundredths. “About 0.73” is more honest than pretending the coordinate is exact.',
    term: { label: 'Scale word', name: 'exajoule', meaning: '10¹⁸ joules of energy' },
    audio: 'humanity-073',
  },
  {
    id: 'quiz-measure',
    kind: 'quiz',
    chapter: 'Discovery',
    image: 'assets/images/humanity-night.webp',
    tone: 'earth',
    layout: 'right',
    focal: '50% 50%',
    progress: 'Discovery 1',
    eyebrow: 'DISCOVERY 01 · CALIBRATE',
    date: '1 / 3',
    title: 'What does the scale actually rate?',
    lede: 'The name sounds like a civilization scorecard. Kardashev’s measuring stick is much narrower.',
    question: 'Choose the quantity that sets the Kardashev type.',
    options: [
      'How morally advanced a society is',
      'How much usable power it commands',
      'How many planets it has visited',
    ],
    answer: 1,
    explanation: 'The scale tracks power on a logarithmic ladder. It says nothing by itself about justice, happiness, intelligence, or survival—and those may be the harder achievements.',
    term: { label: 'Keep in mind', name: 'logarithmic', meaning: 'each step represents a power-of-ten leap' },
    audio: 'quiz-measure',
  },
  {
    id: 'type-one',
    kind: 'story',
    chapter: 'Type I',
    image: 'assets/images/type-one-world.webp',
    tone: 'planet',
    layout: 'left',
    focal: '50% 50%',
    progress: 'Planetary',
    eyebrow: '03 · TYPE I',
    date: '≈ 10¹⁶ W',
    title: 'A planet learns to steer.',
    lede: 'Type I is not a weather remote. It is a civilization able to run planetary infrastructure without breaking the world that carries it.',
    details: [
      { value: '10¹⁶ W', label: 'Power scale', caption: 'About 500 times today’s use' },
      { value: '≈ 10²¹ J', label: 'One-day buffer', caption: 'At full Type I throughput' },
      { value: '1 planet', label: 'Shared system', caption: 'Grid · climate · biosphere · orbit' },
    ],
    note: 'Earth intercepts roughly 1.7 × 10¹⁷ W of sunlight. At Type I power, direct waste heat and ecological side effects become design constraints, not footnotes.',
    term: { label: 'Core idea', name: 'planetary stewardship', meaning: 'capability paired with long-term care' },
    audio: 'type-one',
  },
  {
    id: 'planetary-threshold',
    kind: 'story',
    chapter: 'Transition I → II',
    image: 'assets/images/planetary-threshold.webp',
    tone: 'lunar',
    layout: 'right',
    focal: '50% 50%',
    progress: 'Leave the cradle',
    eyebrow: '04 · THE FIRST THRESHOLD',
    date: 'CENTURIES?',
    title: 'The first rung is a survival test.',
    lede: 'The bridge to Type I is a million coordinated systems: clean power, storage, planetary defense, trusted automation, and industry beyond Earth.',
    details: [
      { value: 'DART', label: 'Defense hint', caption: 'We have deliberately shifted an asteroid orbit' },
      { value: '494M km', label: 'Network hint', caption: 'A deep-space laser link record' },
      { value: 'Moon → asteroids', label: 'Industry hint', caption: 'Use local material beyond Earth' },
    ],
    note: 'These are tiny demonstrations, not proof that Type I is inevitable. The key transition is from heroic missions to reliable, repairable infrastructure that can outlast generations.',
    term: { label: 'Builder’s word', name: 'in-situ resources', meaning: 'using material found where you work' },
    audio: 'planetary-threshold',
  },
  {
    id: 'quiz-type-one',
    kind: 'quiz',
    chapter: 'Discovery',
    image: 'assets/images/type-one-world.webp',
    tone: 'planet',
    layout: 'left',
    focal: '50% 50%',
    progress: 'Discovery 2',
    eyebrow: 'DISCOVERY 02 · PLANET CHECK',
    date: '2 / 3',
    title: 'Which future looks most Type I?',
    lede: 'Look past the spectacle. A planetary civilization has to keep working through storms, failures, and political change.',
    question: 'Choose the strongest sign of Type I capability.',
    options: [
      'A resilient, low-carbon planetary system',
      'Perfect control of tomorrow’s weather',
      'One extremely powerful reactor',
    ],
    answer: 0,
    explanation: 'Type I is a system achievement. A miracle reactor would help, but grids, storage, ecosystems, materials, safety, and legitimate coordination must all survive together.',
    term: { label: 'System word', name: 'resilience', meaning: 'the ability to recover without collapse' },
    audio: 'quiz-type-one',
  },
  {
    id: 'type-two',
    kind: 'story',
    chapter: 'Type II',
    image: 'assets/images/type-two-swarm.webp',
    tone: 'stellar',
    layout: 'right',
    focal: '50% 50%',
    progress: 'Stellar',
    eyebrow: '05 · TYPE II',
    date: '≈ 10²⁶ W',
    title: 'A star becomes an archipelago.',
    lede: 'Type II lives at stellar scale. The plausible icon is not a solid shell, but a vast ecology of independent collectors, habitats, factories, and radiators.',
    details: [
      { value: '3.828 × 10²⁶ W', label: 'The Sun', caption: 'Nominal solar luminosity' },
      { value: '10 billion ×', label: 'From Type I', caption: 'Another ten orders of magnitude' },
      { value: 'swarm', label: 'Likely architecture', caption: 'Separate objects in many orbits' },
    ],
    note: '“Dyson sphere” is often pictured as one rigid ball. Distributed swarms are far more physically plausible, can grow gradually, and leave room for stable orbital families.',
    term: { label: 'Megastructure', name: 'Dyson swarm', meaning: 'independent collectors orbiting a star' },
    audio: 'type-two',
  },
  {
    id: 'stellar-industry',
    kind: 'story',
    chapter: 'Transition II → III',
    image: 'assets/images/stellar-industry.webp',
    tone: 'forge',
    layout: 'left',
    focal: '50% 50%',
    progress: 'Build the swarm',
    eyebrow: '06 · THE STELLAR FORGE',
    date: 'PLANETARY MASS',
    title: 'The real megastructure is the supply chain.',
    lede: 'Collectors are the easy part to draw. Mining, fabrication, station-keeping, repair, traffic control, and heat rejection are the civilization-sized machine.',
    details: [
      { value: '≈ 2.8 × 10²¹ m²', label: 'One-percent capture', caption: 'Collector area near Earth’s orbit' },
      { value: '≈ 3 × 10¹⁹ kg', label: 'At 10 g/m²', caption: 'An aggressive film-only estimate' },
      { value: 'infrared', label: 'The receipt', caption: 'Used energy ultimately leaves as heat' },
    ],
    note: 'The area and mass figures are order-of-magnitude inferences. Real systems also need structure, wiring, propulsion, redundancy, and radiators—often much more mass than the collecting film.',
    term: { label: 'Physics word', name: 'exergy', meaning: 'the useful part of an energy flow' },
    audio: 'stellar-industry',
  },
  {
    id: 'quiz-waste-heat',
    kind: 'quiz',
    chapter: 'Discovery',
    image: 'assets/images/stellar-industry.webp',
    tone: 'forge',
    layout: 'left',
    focal: '50% 50%',
    progress: 'Discovery 3',
    eyebrow: 'DISCOVERY 03 · COSMIC RECEIPT',
    date: '3 / 3',
    title: 'Where does all that power go?',
    lede: 'A swarm can convert starlight into industry, motion, habitats, or computation. Physics still balances the books.',
    question: 'Which signal would astronomers expect after the work is done?',
    options: [
      'Extra ultraviolet starlight',
      'No trace at all from perfect efficiency',
      'A surplus of mid-infrared waste heat',
    ],
    answer: 2,
    explanation: 'Energy can change form, but ordinary work eventually becomes heat. A large warm infrared excess is therefore a classic technosignature—though natural dust can imitate it.',
    term: { label: 'Search band', name: 'mid-infrared', meaning: 'thermal light beyond human vision' },
    audio: 'quiz-waste-heat',
  },
  {
    id: 'type-three',
    kind: 'story',
    chapter: 'Type III',
    image: 'assets/images/type-three-galaxy.webp',
    tone: 'galactic',
    layout: 'right',
    focal: '50% 50%',
    progress: 'Galactic',
    eyebrow: '07 · TYPE III',
    date: '≈ 10³⁶ W',
    title: 'A galaxy has no single now.',
    lede: 'Type III is not one bigger object. It is billions of stellar-scale nodes spread across distances that turn coordination into archaeology.',
    details: [
      { value: '100,000 ly', label: 'Milky Way span', caption: 'About one hundred millennia for light' },
      { value: '100–400B', label: 'Stars', caption: 'NASA’s current broad estimate' },
      { value: '≈ 2.6B Suns', label: '10³⁶ W', caption: 'A few billion solar equivalents' },
    ],
    note: 'A Type III civilization is more plausibly a civilizational ecology than a single empire: local cultures, machines, archives, and biospheres linked by delayed protocols.',
    term: { label: 'Network mode', name: 'delay-tolerant', meaning: 'built to act without an immediate reply' },
    audio: 'type-three',
  },
  {
    id: 'meaning-of-the-scale',
    kind: 'story',
    chapter: 'Meaning',
    image: 'assets/images/light-lag.webp',
    tone: 'silence',
    layout: 'left',
    focal: '50% 50%',
    progress: 'The speed limit',
    eyebrow: '08 · WHAT THE SCALE MEANS',
    date: 'NO FASTER THAN LIGHT',
    title: 'Power is a footprint, not a destiny.',
    lede: 'At galactic scale, the rarest resource may not be energy. It may be trust that survives distance, autonomy, and deep time.',
    details: [
      { value: '≈ 1M years', label: 'At 0.1c', caption: 'One Milky Way crossing, minimum' },
      { value: 'local first', label: 'Control model', caption: 'Every node must think for itself' },
      { value: 'no obvious KIII', label: 'Search result', caption: 'Evidence so far, never proof of absence' },
    ],
    note: 'Infrared galaxy surveys have not found an obvious civilization rerouting most of a nearby galaxy’s starlight. Quiet, efficient, partial, or unfamiliar technology could be much harder to recognize.',
    term: { label: 'Better metaphor', name: 'civilizational ecology', meaning: 'many evolving lineages, not one command center' },
    audio: 'meaning-of-the-scale',
  },
  {
    id: 'finale',
    kind: 'finale',
    chapter: 'Finale',
    image: 'assets/images/finale-horizon.webp',
    tone: 'horizon',
    layout: 'left',
    focal: '50% 50%',
    progress: 'The next signal',
    eyebrow: 'ASCENT · FINALE',
    date: 'THE FUTURE IS LOCAL FIRST',
    title: 'The scale ends. The launch begins.',
    lede: 'Planet. Star. Galaxy. The numbers expand, but the first real step is intimate: learning to keep a shared world alive while our reach grows.',
    details: [
      { value: 'Steward', label: 'Type I lesson', caption: 'Power must preserve its home' },
      { value: 'Build', label: 'Type II lesson', caption: 'Infrastructure is the wonder' },
      { value: 'Trust', label: 'Type III lesson', caption: 'Values must travel without control' },
    ],
    note: 'No rung is guaranteed, and bigger is not automatically better. But every durable grid, restored ecosystem, safer machine, and curious telescope makes the future less imaginary.',
    term: { label: 'Your coordinate', name: 'agency', meaning: 'the capacity to choose and act' },
    audio: 'finale',
  },
];

window.STORY_SLIDES = STORY_SLIDES;
