'use strict';

const DEEP_OCEAN_STORY = {
  meta: {
    title: 'Deep sea journey',
    chapters: 8,
    quizzes: 3,
    duration: '10–15',
    maximumDepth: 10935,
    researchChecked: '2026-07-28',
  },

  ui: {
    en: {
      documentLanguage: 'en',
      pageTitle: 'Deep sea journey',
      metaDescription: 'A cinematic bilingual animal journey from the meeting of river and sea to the deepest ocean trench.',
      skipLink: 'Skip to the current chapter',
      backToGames: 'Back to games',
      brandLabel: 'Deep sea journey, an animal descent',
      brandSubtitle: 'AN ANIMAL DESCENT',
      languageLabel: 'Language',
      infoOpen: 'Open controls, media notes, and sources',
      panelControl: 'Panel',
      panelHide: 'Hide information panel',
      panelShow: 'Show information panel',
      panelQuizLocked: 'The information panel stays open until this discovery is answered',
      panelShownAnnouncement: 'Information panel shown.',
      panelHiddenAnnouncement: 'Information panel hidden. The artwork, narration, and journey controls remain available.',
      captionsControl: 'Transcript',
      captionsShow: 'Show transcript',
      captionsHide: 'Hide transcript',
      captionsShownAnnouncement: 'Narration transcript shown.',
      captionsHiddenAnnouncement: 'Narration transcript hidden.',
      soundControl: 'Sound',
      soundOff: 'Turn narration off',
      soundOn: 'Turn narration on',
      soundOnAnnouncement: 'Narration turned on.',
      soundOffAnnouncement: 'Narration turned off.',
      storyStageLabel: 'Deep ocean story',
      introOverline: 'THE WATER IS CALLING',
      introKicker: 'FROM SHORE TO THE HADAL',
      introLede: 'Follow familiar animals from the bright edge of the sea into a world of living lights, gentle giants, falling food, and tiny survivors.',
      introLanguageLabel: 'Choose your language',
      introEnglishVoice: 'Lessac narration',
      introJapaneseVoice: 'Shikoku Metan narration',
      introStatsLabel: 'Experience overview',
      chapterStatLabel: 'chapters',
      durationStatLabel: 'minutes',
      quizStatLabel: 'discoveries',
      startHint: 'Narration begins after you press start',
      startLabel: 'Begin the dive',
      headphoneNote: 'Headphones welcome · sound can be changed anytime',
      introCoordinatePrimary: 'SEA LEVEL · 0 M',
      introCoordinateSecondary: 'NEXT STOP · SUNLIT WATER',
      previous: 'Back',
      previousAria: 'Previous scene',
      next: 'Dive deeper',
      nextAria: 'Next scene',
      answerToContinue: 'Choose an answer',
      answerToContinueAria: 'Choose an answer before continuing',
      returnToSurface: 'Return to shore',
      returnToSurfaceAria: 'Restart the journey at the shore',
      navigationLabel: 'Journey navigation',
      scenesLabel: '{count} scenes',
      progressSceneAria: 'Go to scene {number}, {title}',
      sceneAnnouncement: 'Scene {number} of {count}. {title}',
      narrationReady: 'Narration ready',
      narrationLoading: 'Loading narration…',
      narrationPlaying: 'English narration playing',
      narrationPaused: 'Narration paused',
      narrationComplete: 'Narration complete',
      narrationMuted: 'Narration is off',
      narrationError: 'Audio unavailable · transcript ready',
      narrationPlayPrompt: 'Press replay to hear this scene',
      narrationReplay: 'Replay this scene’s narration',
      narrationProgress: 'Narration progress',
      transcriptHeading: 'Narration transcript',
      transcriptAria: 'Narration transcript',
      transcriptClose: 'Close transcript',
      transcriptLoading: 'Loading transcript…',
      transcriptError: 'The transcript could not be loaded. The shorter scene text remains available.',
      depthWord: 'DEPTH WORD',
      quizGroup: 'Answer choices: {question}',
      quizOption: 'Choice {number}: {label}',
      quizCorrectLead: 'Bright thinking!',
      quizDiscoverLead: 'A new discovery!',
      quizCorrectAnnouncement: 'That is right. {explanation}',
      quizDiscoverAnnouncement: 'Here is the discovery. {explanation}',
      finaleVisitedLabel: 'Discoveries visited',
      finaleComplete: 'All three curious pauses explored',
      finaleIncomplete: 'Every discovery remains open on the depth rail',
      restart: 'Dive again ↺',
      languageChanged: 'Language changed to English. This scene’s narration and transcript were replaced; journey progress is unchanged.',
      infoOverline: 'DIVE NOTES',
      infoTitle: 'About this journey',
      infoClose: 'Close',
      controlsHeading: 'Controls',
      controlsCopyOne: 'Use the arrows below, the progress rings, or the ← and → keys to move. Number keys 1–3 answer a discovery.',
      controlsCopyTwo: 'Press R to replay narration, C for the transcript, M for sound, P for the information panel, and L to switch language.',
      controlsCopyThree: 'Hiding the panel leaves navigation, language, sound, transcript, and depth controls available. Discoveries open the panel automatically and restore your preference afterward.',
      mediaHeading: 'Media & accessibility',
      mediaCopyOne: 'The scene artwork was generated specifically for this experience and reviewed as a cinematic artist’s interpretation, not a field photograph or scale diagram.',
      mediaCopyTwo: 'English narration uses the local Piper Lessac voice. Japanese narration uses the local Voicevox Shikoku Metan voice. Audio and exact transcripts are stored locally.',
      mediaCopyThree: 'Decorative motion follows your reduced-motion setting. Narration begins only after the start button, and a transcript is available independently of the story panel.',
      sourcesHeading: 'Research sources',
      sourcesIntro: 'Facts and record language were checked against these institutional sources on July 28, 2026. Ocean-zone boundaries are useful conventions, and animal depth ranges vary by species and location.',
    },
    ja: {
      documentLanguage: 'ja',
      pageTitle: 'Deep sea journey · 深海への旅',
      metaDescription: '川と海が出会う場所から最深部の海溝まで、生きものと一緒に潜る英日対応の映像ガイド。',
      skipLink: '現在の章へ移動',
      backToGames: 'ゲーム一覧へ戻る',
      brandLabel: 'Deep sea journey、生きものと潜る旅',
      brandSubtitle: '生きものと潜る旅',
      languageLabel: '言語',
      infoOpen: '操作方法、メディアについて、出典を開く',
      panelControl: 'パネル',
      panelHide: '情報パネルを隠す',
      panelShow: '情報パネルを表示',
      panelQuizLocked: '発見クイズに答えるまでは、情報パネルを隠せません',
      panelShownAnnouncement: '情報パネルを表示しました。',
      panelHiddenAnnouncement: '情報パネルを隠しました。画像、ナレーション、移動操作はそのまま使えます。',
      captionsControl: '字幕',
      captionsShow: '字幕を表示',
      captionsHide: '字幕を隠す',
      captionsShownAnnouncement: 'ナレーション字幕を表示しました。',
      captionsHiddenAnnouncement: 'ナレーション字幕を隠しました。',
      soundControl: '音声',
      soundOff: 'ナレーションをオフ',
      soundOn: 'ナレーションをオン',
      soundOnAnnouncement: 'ナレーションをオンにしました。',
      soundOffAnnouncement: 'ナレーションをオフにしました。',
      storyStageLabel: '深海をめぐる物語',
      introOverline: '水の世界が呼んでいる',
      introKicker: '浜辺から超深海へ',
      introLede: '明るい海辺で出会う生きものから、自分で光る魚、静かな巨人、空から降る食べもの、最深部の小さな命まで。いっしょに潜ってみましょう。',
      introLanguageLabel: '言語を選んでください',
      introEnglishVoice: 'Lessac の英語ナレーション',
      introJapaneseVoice: '四国めたんの日本語ナレーション',
      introStatsLabel: '体験の概要',
      chapterStatLabel: 'つの章',
      durationStatLabel: '分',
      quizStatLabel: 'つの発見',
      startHint: '開始ボタンを押すとナレーションが始まります',
      startLabel: '潜航をはじめる',
      headphoneNote: 'イヤホンもおすすめ · 音声はいつでも切り替えられます',
      introCoordinatePrimary: '海面 · 水深 0 M',
      introCoordinateSecondary: 'つぎの場所 · 太陽の海',
      previous: 'もどる',
      previousAria: '前の場面へ',
      next: 'もっと深くへ',
      nextAria: '次の場面へ',
      answerToContinue: '答えを選ぼう',
      answerToContinueAria: '答えを選んでから進んでください',
      returnToSurface: '浜辺へもどる',
      returnToSurfaceAria: '浜辺から旅をやり直す',
      navigationLabel: '旅の移動',
      scenesLabel: '全{count}場面',
      progressSceneAria: '{number}場面目「{title}」へ移動',
      sceneAnnouncement: '全{count}場面のうち{number}場面目。{title}',
      narrationReady: 'ナレーションの準備ができました',
      narrationLoading: 'ナレーションを読み込んでいます…',
      narrationPlaying: '日本語ナレーションを再生中',
      narrationPaused: 'ナレーションを一時停止',
      narrationComplete: 'ナレーションを聞き終えました',
      narrationMuted: 'ナレーションはオフです',
      narrationError: '音声を再生できません · 字幕を利用できます',
      narrationPlayPrompt: '再生ボタンでこの場面を聞けます',
      narrationReplay: 'この場面のナレーションをもう一度聞く',
      narrationProgress: 'ナレーションの進み具合',
      transcriptHeading: 'ナレーション字幕',
      transcriptAria: 'ナレーション字幕',
      transcriptClose: '字幕を閉じる',
      transcriptLoading: '字幕を読み込んでいます…',
      transcriptError: '字幕を読み込めませんでした。短い場面説明は情報パネルで読めます。',
      depthWord: '深海ワード',
      quizGroup: '答えの選択肢：{question}',
      quizOption: '選択肢{number}：{label}',
      quizCorrectLead: 'その通り！',
      quizDiscoverLead: '新しい発見！',
      quizCorrectAnnouncement: '正解です。{explanation}',
      quizDiscoverAnnouncement: '新しい発見です。{explanation}',
      finaleVisitedLabel: '立ち寄った発見クイズ',
      finaleComplete: '3つの寄り道をすべて探検しました',
      finaleIncomplete: '見逃した発見には深度レールから戻れます',
      restart: 'もう一度潜る ↺',
      languageChanged: '日本語に切り替えました。この場面の音声と字幕だけを交換し、旅の進み具合は保っています。',
      infoOverline: '潜航ノート',
      infoTitle: 'この旅について',
      infoClose: '閉じる',
      controlsHeading: '操作',
      controlsCopyOne: '画面下の矢印、深度リング、またはキーボードの ← と → で移動できます。発見クイズは数字の1〜3でも答えられます。',
      controlsCopyTwo: 'R は音声の再生、C は字幕、M は音声、P は情報パネル、L は言語の切り替えです。',
      controlsCopyThree: 'パネルを隠しても、移動、言語、音声、字幕、深度の操作は残ります。発見クイズでは自動でパネルが開き、答えたあとには以前の好みに戻ります。',
      mediaHeading: 'メディアとアクセシビリティ',
      mediaCopyOne: '場面画像はこの作品のために生成し、科学的な見え方を確認した映画的なアーティスト・インプレッションです。調査写真や正確な縮尺図ではありません。',
      mediaCopyTwo: '英語音声はローカルの Piper Lessac、日本語音声はローカルの Voicevox 四国めたんで制作しました。音声と一致する字幕はすべて端末内の素材です。',
      mediaCopyThree: '装飾的な動きは端末の「視差効果を減らす」設定に従います。音声は開始操作のあとだけ再生され、字幕は情報パネルとは別に開けます。',
      sourcesHeading: '調査出典',
      sourcesIntro: '事実と記録の表現は、2026年7月28日に次の機関資料で確認しました。海の層の境界は便利な目安で、生きものの深度は種や場所によって変わります。',
    },
  },

  sources: [
    {
      url: 'https://oceanservice.noaa.gov/facts/estuary.html',
      title: {
        en: 'NOAA National Ocean Service · What is an estuary?',
        ja: 'NOAA 国立海洋局 · 河口域とは',
      },
    },
    {
      url: 'https://oceanservice.noaa.gov/facts/coral.html',
      title: {
        en: 'NOAA National Ocean Service · Are corals animals or plants?',
        ja: 'NOAA 国立海洋局 · サンゴは動物、それとも植物？',
      },
    },
    {
      url: 'https://www.fisheries.noaa.gov/species/green-turtle',
      title: {
        en: 'NOAA Fisheries · Green turtle',
        ja: 'NOAA 水産局 · アオウミガメ',
      },
    },
    {
      url: 'https://oceanservice.noaa.gov/facts/light_travel.html',
      title: {
        en: 'NOAA National Ocean Service · How far does light travel in the ocean?',
        ja: 'NOAA 国立海洋局 · 海の光はどこまで届く？',
      },
    },
    {
      url: 'https://oceanexplorer.noaa.gov/ocean-fact/vertical-migration/',
      title: {
        en: 'NOAA Ocean Exploration · Vertical migration',
        ja: 'NOAA 海洋探査局 · 生きものの鉛直移動',
      },
    },
    {
      url: 'https://twilightzone.whoi.edu/explore-the-otz/creature-features/lanternfishes/',
      title: {
        en: 'Woods Hole Oceanographic Institution · Lanternfishes',
        ja: 'ウッズホール海洋研究所 · ランタンフィッシュ',
      },
    },
    {
      url: 'https://ocean.si.edu/ocean-life/fish/bioluminescence',
      title: {
        en: 'Smithsonian Ocean · Bioluminescence',
        ja: 'スミソニアン海洋ポータル · 生物発光',
      },
    },
    {
      url: 'https://www.fisheries.noaa.gov/feature-story/sperm-whales-revealing-mysteries-deep',
      title: {
        en: 'NOAA Fisheries · Sperm whales in the deep',
        ja: 'NOAA 水産局 · 深海のマッコウクジラ',
      },
    },
    {
      url: 'https://ocean.si.edu/ocean-life/invertebrates/giant-squid',
      title: {
        en: 'Smithsonian Ocean · Giant squid',
        ja: 'スミソニアン海洋ポータル · ダイオウイカ',
      },
    },
    {
      url: 'https://oceanexplorer.noaa.gov/education/hydrothermal-vents-volcanoes/',
      title: {
        en: 'NOAA Ocean Exploration · Hydrothermal vents and volcanoes',
        ja: 'NOAA 海洋探査局 · 熱水噴出孔と海底火山',
      },
    },
    {
      url: 'https://oceanexplorer.noaa.gov/ocean-fact/marinesnow/',
      title: {
        en: 'NOAA Ocean Exploration · What is marine snow?',
        ja: 'NOAA 海洋探査局 · マリンスノーとは',
      },
    },
    {
      url: 'https://ocean.si.edu/ocean-life/invertebrates/grimpoteuthis-dumbo-octopus',
      title: {
        en: 'Smithsonian Ocean · Dumbo octopus',
        ja: 'スミソニアン海洋ポータル · メンダコの仲間',
      },
    },
    {
      url: 'https://www.kaiyodai.ac.jp/faculty/r/news/detail/8336_1.html',
      title: {
        en: 'Tokyo University of Marine Science and Technology · Fish filmed at 8,336 metres',
        ja: '東京海洋大学 · 水深8,336メートルで確認された最深の魚',
      },
    },
    {
      url: 'https://repository.library.noaa.gov/view/noaa/33477',
      title: {
        en: 'NOAA Library · Revised depth of Challenger Deep',
        ja: 'NOAA 図書館 · チャレンジャー海淵の改訂深度',
      },
    },
    {
      url: 'https://www.whoi.edu/ocean-learning-hub/ocean-facts/why-is-pressure-different-in-the-ocean/',
      title: {
        en: 'Woods Hole Oceanographic Institution · Pressure in the ocean',
        ja: 'ウッズホール海洋研究所 · 海の圧力',
      },
    },
    {
      url: 'https://schmidtocean.org/cruise-log-post/the-deepest-living-animals/',
      title: {
        en: 'Schmidt Ocean Institute · The deepest living animals',
        ja: 'シュミット海洋研究所 · 最深部に生きる動物',
      },
    },
    {
      url: 'https://www.jamstec.go.jp/godac/j/godac/kaiyou/deepsea.html',
      title: {
        en: 'JAMSTEC GODAC · What is the deep sea?',
        ja: 'JAMSTEC 国際海洋環境情報センター · 深海とは',
      },
    },
  ],

  scenes: [
    {
      id: 'estuary-gateway',
      kind: 'story',
      image: 'assets/images/estuary-dawn.webp',
      tone: 'shore',
      layout: 'right',
      focal: { desktop: '48% 54%', mobile: '44% 55%' },
      depth: 2,
      audio: '01-estuary-gateway',
      term: {
        name: 'estuary',
        pronunciation: { en: 'ES-choo-air-ee', ja: 'エスチュアリー' },
        meaning: { en: 'where river and sea mix', ja: '川の水と海水が混ざる河口域' },
      },
      copy: {
        en: {
          progress: 'River meets sea',
          eyebrow: '01 · THE GATEWAY',
          depthLabel: '0–10 m',
          title: 'Where two waters meet.',
          lede: 'Our journey begins in an estuary, where a river carries fresh water into the salty rhythm of the tide.',
          facts: [
            { value: 'Fresh + salt', label: 'Brackish water', caption: 'The mixture shifts with every tide' },
            { value: 'Nursery', label: 'A sheltered beginning', caption: 'Young fish find food and hiding places' },
            { value: 'Amphipods', label: 'Beach hoppers', caption: 'Tiny crustaceans recycle washed-up seaweed' },
          ],
          note: 'Remember the little beach hoppers. Much deeper relatives will meet us again near the bottom of the world.',
        },
        ja: {
          progress: '川と海の出会い',
          eyebrow: '01 · 海への入口',
          depthLabel: '0〜10 m',
          title: 'ふたつの水が、出会う場所。',
          lede: '旅の始まりは河口域。川の淡水が、潮とともに動く海水へそっと混ざります。',
          facts: [
            { value: '淡水 + 海水', label: '汽水', caption: '潮の満ち引きで濃さが変わる' },
            { value: '育ち場', label: '守られた入口', caption: '小さな魚の食事と隠れ場所' },
            { value: '端脚類', label: 'ハマトビムシの仲間', caption: '打ち上がった海藻を片づける甲殻類' },
          ],
          note: '小さなハマトビムシの仲間を覚えておいてください。世界の底で、深海にすむ親戚ともう一度出会います。',
        },
      },
    },
    {
      id: 'sunlit-neighborhood',
      kind: 'story',
      image: 'assets/images/sunlit-reef.webp',
      tone: 'sunlit',
      layout: 'left',
      focal: { desktop: '56% 50%', mobile: '57% 51%' },
      depth: 30,
      audio: '02-sunlit-neighborhood',
      term: {
        name: 'symbiosis',
        pronunciation: { en: 'sim-bee-OH-sis', ja: 'シンバイオーシス' },
        meaning: { en: 'different species living closely together', ja: 'ちがう種が近くで支え合う共生' },
      },
      copy: {
        en: {
          progress: 'Sunlit neighbors',
          eyebrow: '02 · THE SUNLIT ZONE',
          depthLabel: '0–200 m',
          title: 'A reef is a city of animals.',
          lede: 'Sunlight powers a crowded neighborhood where coral polyps build homes and every creature has a different job.',
          facts: [
            { value: 'Animal', label: 'A coral polyp', caption: 'Thousands can build one stony colony' },
            { value: 'Air', label: 'Green sea turtle', caption: 'A marine reptile that must surface to breathe' },
            { value: 'Partners', label: 'Clownfish + anemone', caption: 'Shelter and care flow both ways' },
          ],
          note: 'Most significant sunlight is found in the upper 200 metres. Below it, plants and algae can no longer make food by photosynthesis.',
        },
        ja: {
          progress: '太陽のご近所',
          eyebrow: '02 · 太陽の海',
          depthLabel: '0〜200 m',
          title: 'サンゴ礁は、動物たちの町。',
          lede: '太陽の光が届くにぎやかな町では、サンゴのポリプが家をつくり、それぞれの生きものに役目があります。',
          facts: [
            { value: '動物', label: 'サンゴのポリプ', caption: '小さな体が集まり、石のような群体をつくる' },
            { value: '空気', label: 'アオウミガメ', caption: '息をするため海面へ戻る、海のは虫類' },
            { value: 'パートナー', label: 'クマノミ + イソギンチャク', caption: 'かくれ家と手入れを分け合う' },
          ],
          note: '強い太陽光が届く目安は水深200メートルまで。その下では、植物や藻類は光合成で食べものをつくれません。',
        },
      },
    },
    {
      id: 'quiz-surface-breath',
      kind: 'quiz',
      image: 'assets/images/sunlit-reef.webp',
      tone: 'sunlit',
      layout: 'left',
      focal: { desktop: '56% 50%', mobile: '57% 51%' },
      depth: 30,
      audio: '03-quiz-surface-breath',
      answer: 1,
      term: {
        name: 'reptile',
        pronunciation: { en: 'REP-tile', ja: 'レプタイル' },
        meaning: { en: 'an air-breathing animal group', ja: '空気を吸う、は虫類' },
      },
      copy: {
        en: {
          progress: 'Discovery 1',
          eyebrow: 'DISCOVERY 01 · TAKE A BREATH',
          depthLabel: '30 m',
          title: 'Who needs the sky?',
          lede: 'Three reef neighbors spend their day underwater, but one still carries lungs.',
          question: 'Which animal must return to the surface to breathe?',
          options: ['Clownfish', 'Green sea turtle', 'Sea star'],
          explanation: 'The green sea turtle is a reptile with lungs. It can hold its breath, but it must eventually reach the surface for air. Clownfish and sea stars take oxygen from the water.',
        },
        ja: {
          progress: '発見 1',
          eyebrow: '発見 01 · ひと息つこう',
          depthLabel: '30 m',
          title: '空が必要なのは、だれ？',
          lede: '3匹とも水中で一日を過ごします。でも、1匹だけは肺で息をしています。',
          question: '息をするために海面へ戻る生きものは？',
          options: ['クマノミ', 'アオウミガメ', 'ヒトデ'],
          explanation: 'アオウミガメは、肺をもつは虫類です。長く息を止められますが、最後には空気を吸いに海面へ戻ります。クマノミとヒトデは、水の中から酸素を取り込みます。',
        },
      },
    },
    {
      id: 'twilight-commute',
      kind: 'story',
      image: 'assets/images/twilight-migration.webp',
      tone: 'twilight',
      layout: 'right',
      focal: { desktop: '48% 48%', mobile: '46% 50%' },
      depth: 500,
      audio: '04-twilight-commute',
      term: {
        name: 'photophore',
        pronunciation: { en: 'FOH-toh-for', ja: 'フォトフォア' },
        meaning: { en: 'a light-producing organ', ja: '光をつくる発光器' },
      },
      copy: {
        en: {
          progress: 'The twilight commute',
          eyebrow: '03 · THE TWILIGHT ZONE',
          depthLabel: '200–1,000 m',
          title: 'At sunset, a hidden city rises.',
          lede: 'Lanternfish, shrimp, and jellies wait in dim blue water, then swim upward at night to feed.',
          facts: [
            { value: 'No crops', label: 'Too dim for photosynthesis', caption: 'The last sunlight fades rapidly' },
            { value: 'Photophores', label: 'Lanternfish lights', caption: 'Patterns can hide, signal, and guide' },
            { value: 'Every night', label: 'Vertical migration', caption: 'A vast animal commute toward the surface' },
          ],
          note: 'This daily movement is often described as Earth’s largest animal migration. The travelers also carry carbon from the surface into deeper water.',
        },
        ja: {
          progress: '薄明の大移動',
          eyebrow: '03 · トワイライトゾーン',
          depthLabel: '200〜1,000 m',
          title: '日が沈むと、かくれた町が上がってくる。',
          lede: 'ランタンフィッシュやエビ、クラゲの仲間は薄暗い青の中で待ち、夜になると食事のため上へ泳ぎます。',
          facts: [
            { value: '光合成なし', label: '植物には暗すぎる', caption: '残った太陽光も急に弱くなる' },
            { value: '発光器', label: '魚のおなかの明かり', caption: '姿を隠し、合図を送る光の模様' },
            { value: '毎晩', label: '鉛直移動', caption: '海面へ向かう、とても大きな通勤' },
          ],
          note: 'この動きは、地球最大級の動物の大移動と呼ばれます。旅する生きものは、海面近くの炭素を深い水へ運ぶ役目もあります。',
        },
      },
    },
    {
      id: 'midnight-senses',
      kind: 'story',
      image: 'assets/images/midnight-senses.webp',
      tone: 'midnight',
      layout: 'left',
      focal: { desktop: '54% 49%', mobile: '54% 50%' },
      depth: 1500,
      audio: '05-midnight-senses',
      term: {
        name: 'echolocation',
        pronunciation: { en: 'EK-oh-loh-KAY-shun', ja: 'エコーロケーション' },
        meaning: { en: 'finding things with returning sound', ja: '返ってくる音で物の位置を知る方法' },
      },
      copy: {
        en: {
          progress: 'Senses in darkness',
          eyebrow: '04 · THE MIDNIGHT ZONE',
          depthLabel: '1,000–4,000 m',
          title: 'When eyes are not enough, sound travels.',
          lede: 'There is no sunlight here. A giant squid gathers faint glimmers, an anglerfish carries a lure, and a sperm whale sends clicks into the dark.',
          facts: [
            { value: '≈30 cm', label: 'Giant squid eye', caption: 'Among the largest eyes in the animal world' },
            { value: '8 + 2', label: 'Arms and tentacles', caption: 'Two long feeding tentacles reach beyond eight arms' },
            { value: 'Click · echo', label: 'Sperm whale', caption: 'Sound helps locate squid in deep darkness' },
          ],
          note: 'Deep animals do not “break” darkness. They use tiny clues: a silhouette, a returning echo, a chemical glow, or a vibration in the water.',
        },
        ja: {
          progress: '暗闇の感覚',
          eyebrow: '04 · ミッドナイトゾーン',
          depthLabel: '1,000〜4,000 m',
          title: '目だけで足りなければ、音が旅をする。',
          lede: 'ここには太陽光がありません。ダイオウイカはわずかな光を集め、チョウチンアンコウは明かりを持ち、マッコウクジラは暗闇へクリック音を送ります。',
          facts: [
            { value: '約30 cm', label: 'ダイオウイカの目', caption: '動物の中でも最大級の大きな目' },
            { value: '8 + 2', label: '腕と触腕', caption: '8本の腕より長い、2本のえさ取り用触腕' },
            { value: '音 · 反響', label: 'マッコウクジラ', caption: '返る音で深海のイカを探す' },
          ],
          note: '深海の動物は、暗闇を消すのではありません。影、返ってくる音、化学反応の光、水の振動。小さな手がかりを上手に使います。',
        },
      },
    },
    {
      id: 'quiz-living-light',
      kind: 'quiz',
      image: 'assets/images/midnight-senses.webp',
      tone: 'midnight',
      layout: 'left',
      focal: { desktop: '54% 49%', mobile: '54% 50%' },
      depth: 1500,
      audio: '06-quiz-living-light',
      answer: 2,
      term: {
        name: 'bioluminescence',
        pronunciation: { en: 'BY-oh-loo-min-ESS-ens', ja: 'バイオルミネセンス' },
        meaning: { en: 'light made by a living thing', ja: '生きものがつくる生物発光' },
      },
      copy: {
        en: {
          progress: 'Discovery 2',
          eyebrow: 'DISCOVERY 02 · A LIVING LANTERN',
          depthLabel: '1,500 m',
          title: 'Where does living light begin?',
          lede: 'A lanternfish flashes, an anglerfish glows, and a jelly draws a blue-green ring.',
          question: 'What is bioluminescence?',
          options: [
            'Moonlight stored inside scales',
            'Sparks made when warm bubbles rub together',
            'Light from a chemical reaction in a living thing',
          ],
          explanation: 'Bioluminescence is light produced by a chemical reaction in a living organism. Deep animals use it in different ways—to hide, communicate, startle, or attract food.',
        },
        ja: {
          progress: '発見 2',
          eyebrow: '発見 02 · 生きているランタン',
          depthLabel: '1,500 m',
          title: '生きものの光は、どこから？',
          lede: 'ランタンフィッシュがまたたき、チョウチンアンコウが光り、クラゲの仲間が青緑の輪を描きます。',
          question: '生物発光とは、どんな光？',
          options: [
            'うろこにためた月の光',
            '温かい泡がこすれてできる火花',
            '生きものの体内の化学反応でできる光',
          ],
          explanation: '生物発光は、生きものの体内で起きる化学反応がつくる光です。深海の動物は、姿を隠す、合図する、相手を驚かす、えさを誘うなど、いろいろな使い方をします。',
        },
      },
    },
    {
      id: 'vent-oasis',
      kind: 'story',
      image: 'assets/images/vent-oasis.webp',
      tone: 'vent',
      layout: 'left',
      focal: { desktop: '56% 54%', mobile: '56% 55%' },
      depth: 2500,
      audio: '07-vent-oasis',
      term: {
        name: 'chemosynthesis',
        pronunciation: { en: 'KEE-moh-SIN-thuh-sis', ja: 'ケモシンセシス' },
        meaning: { en: 'making food with chemical energy', ja: '化学エネルギーで食べものをつくる化学合成' },
      },
      copy: {
        en: {
          progress: 'A vent oasis',
          eyebrow: '05 · LIFE WITHOUT SUNLIGHT',
          depthLabel: '≈2,500 m',
          title: 'A garden fed by stone and water.',
          lede: 'Seawater slips into cracks, warms near hot rock, and returns carrying minerals. Around the vent, an oasis gathers.',
          facts: [
            { value: 'No sunlight', label: 'Chemical energy', caption: 'Microbes turn vent chemicals into food' },
            { value: 'No mouth', label: 'Giant tube worm', caption: 'Helpful bacteria live inside its body' },
            { value: '1977', label: 'A surprise to science', caption: 'Thriving vent communities were first observed' },
          ],
          note: 'The dark plume of a “black smoker” is mineral-rich water cooling in the sea—not smoke from a fire and not underwater lava.',
        },
        ja: {
          progress: '熱水のオアシス',
          eyebrow: '05 · 太陽なしの命',
          depthLabel: '約2,500 m',
          title: '岩と水が育てる、深海の庭。',
          lede: '海水が岩の割れ目へ入り、熱い岩の近くで温まり、ミネラルを運んで戻ります。そのまわりに命のオアシスができます。',
          facts: [
            { value: '太陽なし', label: '化学エネルギー', caption: '微生物が熱水の物質から食べものをつくる' },
            { value: '口がない', label: '巨大なハオリムシ', caption: '体内の細菌に食事をつくってもらう' },
            { value: '1977年', label: '科学者のおどろき', caption: 'にぎやかな熱水生物群集を初めて観察' },
          ],
          note: '「ブラックスモーカー」の黒い雲は、ミネラルを含む熱水が冷えて見えるもの。火事の煙でも、海中の溶岩でもありません。',
        },
      },
    },
    {
      id: 'quiz-vent-kitchen',
      kind: 'quiz',
      image: 'assets/images/vent-oasis.webp',
      tone: 'vent',
      layout: 'left',
      focal: { desktop: '56% 54%', mobile: '56% 55%' },
      depth: 2500,
      audio: '08-quiz-vent-kitchen',
      answer: 1,
      term: {
        name: 'microbe',
        pronunciation: { en: 'MY-krohb', ja: 'マイクローブ' },
        meaning: { en: 'a life-form too small to see unaided', ja: '目だけでは見えないほど小さな生きもの' },
      },
      copy: {
        en: {
          progress: 'Discovery 3',
          eyebrow: 'DISCOVERY 03 · THE VENT KITCHEN',
          depthLabel: '2,500 m',
          title: 'Who cooks without sunshine?',
          lede: 'Tube worms, mussels, shrimp, and crabs crowd the vent, but the food web begins much smaller.',
          question: 'What starts the hydrothermal-vent food web?',
          options: [
            'Animals biting pieces from hot rocks',
            'Microbes using energy from chemicals',
            'Sunlight stored inside shiny shells',
          ],
          explanation: 'Special microbes use energy from chemicals such as hydrogen sulfide to make food. Some are eaten; others live inside tube worms or mussels and share what they make.',
        },
        ja: {
          progress: '発見 3',
          eyebrow: '発見 03 · 熱水のキッチン',
          depthLabel: '2,500 m',
          title: '太陽なしで料理するのは、だれ？',
          lede: 'ハオリムシ、貝、エビ、カニが集まります。でも、食べもののつながりは、もっと小さな命から始まります。',
          question: '熱水噴出孔の食物網を始めるものは？',
          options: [
            '熱い岩を動物がかじること',
            '化学物質のエネルギーを使う微生物',
            '光る貝がためていた太陽光',
          ],
          explanation: '特別な微生物が、硫化水素などの化学物質からエネルギーを取り、食べものをつくります。食べられるものもいれば、ハオリムシや貝の体内で暮らし、つくった栄養を分けるものもいます。',
        },
      },
    },
    {
      id: 'abyssal-snow',
      kind: 'story',
      image: 'assets/images/abyssal-snow.webp',
      tone: 'abyss',
      layout: 'right',
      focal: { desktop: '48% 55%', mobile: '47% 56%' },
      depth: 4000,
      audio: '09-abyssal-snow',
      term: {
        name: 'marine snow',
        pronunciation: { en: 'muh-REEN snoh', ja: 'マリンスノー' },
        meaning: { en: 'food particles falling from upper water', ja: '上の海から降る、小さな食べものの粒' },
      },
      copy: {
        en: {
          progress: 'The patient plain',
          eyebrow: '06 · THE EDGE OF THE ABYSS',
          depthLabel: '≈4,000 m',
          title: 'Dinner falls like snow.',
          lede: 'Far from a vent, most deep animals wait for tiny leftovers from the bright ocean to drift down through kilometres of water.',
          facts: [
            { value: 'Weeks', label: 'A slow fall', caption: 'Marine snow can travel a very long way' },
            { value: 'Two fins', label: 'Dumbo octopus', caption: 'Ear-like fins help it hover over the bottom' },
            { value: 'Mud recycler', label: 'Sea cucumber', caption: 'It gathers nutrition from soft sediment' },
          ],
          note: 'Marine snow includes plankton, waste, and other organic pieces. Nothing is wasted: deep animals filter it, gather it, or search the mud it reaches.',
        },
        ja: {
          progress: '静かに待つ平原',
          eyebrow: '06 · 深海平原の入口',
          depthLabel: '約4,000 m',
          title: '夕食が、雪のように降ってくる。',
          lede: '熱水から遠い場所では、多くの深海動物が、明るい海から何キロメートルも落ちてくる小さな食べものを待ちます。',
          facts: [
            { value: '何週間も', label: 'ゆっくり降る', caption: 'マリンスノーの長い旅' },
            { value: '2枚のひれ', label: 'メンダコの仲間', caption: '耳のようなひれで海底近くを泳ぐ' },
            { value: '泥の再生係', label: 'ナマコの仲間', caption: 'やわらかな海底から栄養を集める' },
          ],
          note: 'マリンスノーは、プランクトンや排せつ物などの有機物です。深海の動物は、こし取る、拾う、泥から探すなどして、ほとんど無駄にしません。',
        },
      },
    },
    {
      id: 'hadal-snailfish',
      kind: 'story',
      image: 'assets/images/hadal-snailfish.webp',
      tone: 'hadal',
      layout: 'left',
      focal: { desktop: '58% 58%', mobile: '59% 59%' },
      depth: 8336,
      audio: '10-hadal-snailfish',
      term: {
        name: 'hadal',
        pronunciation: { en: 'HAY-dul', ja: 'ヘイダル' },
        meaning: { en: 'the trench zone below 6,000 metres', ja: '水深6,000メートルより深い海溝の世界' },
      },
      copy: {
        en: {
          progress: 'Life in the trench',
          eyebrow: '07 · THE HADAL ZONE',
          depthLabel: '6,000–11,000 m',
          title: 'A soft fish under a mountain of water.',
          lede: 'Trenches form where one part of Earth’s crust bends beneath another. In their cold slopes, snailfish make softness a strength.',
          facts: [
            { value: '8,336 m', label: 'Deepest fish filmed', caption: 'A juvenile snailfish recorded near Japan in 2022' },
            { value: 'No scales', label: 'A flexible body', caption: 'Gel-like tissues suit immense pressure' },
            { value: 'Amphipods', label: 'Favorite small prey', caption: 'Trench crustaceans gather over the mud' },
          ],
          note: 'The 8,336-metre observation was published in 2023. It is a measured record, not proof that every snailfish species lives that deep.',
        },
        ja: {
          progress: '海溝にすむ魚',
          eyebrow: '07 · 超深海帯',
          depthLabel: '6,000〜11,000 m',
          title: '山ほどの水の下に、やわらかな魚。',
          lede: '地球のプレートが別のプレートの下へ曲がりこむ場所に、海溝ができます。冷たい斜面で、スネイルフィッシュはやわらかさを強みにします。',
          facts: [
            { value: '8,336 m', label: '撮影された最深の魚', caption: '2022年、日本近海で若い個体を記録' },
            { value: 'うろこなし', label: 'しなやかな体', caption: 'ゼラチン質の組織が大きな圧力に合う' },
            { value: 'ヨコエビ類', label: '小さなえもの', caption: '海溝の泥の上に集まる甲殻類' },
          ],
          note: '水深8,336メートルの観察は2023年に論文で発表されました。これは測定された記録で、すべてのスネイルフィッシュがその深さにすむという意味ではありません。',
        },
      },
    },
    {
      id: 'challenger-deep',
      kind: 'story',
      image: 'assets/images/challenger-deep.webp',
      tone: 'trench',
      layout: 'right',
      focal: { desktop: '45% 58%', mobile: '44% 59%' },
      depth: 10935,
      audio: '11-challenger-deep',
      term: {
        name: 'amphipod',
        pronunciation: { en: 'AM-fee-pod', ja: 'アンフィポッド' },
        meaning: { en: 'a many-legged crustacean with different kinds of feet', ja: 'さまざまな脚をもつ、ヨコエビなどの端脚類' },
      },
      copy: {
        en: {
          progress: 'The deepest floor',
          eyebrow: '08 · CHALLENGER DEEP',
          depthLabel: '≈10,935 m',
          title: 'The bottom is small, busy, and alive.',
          lede: 'No fish has been observed this deep, yet the silty floor is not empty. Amphipods hurry toward food, and pressure-loving microbes work unseen.',
          facts: [
            { value: '10,935 ± 6 m', label: 'Measured depth', caption: 'A 2021 pressure-based estimate' },
            { value: '≈1,100×', label: 'Surface pressure', caption: 'Deep animals avoid fragile air spaces' },
            { value: 'Beach cousin', label: 'Hadal amphipod', caption: 'Related to the hoppers at our first shore' },
          ],
          note: 'Depth estimates vary with instruments and corrections. Here, “deepest” means the best measured seafloor estimate, not a perfectly fixed number.',
        },
        ja: {
          progress: 'いちばん深い海底',
          eyebrow: '08 · チャレンジャー海淵',
          depthLabel: '約10,935 m',
          title: '世界の底は、小さく、忙しく、生きている。',
          lede: 'この深さで魚は観察されていません。それでも泥の海底は空っぽではなく、ヨコエビの仲間が食べものへ急ぎ、圧力を好む微生物が見えないところで働きます。',
          facts: [
            { value: '10,935 ± 6 m', label: '測定された深さ', caption: '2021年の圧力測定による推定値' },
            { value: '約1,100倍', label: '海面との圧力差', caption: '深海動物には壊れやすい空気袋がほぼない' },
            { value: '浜辺の親戚', label: '超深海の端脚類', caption: '最初に見たハマトビムシと同じ仲間' },
          ],
          note: '深さの推定値は、機器や補正方法で少し変わります。ここでの「最深」は、海底の最良の測定値という意味で、完全に固定した数字ではありません。',
        },
      },
    },
    {
      id: 'finale-surface',
      kind: 'finale',
      image: 'assets/images/estuary-dawn.webp',
      tone: 'surface',
      layout: 'right',
      focal: { desktop: '48% 54%', mobile: '44% 55%' },
      depth: 0,
      audio: '12-finale-surface',
      term: {
        name: 'wonder',
        pronunciation: { en: 'WUN-der', ja: 'ワンダー' },
        meaning: { en: 'curiosity mixed with awe', ja: '知りたい気持ちと、おどろきが合わさった心' },
      },
      copy: {
        en: {
          progress: 'Back to the light',
          eyebrow: 'FINALE · ONE CONNECTED OCEAN',
          depthLabel: 'SURFACE',
          title: 'Every depth has a way to live.',
          lede: 'A turtle rises for air. Lanternfish follow night. Tube worms share a meal with microbes. A soft fish bends, and a tiny amphipod carries on.',
          facts: [
            { value: 'Sunlight', label: 'Feeds the upper ocean', caption: 'Then sends marine snow toward the deep' },
            { value: 'Chemistry', label: 'Feeds a vent oasis', caption: 'Microbes open another path to food' },
            { value: 'Connection', label: 'Shore to trench', caption: 'One ocean, many astonishing solutions' },
          ],
          note: 'The deep sea is not a collection of monsters. It is a set of neighborhoods, each filled with animals solving the same questions: how to eat, move, hide, meet, and begin again.',
        },
        ja: {
          progress: '光の場所へ',
          eyebrow: 'フィナーレ · つながるひとつの海',
          depthLabel: '海面',
          title: 'どの深さにも、生きる方法がある。',
          lede: 'カメは空気へ上がり、ランタンフィッシュは夜を追い、ハオリムシは微生物と食事を分け、やわらかな魚はしなり、小さな端脚類は歩き続けます。',
          facts: [
            { value: '太陽光', label: '上の海を育てる', caption: 'やがてマリンスノーを深海へ送る' },
            { value: '化学反応', label: '熱水の命を育てる', caption: '微生物が別の食事の道をひらく' },
            { value: 'つながり', label: '浜辺から海溝へ', caption: 'ひとつの海に、たくさんの答え' },
          ],
          note: '深海は、怪物を集めた場所ではありません。それぞれの深さのご近所で、動物たちが「どう食べ、動き、隠れ、出会い、次の命を始めるか」を工夫する世界です。',
        },
      },
    },
  ],
};

window.DEEP_OCEAN_STORY = DEEP_OCEAN_STORY;
