const fs = require('fs');
const path = require('path');
const pug = require('pug');
const domain = require('../../services/taric/historyDomain');
const { verified } = require('../helpers/taricHistoryFixture');
test('history DOM safely labels outcomes, review form, filter URL and CSRF preview; stale save is actionable', async () => {
  const { JSDOM } = await import('jsdom');
  const dom = new JSDOM(pug.renderFile(path.join(__dirname, '../../views/admin_taric_history.pug'), { csrfToken: 'synthetic-csrf' }), { url: 'http://localhost/admin/taric/history?mode=test', runScripts: 'outside-only' });
  const attack = '<img src=x onerror="window.compromised=true"><script>window.compromised=true</script>';
  const row = verified(1); row.facts.name = attack; row.diagnostic = { code: '9999999999', description: attack }; row.suggestion.description = attack;
  const responses = [];
  dom.window.fetch = jest.fn(async (url, opts) => {
    responses.push([url, opts]); let data;
    if (url.includes('/data')) data = { rows: [row], stats: domain.stats([row]), next: null };
    else if (url.endsWith('/review')) return { ok: false, status: 409, json: async () => ({ error: 'STALE' }) };
    else if (url.endsWith('/preview')) data = { profile: domain.PROFILE, algorithm: domain.ALGORITHM, summary: { available: 1, eligible: 1, selected: 1, excluded: 0, groups: 1, excludedByReason: {}, perCode: { '0000000002': 1 } }, snapshotHash: 'a'.repeat(64), skipped: [], candidates: [domain.candidate(row)] };
    else data = { ...row, audit: [row.review], targetInTestCatalog: false };
    return { ok: true, json: async () => data };
  });
  const settle = () => new Promise(setImmediate);
  dom.window.eval(fs.readFileSync(path.join(__dirname, '../../public/js/taric-history.js'), 'utf8')); await settle();
  const doc = dom.window.document;
  expect(doc.querySelector('[name=mode]').value).toBe('test');
  expect(doc.querySelector('#requests').textContent).toContain('0000000002 (changed)');
  expect(doc.querySelector('#requests').textContent).toContain('0000000001');
  doc.querySelector('#requests button').click(); await settle();
  expect(doc.querySelector('#review-target').value).toBe('0000000002');
  expect(doc.querySelector('#approved-description').value).toBe('');
  expect(doc.querySelector('#confirm-target').checked).toBe(false);
  expect(doc.querySelector('#detail-content').textContent).toContain('UNVALIDATED');
  expect(doc.querySelector('#detail-content').textContent).toContain(attack);
  expect(doc.querySelectorAll('img')).toHaveLength(0); expect(dom.window.compromised).toBeUndefined();
  expect(doc.querySelectorAll('script:not([src])')).toHaveLength(0);
  doc.querySelector('#confirm-target').checked = true; doc.querySelector('#review-note').value = 'Synthetic verification';
  doc.querySelector('#review-form').dispatchEvent(new dom.window.Event('submit', { cancelable: true })); await settle();
  expect(doc.querySelector('#status').textContent).toContain('Snapshot changed');
  const save = responses.find(([url]) => url.endsWith('/review'));
  expect(save[1].headers['X-CSRF-Token']).toBe('synthetic-csrf');
  expect(JSON.parse(save[1].body)).toMatchObject({ target: '0000000002', expectedRevision: 1, approvedDescription: null });
  doc.querySelector('#preview').click(); await settle();
  expect(doc.querySelector('#download').disabled).toBe(false);
  expect(doc.querySelector('#preview-content').textContent).toContain('formatter pending');
  expect(responses.find(([url]) => url.endsWith('/preview'))[1].headers['X-CSRF-Token']).toBe('synthetic-csrf');
  doc.querySelector('#selection-limit').value = '2'; doc.querySelector('#selection-limit').dispatchEvent(new dom.window.Event('input'));
  expect(doc.querySelector('#download').disabled).toBe(true);
  doc.querySelector('[name=feedback]').value = 'changed';
  doc.querySelector('#filters').dispatchEvent(new dom.window.Event('submit', { cancelable: true })); await settle();
  expect(dom.window.location.search).toContain('feedback=changed');
  doc.querySelector('#theme').click(); expect(doc.documentElement.dataset.theme).toBe('light');
  dom.window.close();
});
test('empty data is explicit and DB failure does not replace stats with fake zeros', async () => {
  const { JSDOM } = await import('jsdom');
  const dom = new JSDOM(pug.renderFile(path.join(__dirname, '../../views/admin_taric_history.pug'), { csrfToken: 'synthetic' }), { url: 'http://localhost/admin/taric/history', runScripts: 'outside-only' });
  let fail = false;
  dom.window.fetch = jest.fn(async () => ({ ok: !fail, status: fail ? 503 : 200, json: async () => fail ? { error: 'STORAGE_FAILED' } : { rows: [], stats: domain.stats([]), next: null } }));
  dom.window.eval(fs.readFileSync(path.join(__dirname, '../../public/js/taric-history.js'), 'utf8')); await new Promise(setImmediate);
  expect(dom.window.document.querySelector('#requests').textContent).toContain('No requests');
  fail = true; dom.window.document.querySelector('#filters').dispatchEvent(new dom.window.Event('submit', { cancelable: true })); await new Promise(setImmediate);
  expect(dom.window.document.querySelector('#status').textContent).toContain('503: STORAGE_FAILED');
  dom.window.close();
});
